Place.create!([
  {title: "公会堂", address: "北海道小樽市花園５丁目２−１", official_url: "http://otarushiminkaikan.jp/koukai/"},
  {title: "札幌市教育文化会館", address: "北海道札幌市中央区北１条西１３丁目", official_url: "http://www.kyobun.org/"},
  {title: "伝統芸能伝承館森舞台", address: "宮城県登米市登米町寺池桜小路 宮城県登米市登米町寺池上町42", official_url: "http://toyoma.co.jp/facilities-densho/"},
  {title: "庄内能楽館", address: "山形県酒田市浜松町１ 山形県酒田市浜松町1−1", official_url: nil},
  {title: "阿能川会館", address: "群馬県利根郡みなかみ町阿能川５５２", official_url: nil},
  {title: "国立能楽堂", address: "東京都渋谷区千駄ヶ谷４丁目４−１８−１", official_url: "http://www.ntj.jac.go.jp/nou.html"},
  {title: "宝生能楽堂", address: "東京都文京区本郷１丁目５ 本郷1丁目5−9", official_url: "http://www.hosho.or.jp/"},
  {title: "矢来能楽堂", address: "東京都新宿区矢来町６０", official_url: "http://yarai-nohgakudo.com/"},
  {title: "梅若能楽学院会館", address: "東京都中野区東中野２丁目６−１４", official_url: "http://umewakanoh.exblog.jp/"},
  {title: "十四世喜多六平太記念能楽堂", address: "東京都品川区上大崎４丁目６−９", official_url: "http://kita-noh.com/"},
  {title: "観世能楽堂", address: "東京都中央区銀座６丁目１０−１ B3F", official_url: "http://kanze.net/"},
  {title: "公益社団法人 能楽協会", address: "東京都新宿区高田馬場４丁目４０−１３ 双秀ビル", official_url: "http://www.nohgaku.or.jp/"},
  {title: "銕仙会能楽研修所", address: "東京都港区南青山４丁目２１−２１−２９", official_url: "http://www.tessen.org/"},
  {title: "セルリアンタワー能楽堂", address: "東京都渋谷区桜丘町２６−１", official_url: "http://www.ceruleantower-noh.com/"},
  {title: "代々木能舞台", address: "東京都渋谷区代々木４丁目３６ 代々木４丁目３６−１４", official_url: "http://www.yoyoginoubutai.com/"},
  {title: "能楽書林", address: "東京都千代田区神田神保町３丁目 東京都千代田区神田神保町3丁目6−1", official_url: "http://nohgakushorin.co.jp/"},
  {title: "杉並能楽堂", address: "東京都杉並区和田１丁目５５ 和田１丁目５５−９", official_url: "http://www.city.suginami.tokyo.jp/kyouiku/bunkazai/hyouji/1008023.html"},
  {title: "横浜能楽堂", address: "神奈川県横浜市西区紅葉ケ丘２７−２", official_url: "http://ynt.yafjp.org/"},
  {title: "金井能楽堂", address: "新潟県佐渡市中興 新潟県佐渡市中興甲371", official_url: nil},
  {title: "本間家能舞台", address: "新潟県佐渡市吾潟 新潟県佐渡市吾潟丙987", official_url: nil},
  {title: "富山市役所 富山能楽堂", address: "富山県富山市友杉１０９７", official_url: nil},
  {title: "石川県立能楽堂", address: "石川県金沢市石引４丁目１８−３", official_url: "http://www.pref.ishikawa.lg.jp/nougakudo/nougakudoutop.html"},
  {title: "能化公会堂", address: "長野県飯田市北方３４８９−２", official_url: nil},
  {title: "名古屋能楽堂", address: "愛知県名古屋市中区三の丸１丁目１−１−１", official_url: "http://www.bunka758.or.jp/scd24_top.html"},
  {title: "栄能楽堂", address: "愛知県名古屋市中区栄５丁目６−４", official_url: "http://www.k4.dion.ne.jp/~gotou/"},
  {title: "岡崎城二の丸能楽堂", address: "愛知県岡崎市康生町５６１−１", official_url: "http://okazakipark.com/nougalkudou/nougakudou.htm"},
  {title: "大津市立会館伝統芸能会館", address: "滋賀県大津市園城寺町２４６−２４", official_url: "http://www.dentogeinokaikan.net/"},
  {title: "伴能十全堂", address: "吉身一丁目6-31, １丁目-６ 吉身 守山市 滋賀県 524-0021 日本", official_url: "http://www.eonet.ne.jp/~hyougu/"},
  {title: "金剛能楽堂", address: "京都府京都市上京区龍前町 上京区烏丸通一条下る龍前町590", official_url: "http://www.kongou-net.com/"},
  {title: "河村能舞台", address: "京都府京都市上京区柳図子町 京都府京都市上京区烏丸通上立売上る柳図子町320−14", official_url: "http://www.omosiro-noh-taiken.kyoto.jp/"},
  {title: "京都観世会館", address: "京都府京都市左京区岡崎円勝寺町 左京区岡崎円勝寺町44", official_url: "http://www.kyoto-kanze.jp/"},
  {title: "大江能楽堂", address: "京都府京都市中京区橘町（押小路通） 京都府京都市中京区押小路通柳馬場東入橘町646", official_url: "http://www.asahi-net.or.jp/~tn4m-ooe/"},
  {title: "大江能楽会", address: "京都府京都市東山区本町２０丁目４２８", official_url: "http://www.asahi-net.or.jp/~tn4m-ooe/"},
  {title: "京都・市民放射能測定所", address: "京都府京都市伏見区両替町９丁目 京都府京都市伏見区両替町9丁目254−203", official_url: "http://nukecheck.namaste.jp/"},
  {title: "能楽幸流小鼓教室 林木双会", address: "京都府京都市中京区橘町（押小路通）", official_url: "http://mokusoukai.net/"},
  {title: "能楽名盤会", address: "京都府京都市左京区田中上柳町 京都府京都市左京区田中上柳町９０", official_url: nil},
  {title: "北能舞台", address: "京都府京都市下京区門前町", official_url: nil},
  {title: "山本能楽堂", address: "大阪府大阪市中央区徳井町１丁目３−６", official_url: "http://www.noh-theater.com/"},
  {title: "大槻能楽堂", address: "大阪府大阪市中央区上町Ａ 大阪府大阪市中央区上町A−7", official_url: "http://www.noh-kyogen.com/"},
  {title: "本城能楽堂", address: "兵庫県姫路市元塩町１４１", official_url: nil},
  {title: "面塚 観世能楽発祥の地", address: "〒636-0202, 結崎 川西町 磯城郡 奈良県 636-0202 日本", official_url: "http://www.town.nara-kawanishi.lg.jp/contents_detail.php?co=kak&frmId=193"},
  {title: "大濠公園能楽堂", address: "福岡県福岡市中央区大濠公園１−５", official_url: "http://www.ohori-nougaku.jp/"},
  {title: "能学館長崎南教室", address: "長崎県長崎市末石町３７０−５５ シティーハウス伸 2F", official_url: nil},
  {title: "能楽殿", address: "熊本県熊本市中央区水前寺公園７−３４ 〒862-0956", official_url: nil},
  {title: "藤崎八幡宮御旅所能舞台", address: "熊本県熊本市中央区新町３丁目１−２６", official_url: nil},
  {title: "菊池市松囃子能舞台", address: "熊本県菊池市隈府 隈府２１６−５", official_url: nil},
  {title: "平和市民公園能楽堂", address: "大分県大分市牧緑町１−３０", official_url: "http://www.nogaku.jp/"},
  {title: "小能公民館", address: "鹿児島県曽於郡大崎町井俣", official_url: nil},
  {title: "伏見稲荷大社", address: "〒612-0882 京都府京都市伏見区深草藪之内町68", official_url: "http://inari.jp/"}
])
