version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          CLOUDINARY_API_KEY: '561279793255188'
          CLOUDINARY_API_SECRET: -UoOEL2-mIM_LlFERPrSwtU6SiM
          CLOUDINARY_NAME: hezb4lkyp
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: noh_sightdb_test
    working_directory: ~/nohsight
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          # TODO: Find the way to refer cache despite of changin branch.
          # Because everytime I build, in restore_cache, CircleCI says 'no cache is found'

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # TODO: create resotre_cache of yarn

      # Yarn install dependencies
      - run: yarn install

      # Store bundle cache
      - save_cache:
         key: rails-demo-yarn{{ checksum "yarn.lock" }}
         paths:
            - .yarn-cache

      # TODO: Find the way to cache the following packages which usually takes 1 minute for being installed.

      # Install chrome driver for System Spec
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-unstable
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps

      # Database setup
      - run:
         name: Database setup
         command: |
            bundle exec bin/rails db:create
            bundle exec rails db:migrate

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec spec/system --profile 10 \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
