Style.create!([
  {title: "シテ方観世流"},
  {title: "シテ方金春流"},
  {title: "シテ方金剛流"},
  {title: "ワキ方高安流"},
  {title: "笛方森田流"},
  {title: "小鼓方幸流"},
  {title: "小鼓方大倉流"},
  {title: "大鼓方石井流"},
  {title: "太鼓方観世流"},
  {title: "太鼓方金春流"},
  {title: "狂言方大蔵流"}
])

Performer.create!([
  {full_name: "青木 道喜", last_name: "あおき", first_name: "みちよし", style_id: 1},
  {full_name: "浅井 通昭", last_name: "あさい", first_name: "みちあき", style_id: 1},
  {full_name: "浅野 篤義", last_name: "あさの", first_name: "あつよし", style_id: 1},
  {full_name: "井上 裕久", last_name: "いのうえ", first_name: "ひろひさ", style_id: 1},
  {full_name: "井上 和幸", last_name: "いのうえ", first_name: "かずゆき", style_id: 1},
  {full_name: "井上 貴美子", last_name: "いのうえ", first_name: "きみこ", style_id: 1},
  {full_name: "梅田 嘉宏", last_name: "うめだ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦田 保浩", last_name: "うらた", first_name: "やすひろ", style_id: 1},
  {full_name: "浦田 保親", last_name: "うらた", first_name: "やすちか", style_id: 1},
  {full_name: "浦部 好弘", last_name: "うらべ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦部 幸裕", last_name: "うらべ", first_name: "ゆきひろ", style_id: 1},
  {full_name: "大江 又三郎", last_name: "おおえ", first_name: "またさぶろう", style_id: 1},
  {full_name: "大江 信行", last_name: "おおえ", first_name: "のぶゆき", style_id: 1},
  {full_name: "大江 泰正", last_name: "おおえ", first_name: "やすまさ", style_id: 1},
  {full_name: "大江 広祐", last_name: "おおえ", first_name: "こうすけ", style_id: 1},
  {full_name: "大塚 嘉則", last_name: "おおつか", first_name: "よしのり", style_id: 1},
  {full_name: "岡田 すみ子", last_name: "おかだ", first_name: "すみこ", style_id: 1},
  {full_name: "片山 九郎右衛門", last_name: "かたやま", first_name: "くろうえもん", style_id: 1},
  {full_name: "片山 伸吾", last_name: "かたやま", first_name: "しんご", style_id: 1},
  {full_name: "河村 和重", last_name: "かわむら", first_name: "かずしげ", style_id: 1},
  {full_name: "河村 和貴", last_name: "かわむら", first_name: "かずたか", style_id: 1},
  {full_name: "河村 和晃", last_name: "かわむら", first_name: "かずあき", style_id: 1},
  {full_name: "河村 博重", last_name: "かわむら", first_name: "ひろしげ", style_id: 1},
  {full_name: "河村 晴久", last_name: "かわむら", first_name: "はるひさ", style_id: 1},
  {full_name: "河村 晴道", last_name: "かわむら", first_name: "はるみち", style_id: 1},
  {full_name: "河本 望", last_name: "かわもと", first_name: "のぞむ", style_id: 1},
  {full_name: "越賀 隆之", last_name: "こしか", first_name: "たかゆき", style_id: 1},
  {full_name: "小林 慶三", last_name: "こばやし", first_name: "けいぞう", style_id: 1},
  {full_name: "實川 紀", last_name: "じつかわ", first_name: "おさむ", style_id: 1},
  {full_name: "杉浦 豊彦", last_name: "すぎうら", first_name: "とよひこ", style_id: 1},
  {full_name: "武田 欣司", last_name: "たけだ", first_name: "きんじ", style_id: 1},
  {full_name: "武田 邦弘", last_name: "たけだ", first_name: "くにひろ", style_id: 1},
  {full_name: "武田 大志", last_name: "たけだ", first_name: "ひろし", style_id: 1},
  {full_name: "田中 隆夫", last_name: "たなか", first_name: "たかお", style_id: 1},
  {full_name: "田茂井 廣和", last_name: "たもい", first_name: "ひろかず", style_id: 1},
  {full_name: "田茂井 廣道", last_name: "たもい", first_name: "ひろみち", style_id: 1},
  {full_name: "塚本 和雄", last_name: "つかもと", first_name: "かずお", style_id: 1},
  {full_name: "橋本 雅夫", last_name: "はしもと", first_name: "まさお", style_id: 1},
  {full_name: "橋本 光史", last_name: "はしもと", first_name: "こうじ", style_id: 1},
  {full_name: "橋本 磯道", last_name: "はしもと", first_name: "いそみち", style_id: 1},
  {full_name: "橋本 忠樹", last_name: "はしもと", first_name: "ただき", style_id: 1},
  {full_name: "橋本 擴三郎", last_name: "はしもと", first_name: "こうざぶろう", style_id: 1},
  {full_name: "林 喜右衛門", last_name: "はやし", first_name: "きうえもん", style_id: 1},
  {full_name: "林 宗一郎", last_name: "はやし", first_name: "そういちろう", style_id: 1},
  {full_name: "深野 新次郎", last_name: "ふかの", first_name: "しんじろう", style_id: 1},
  {full_name: "深野 貴彦", last_name: "ふかの", first_name: "たかひこ", style_id: 1},
  {full_name: "藤井 千鶴子", last_name: "ふじい", first_name: "ちずこ", style_id: 1},
  {full_name: "古橋 正邦", last_name: "ふるはし", first_name: "まさくに", style_id: 1},
  {full_name: "牧野 和夫", last_name: "まきの", first_name: "かずお", style_id: 1},
  {full_name: "松井 美樹", last_name: "まつい", first_name: "みき", style_id: 1},
  {full_name: "松野 浩行", last_name: "まつの", first_name: "ひろゆき", style_id: 1},
  {full_name: "味方 健", last_name: "みかた", first_name: "けん", style_id: 1},
  {full_name: "味方 玄", last_name: "みかた", first_name: "しずか", style_id: 1},
  {full_name: "味方 團", last_name: "みかた", first_name: "まどか", style_id: 1},
  {full_name: "宮田 宏之", last_name: "みやた", first_name: "ひろゆき", style_id: 1},
  {full_name: "宮本 茂樹", last_name: "みやもと", first_name: "しげき", style_id: 1},
  {full_name: "山田 芙紗子", last_name: "やまだ", first_name: "ふさこ", style_id: 1},
  {full_name: "山田 修司", last_name: "やまだ", first_name: "しゅうじ", style_id: 1},
  {full_name: "吉田 潔司", last_name: "よしだ", first_name: "きよし", style_id: 1},
  {full_name: "吉田 篤史", last_name: "よしだ", first_name: "あつし", style_id: 1},
  {full_name: "吉浪 壽晃", last_name: "よしなみ", first_name: "としあき", style_id: 1},
  {full_name: "分林 道治", last_name: "わけばやし", first_name: "みちはる", style_id: 1},
  {full_name: "鷲尾 周三", last_name: "わしお", first_name: "しゅうぞう", style_id: 1},
  {full_name: "鷲尾 世志子", last_name: "わしお", first_name: "よしこ", style_id: 1},
  {full_name: "石原 昌和", last_name: "いしはら", first_name: "まさかず", style_id: 2},
  {full_name: "上浦 一道", last_name: "うえうら", first_name: "かずみち", style_id: 2},
  {full_name: "植松 洋", last_name: "うえまつ", first_name: "ひろし", style_id: 2},
  {full_name: "岸田 善三郎", last_name: "きしだ", first_name: "ぜんざぶろう", style_id: 2},
  {full_name: "金春 康之", last_name: "こんぱる", first_name: "やすゆき", style_id: 2},
  {full_name: "辻本 實", last_name: "つじもと", first_name: "みのる", style_id: 2},
  {full_name: "南浦 潔", last_name: "みなみうら", first_name: "きよし", style_id: 2},
  {full_name: "今井 清隆", last_name: "いまい", first_name: "きよたか", style_id: 3},
  {full_name: "今井 克紀", last_name: "いまい", first_name: "かつのり", style_id: 3},
  {full_name: "宇髙 通成", last_name: "うたか", first_name: "みちしげ", style_id: 3},
  {full_name: "宇髙 竜成", last_name: "うたか", first_name: "たつしげ", style_id: 3},
  {full_name: "宇髙 徳成", last_name: "うたか", first_name: "のりしげ", style_id: 3},
  {full_name: "漆垣 謙次", last_name: "うるしがき", first_name: "けんじ", style_id: 3},
  {full_name: "小鴨 梨辺華", last_name: "おがも", first_name: "れべっか", style_id: 3},
  {full_name: "小野 芳朗", last_name: "おの", first_name: "よしろう", style_id: 3},
  {full_name: "金剛 龍謹", last_name: "こんごう", first_name: "たつのり", style_id: 3},
  {full_name: "重本 昌也", last_name: "しげもと", first_name: "まさや", style_id: 3},
  {full_name: "嶋崎 暢久", last_name: "しまざき", first_name: "のぶひさ", style_id: 3},
  {full_name: "種田 道一", last_name: "たねだ", first_name: "みちかず", style_id: 3},
  {full_name: "豊島 晃嗣", last_name: "てしま", first_name: "こうじ", style_id: 3},
  {full_name: "豊島 幸洋", last_name: "てしま", first_name: "ゆきひろ", style_id: 3},
  {full_name: "廣田 幸稔", last_name: "ひろた", first_name: "ゆきとし", style_id: 3},
  {full_name: "廣田 泰三", last_name: "ひろた", first_name: "たいぞう", style_id: 3},
  {full_name: "廣田 泰能", last_name: "ひろた", first_name: "やすのり", style_id: 3},
  {full_name: "松野 恭憲", last_name: "まつの", first_name: "やすのり", style_id: 3},
  {full_name: "山田 安造", last_name: "やまだ", first_name: "やすぞう", style_id: 3},
  {full_name: "和田 次夫", last_name: "わだ", first_name: "つぐお", style_id: 3},
  {full_name: "有松 遼一", last_name: "ありまつ", first_name: "りょういち", style_id: 4},
  {full_name: "岡 充", last_name: "おか", first_name: "みつる", style_id: 4},
  {full_name: "久馬 治彦", last_name: "きゅうま", first_name: "はるひこ", style_id: 4},
  {full_name: "小林 努", last_name: "こばやし", first_name: "つとむ", style_id: 4},
  {full_name: "原 大", last_name: "はら", first_name: "まさる", style_id: 4},
  {full_name: "村山 弘", last_name: "むらやま", first_name: "ひろし", style_id: 4},
  {full_name: "左鴻 泰弘", last_name: "さこう", first_name: "やすひろ", style_id: 5},
  {full_name: "杉 市和", last_name: "すぎ", first_name: "いちかず", style_id: 5},
  {full_name: "杉 信太朗", last_name: "すぎ", first_name: "しんたろう", style_id: 5},
  {full_name: "光田 洋一", last_name: "みつだ", first_name: "よういち", style_id: 5},
  {full_name: "森田 保美", last_name: "もりた", first_name: "やすよし", style_id: 5},
  {full_name: "森田 光廣", last_name: "もりた", first_name: "みつひろ", style_id: 5},
  {full_name: "伊吹 吉博", last_name: "いぶき", first_name: "よしひろ", style_id: 6},
  {full_name: "菅 啓好", last_name: "すが", first_name: "ひろよし", style_id: 6},
  {full_name: "曽和 鼓堂", last_name: "そわ", first_name: "こどう", style_id: 6},
  {full_name: "竹村 英雄", last_name: "たけむら", first_name: "ひでお", style_id: 6},
  {full_name: "竹村 英敏", last_name: "たけむら", first_name: "ひでとし", style_id: 6},
  {full_name: "丹下 紀香", last_name: "たんげ", first_name: "のりか", style_id: 6},
  {full_name: "林 吉兵衛", last_name: "はやし", first_name: "きちべ", style_id: 6},
  {full_name: "林 大和", last_name: "はやし", first_name: "やまと", style_id: 6},
  {full_name: "林 大輝", last_name: "はやし", first_name: "ひろき", style_id: 6},
  {full_name: "吉阪 一郎", last_name: "きちさか", first_name: "いちろう", style_id: 7},
  {full_name: "石井 保彦", last_name: "いしい", first_name: "やすひこ", style_id: 8},
  {full_name: "井林 清一", last_name: "いばやし", first_name: "せいいち", style_id: 8},
  {full_name: "井林 久登", last_name: "いばやし", first_name: "ひさと", style_id: 8},
  {full_name: "河村 大", last_name: "かわむら", first_name: "まさる", style_id: 8},
  {full_name: "武重 正律", last_name: "たけしげ", first_name: "まさのり", style_id: 8},
  {full_name: "谷口 正壽", last_name: "たにぐち", first_name: "まさとし", style_id: 8},
  {full_name: "渡部 諭", last_name: "わたなべ", first_name: "さとる", style_id: 8},
  {full_name: "井上 敬介", last_name: "いのうえ", first_name: "けいすけ", style_id: 9},
  {full_name: "前川 光長", last_name: "まえかわ", first_name: "みつなが", style_id: 10},
  {full_name: "前川 光範", last_name: "まえかわ", first_name: "みつのり", style_id: 10},
  {full_name: "前川 雪", last_name: "まえかわ", first_name: "すぐる", style_id: 10},
  {full_name: "網谷 正美", last_name: "あみたに", first_name: "まさよし", style_id: 11},
  {full_name: "安東 伸元", last_name: "あんどう", first_name: "のぶちか", style_id: 11},
  {full_name: "井口 竜也", last_name: "いぐち", first_name: "たつや", style_id: 11},
  {full_name: "木村 正雄", last_name: "きむら", first_name: "まさお", style_id: 11},
  {full_name: "茂山 千作", last_name: "しげやま", first_name: "せんさく", style_id: 11},
  {full_name: "茂山 千五郎", last_name: "しげやま", first_name: "せんごろう", style_id: 11},
  {full_name: "茂山 茂", last_name: "しげやま", first_name: "しげる", style_id: 11},
  {full_name: "茂山 七五三", last_name: "しげやま", first_name: "しめ", style_id: 11},
  {full_name: "茂山 宗彦", last_name: "しげやま", first_name: "もとひこ", style_id: 11},
  {full_name: "茂山 逸平", last_name: "しげやま", first_name: "いっぺい", style_id: 11},
  {full_name: "茂山 千三郎", last_name: "しげやま", first_name: "せんざぶろう", style_id: 11},
  {full_name: "茂山 あきら", last_name: "しげやま", first_name: "あきら", style_id: 11},
  {full_name: "茂山 良暢", last_name: "しげやま", first_name: "よしのぶ", style_id: 11},
  {full_name: "島田 洋海", last_name: "しまだ", first_name: "ひろみ", style_id: 11},
  {full_name: "鈴木 実", last_name: "すずき", first_name: "みのる", style_id: 11},
  {full_name: "田賀屋 夙", last_name: "たがや", first_name: "なぎさ", style_id: 11},
  {full_name: "古川 道郎", last_name: "ふるかわ", first_name: "みちろう", style_id: 11},
  {full_name: "増田 浩紀", last_name: "ました", first_name: "こうき", style_id: 11},
  {full_name: "松本 薫", last_name: "まつもと", first_name: "かおる", style_id: 11},
  {full_name: "丸石 やすし", last_name: "まるいし", first_name: "やすし", style_id: 11},
  {full_name: "山口 耕道", last_name: "やまぐち", first_name: "こうどう", style_id: 11},
  {full_name: "山下 守之", last_name: "やました", first_name: "もりゆき", style_id: 11}
])

Place.create!([
  {title: "秋篠寺", address: "奈良県奈良市秋篠町７５７", official_url: "http://yamatoji.nara-kankou.or.jp/01shaji/02tera/01north_area/akishinodera/"},
  {title: "飛鳥寺", address: "奈良県高市郡明日香村大字飛鳥682", official_url: "http://www.asuka-tobira.com/asukakyo/asukadera.htm"},
  {title: "穴太寺", address: "京都府亀岡市曽我部町穴太東ノ辻４６", official_url: "http://saikoku33.gr.jp/21/"},
  {title: "安倍文殊院", address: "奈良県桜井市安倍山", official_url: "http://www.abemonjuin.or.jp/"},
  {title: "安国寺", address: "岐阜県高山市国府町西門前４７４", official_url: nil},
  {title: "安楽寺(長野県)", address: "長野県上田市別所温泉２３６１", official_url: "http://www.anrakuji.com/"},
  {title: "安楽寺(徳島県)", address: "徳島県板野郡上板町引野字寺ノ西北８", official_url: "http://www.shikoku6.or.jp/"},
  {title: "安楽寺(高知県)", address: "高知県高知市洞ケ島町５ 安楽寺", official_url: nil},
  {title: "池上本門寺", address: "東京都大田区池上１丁目３２−１２", official_url: "http://honmonji.jp/"},
  {title: "石手寺", address: "愛媛県松山市石手２丁目2−9−21", official_url: "http://www.nehan.net/"},
  {title: "石山寺", address: "滋賀県大津市石山寺", official_url: nil},
  {title: "一乗寺", address: "兵庫県加西市坂本町８２１−１７", official_url: "http://saikoku33.gr.jp/26/"},
  {title: "一畑寺", address: "島根県出雲市小境町８０３", official_url: "http://ichibata.jp/"},
  {title: "弥谷寺", address: "香川県三豊市三野町大見乙７０", official_url: "http://www.geocities.jp/ryogot1010/"},
  {title: "伊予国分寺", address: "愛媛県今治市国分４丁目１−３３", official_url: "http://www.88shikokuhenro.jp/ehime/59kokubunji/"},
  {title: "永源寺", address: "滋賀県東近江市永源寺高野町41", official_url: "http://eigenji-t.jp/"},
  {title: "栄山寺", address: "奈良県五條市小島町５０３", official_url: nil},
  {title: "叡福寺", address: "大阪府南河内郡太子町太子 太子町太子２１４６", official_url: "http://www.shin-saigoku.jp/temple/11_eifukuji_01.html"},
  {title: "永平寺", address: "福井県吉田郡永平寺町", official_url: nil},
  {title: "永保寺", address: "岐阜県多治見市虎渓山町１丁目 虎渓山町1丁目40", official_url: "http://www.kokei.or.jp/"},
  {title: "回向院", address: "東京都墨田区両国２丁目８ 東京都墨田区両国２丁目８−１０", official_url: "http://www.ekoin.or.jp/"},
  {title: "恵日寺", address: "福島県耶麻郡磐梯町磐梯本寺上４９５０", official_url: nil},
  {title: "恵林寺", address: "山梨県甲州市塩山小屋敷２２８０", official_url: "http://www.erinji.jp/"},
  {title: "円覚寺", address: "神奈川県鎌倉市山ノ内409", official_url: "http://www.engakuji.or.jp/"},
  {title: "圓教寺", address: "兵庫県姫路市書写２９６８", official_url: "http://www.shosha.or.jp/"},
  {title: "円成寺", address: "奈良県奈良市忍辱山町1273", official_url: "http://www.enjyouji.jp/"},
  {title: "円通寺", address: "京都府京都市左京区岩倉幡枝町 岩倉幡枝町３８９", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000020"},
  {title: "延暦寺", address: "滋賀県大津市坂本本町４２２０", official_url: "http://www.hieizan.or.jp/"},
  {title: "大須観音", address: "愛知県名古屋市中区大須２丁目２１−４７", official_url: "http://www.osu-kannon.jp/"},
  {title: "大峯山寺", address: "奈良県吉野郡天川村洞川７０３", official_url: nil},
  {title: "大谷寺", address: "栃木県宇都宮市大谷町１１９８", official_url: "http://www.ooyaji.jp/"},
  {title: "大山寺(神奈川県)", address: "神奈川県伊勢原市大山７２４", official_url: "http://www.oyamadera.jp/"},
  {title: "岡寺", address: "奈良県高市郡明日香村岡８０６", official_url: "http://www.okadera3307.com/"},
  {title: "愛宕念仏寺", address: "京都府京都市右京区嵯峨鳥居本深谷町２−５", official_url: "http://www.otagiji.com/"},
  {title: "帯解寺", address: "奈良県奈良市今市町７３４", official_url: "http://www.obitokedera.or.jp/"},
  {title: "園城寺", address: "滋賀県大津市園城寺町", official_url: nil},
  {title: "温泉寺", address: "兵庫県豊岡市城崎町湯島 兵庫県豊岡市城崎町湯島", official_url: "http://www.kinosaki-onsenji.jp/"},
  {title: "海住山寺", address: "京都府木津川市加茂町例幣海住山境外２０", official_url: "http://www.kaijyusenji.jp/"},
  {title: "海龍王寺", address: "奈良県奈良市法華寺町８９７", official_url: "http://www.kairyuouji.jp/"},
  {title: "花岳寺", address: "兵庫県赤穂市加里屋１９９２", official_url: "https://kagakuji.jimdo.com/"},
  {title: "覚園寺", address: "神奈川県鎌倉市二階堂４２１", official_url: "http://kamakura894do.com/"},
  {title: "鰐淵寺", address: "島根県出雲市別所町１４８", official_url: nil},
  {title: "鶴林寺", address: "兵庫県加古川市加古川町北在家４２４", official_url: "http://www.kakurinji.or.jp/"},
  {title: "勝尾寺", address: "大阪府箕面市粟生間谷２９１４−１", official_url: "http://www.katsuo-ji-temple.or.jp/"},
  {title: "勧修寺", address: "京都府京都市山科区勧修寺仁王堂町２７−６", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000031"},
  {title: "蟹満寺", address: "京都府木津川市山城町綺田浜 京都府木津川市山城町綺田浜３６", official_url: nil},
  {title: "神峯山寺", address: "大阪府高槻市原 大阪府高槻市大字原3301−1", official_url: "http://kabusan.or.jp/"},
  {title: "伽耶院", address: "兵庫県三木市志染町大谷４１０", official_url: "http://www.gayain.or.jp/"},
  {title: "川原寺", address: "奈良県高市郡明日香村大字川原1109", official_url: "http://asukamura.com/?page_id=316"},
  {title: "寛永寺", address: "東京都台東区上野桜木１丁目１４−１１", official_url: "http://www.kaneiji.jp/"},
  {title: "歓喜院", address: "埼玉県熊谷市妻沼1627", official_url: "http://www.city.kumagaya.lg.jp/kanko/midokoro/menumasyoudenzan/"},
  {title: "元興寺", address: "奈良県奈良市中院町１１番地", official_url: "http://www.gangoji.or.jp/tera/jap/link/link.html"},
  {title: "願成就院", address: "静岡県伊豆の国市寺家８３", official_url: "http://ganjoujuin.jp/"},
  {title: "観心寺", address: "大阪府河内長野市寺元475", official_url: "http://www.kanshinji.com/"},
  {title: "観世音寺", address: "福岡県太宰府市観世音寺５丁目６−１", official_url: "http://www.dazaifu.org/map/tanbo/tourismmap/4.html"},
  {title: "岩船寺", address: "京都府木津川市加茂町岩船上ノ門４３", official_url: "http://0774.or.jp/temple/gansenji.html"},
  {title: "願徳寺", address: "京都府京都市西京区大原野南春日町", official_url: "http://www.gantoku.or.jp/"},
  {title: "神呪寺", address: "兵庫県西宮市甲山町２５−１", official_url: "http://www.ne.jp/asahi/kabutoyama/kanno-ji/"},
  {title: "観音寺", address: "京都府福知山市観音寺", official_url: nil},
  {title: "観音正寺", address: "滋賀県近江八幡市安土町石寺２", official_url: "http://www.kannon.or.jp/"},
  {title: "喜光寺", address: "奈良県奈良市菅原町５０８", official_url: "http://www.kikouji.com/"},
  {title: "喜多院", address: "埼玉県川越市小仙波町１丁目２０−１", official_url: "http://www.kawagoe.com/kitain/"},
  {title: "吉田寺", address: "奈良県生駒郡斑鳩町小吉田１丁目１−２３", official_url: "http://www.kichidenji.com/"},
  {title: "木之本地蔵院", address: "滋賀県長浜市木之本町木之本944番地", official_url: "http://www.kinomoto-jizo.com/"},
  {title: "紀三井寺", address: "和歌山県和歌山市紀三井寺", official_url: nil},
  {title: "教王護国寺(京都府)", address: "京都府京都市南区九条町１", official_url: "http://www.toji.or.jp/"},
  {title: "行願寺", address: "京都府京都市中京区行願寺門前町 寺町通竹屋町上る行願寺門前町17", official_url: nil},
  {title: "清荒神清澄寺", address: "兵庫県宝塚市米谷清シ−１", official_url: "http://www.kiyoshikojin.or.jp/"},
  {title: "清水寺(京都府)", address: "京都府京都市東山区清水１丁目２９４", official_url: "http://www.kiyomizudera.or.jp/"},
  {title: "清水寺(兵庫県)", address: "兵庫県加東市平木１１９４", official_url: "http://kiyomizudera.net/"},
  {title: "清水寺(岩手県)", address: "岩手県花巻市太田第21地割第２１地割５−１", official_url: "http://kiyomizudera.org/"},
  {title: "清水寺(島根県)", address: "島根県安来市清水町５２８番地", official_url: "http://www.kiyomizudera.jp/"},
  {title: "金峯山寺", address: "奈良県吉野郡吉野町吉野山２４９８", official_url: "http://www.kinpusen.or.jp/"},
  {title: "久遠寺", address: "山梨県南巨摩郡身延町身延3567", official_url: "http://www.kuonji.jp/"},
  {title: "百済寺(奈良県)", address: "奈良県北葛城郡広陵町百済１１６８", official_url: "http://www.library.pref.nara.jp/nara_2010/0267.html"},
  {title: "鞍馬寺", address: "京都府京都市左京区鞍馬本町1074番地", official_url: "http://www.kuramadera.or.jp/"},
  {title: "桂春院", address: "京都府京都市右京区花園寺ノ中町１１", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000052"},
  {title: "華厳寺", address: "岐阜県揖斐郡揖斐川町谷汲徳積２３", official_url: "http://www.kegonji.or.jp/"},
  {title: "月照寺", address: "島根県松江市外中原町１７９", official_url: "http://www.shinbutsu.jp/36.html"},
  {title: "建長寺", address: "神奈川県鎌倉市山ノ内8", official_url: "http://kenchoji.com/"},
  {title: "建仁寺", address: "京都府京都市東山区小松町 大和大路通四条下る小松町584", official_url: "http://www.kenninji.jp/"},
  {title: "孝恩寺", address: "大阪府貝塚市木積 大阪府貝塚市木積７９８", official_url: "http://www.netfam.jp/kohonji/"},
  {title: "向嶽寺", address: "山梨県甲州市塩山上於曽２０２６", official_url: "http://www.rinnou.net/cont_03/13kogaku/"},
  {title: "向源寺", address: "滋賀県長浜市高月町渡岸寺８８", official_url: nil},
  {title: "高山寺", address: "京都府京都市右京区梅ケ畑栂尾町8", official_url: "http://www.kosanji.com/"},
  {title: "興山寺", address: "和歌山県紀の川市桃山町最上５６１", official_url: "https://ja.wikipedia.org/wiki/%E8%88%88%E5%B1%B1%E5%AF%BA"},
  {title: "功山寺", address: "山口県下関市長府川端１丁目１−２−３", official_url: "http://www.npweb.com/kouzanji/"},
  {title: "興正寺", address: "京都府京都市下京区花園町 堀川通七条上る花園町70", official_url: "http://www.koshoji.or.jp/"},
  {title: "興禅寺", address: "兵庫県丹波市春日町黒井２２６３", official_url: nil},
  {title: "光前寺", address: "長野県駒ヶ根市赤穂２９", official_url: "http://www.kozenji.or.jp/"},
  {title: "高台寺", address: "京都府京都市東山区下河原町526番地３９", official_url: "http://www.kodaiji.com/"},
  {title: "高桐院", address: "京都府京都市北区紫野大徳寺町73−1", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000062"},
  {title: "高徳院", address: "神奈川県鎌倉市長谷４丁目２−２８", official_url: "http://www.kotoku-in.jp/"},
  {title: "興福寺", address: "奈良県奈良市登大路町４８", official_url: "http://www.kohfukuji.com/"},
  {title: "光明寺(京都府)", address: "京都府長岡京市粟生西条ノ内26−1", official_url: "http://www.komyo-ji.or.jp/"},
  {title: "光明寺(兵庫県)", address: "兵庫県加東市光明寺", official_url: nil},
  {title: "光明寺(神奈川県)", address: "神奈川県鎌倉市材木座６丁目１７−１９ 光明寺", official_url: nil},
  {title: "光明寺(京都府)", address: "京都府長岡京市粟生西条ノ内26−1", official_url: "http://www.komyo-ji.or.jp/"},
  {title: "広隆寺", address: "京都府京都市右京区太秦蜂岡町32", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000064"},
  {title: "粉河寺", address: "和歌山県紀の川市粉河 粉河2787", official_url: "http://www.kokawadera.org/"},
  {title: "護国寺(東京都)", address: "東京都文京区大塚５丁目４０−１", official_url: "http://www.gokokuji.or.jp/"},
  {title: "孤篷庵", address: "京都府京都市北区紫野大徳寺町", official_url: nil},
  {title: "金戒光明寺", address: "京都府京都市左京区黒谷町１２１", official_url: "http://www.kurodani.jp/"},
  {title: "金地院", address: "京都府京都市左京区南禅寺福地町86−１２", official_url: nil},
  {title: "金剛三昧院", address: "和歌山県伊都郡高野町大字高野山425", official_url: "http://www.kongosanmaiin.or.jp/"},
  {title: "金剛寺", address: "大阪府河内長野市天野町996", official_url: "http://amanosan-kongoji.jp/"},
  {title: "金剛證寺", address: "三重県伊勢市朝熊町５４８", official_url: "http://www.iseshimaskyline.com/kongoushouji.htm"},
  {title: "金剛峯寺", address: "和歌山県伊都郡高野町高野山１３２", official_url: "http://www.koyasan.or.jp/"},
  {title: "金剛輪寺", address: "滋賀県愛知郡愛荘町松尾寺８７４", official_url: "http://kongourinji.jp/"},
  {title: "金林寺", address: "高知県安芸郡馬路村馬路 高知県安芸郡馬路村大字馬路4281日浦", official_url: nil},
  {title: "金蓮寺", address: "愛知県西尾市吉良町饗庭七度ケ入 愛知県西尾市吉良町饗庭七度ケ入1", official_url: nil},
  {title: "西岸寺", address: "京都府京都市伏見区深草直違橋２丁目４３８−１", official_url: "http://www.saiganji.or.jp/"},
  {title: "西教寺", address: "滋賀県大津市坂本５丁目１３−１３番地１", official_url: "http://saikyoji.org/"},
  {title: "最上稲荷", address: "岡山県岡山市北区高松稲荷７１２", official_url: "http://www.inari.ne.jp/"},
  {title: "西大寺", address: "奈良県奈良市西大寺町", official_url: nil},
  {title: "西福寺", address: "福井県敦賀市原１３−７", official_url: "http://www.saifukuji.jp/"},
  {title: "西芳寺", address: "京都府京都市西京区松尾神ケ谷町５６", official_url: "http://www.pref.kyoto.jp/isan/saihouji.html"},
  {title: "西明寺", address: "滋賀県犬山郡甲良町池寺２６", official_url: "http://www.saimyouji.com/"},
  {title: "三十三間堂", address: "京都府京都市東山区三十三間堂廻リ６５７", official_url: "http://www.sanjusangendo.jp/"},
  {title: "三千院", address: "京都府京都市左京区大原来迎院町５４０", official_url: "http://www.sanzenin.or.jp/"},
  {title: "三仏寺", address: "鳥取県東伯郡三朝町三徳１０１０", official_url: "http://www.mitokusan.jp/"},
  {title: "三宝院", address: "京都府京都市伏見区醍醐東大路町 三宝院", official_url: nil},
  {title: "慈恩寺", address: "山形県寒河江市慈恩寺", official_url: nil},
  {title: "慈光院", address: "奈良県大和郡山市小泉町８６５", official_url: "http://www1.kcn.ne.jp/~jikoin/"},
  {title: "慈眼院", address: "大阪府泉佐野市日根野６２６", official_url: "http://www.jigenin.or.jp/"},
  {title: "実相院", address: "京都府京都市左京区岩倉上蔵町121", official_url: "http://www.jissoin.com/"},
  {title: "柴又帝釈天", address: "東京都葛飾区柴又７丁目７−１０−３", official_url: "http://www.taishakuten.or.jp/index.html"},
  {title: "寂光院", address: "京都府京都市左京区大原草生町６７６", official_url: "http://www.jakkoin.jp/"},
  {title: "酬恩庵", address: "京都府京田辺市薪里ノ内 京都府京田辺市薪里ノ内102", official_url: "http://www.ikkyuji.org/"},
  {title: "十輪院", address: "奈良県奈良市十輪院町", official_url: nil},
  {title: "修禅寺", address: "静岡県伊豆市修善寺", official_url: nil},
  {title: "鷲山寺", address: "千葉県茂原市鷲巣４８", official_url: "http://www.hokkeshu.or.jp/honzan/jusenji.html"},
  {title: "寿福寺", address: "神奈川県鎌倉市扇ガ谷１丁目１７−７", official_url: "http://www.kamakura-burabura.com/meisyokamakurajyufukuji.htm"},
  {title: "聖護院", address: "京都府京都市左京区聖護院中町１５", official_url: "http://www.shogoin.or.jp/"},
  {title: "相国寺", address: "京都府京都市上京区相国寺門前町 今出川通烏丸東入", official_url: "http://www.shokoku-ji.jp/"},
  {title: "聖衆来迎寺", address: "滋賀県大津市比叡辻２丁目４ 聖衆来迎寺", official_url: nil},
  {title: "清浄華院", address: "京都府京都市上京区北之辺町 京都府京都市上京区寺町通広小路上る北之辺町395", official_url: "http://www.jozan.jp/"},
  {title: "清浄光寺", address: "神奈川県藤沢市西富１丁目８−１", official_url: "http://www.jishu.or.jp/"},
  {title: "勝常寺", address: "福島県河沼郡湯川村勝常代舞１７６４", official_url: "http://www.vill.yugawa.fukushima.jp/kyouikuiinkai/historic.html"},
  {title: "浄智寺", address: "神奈川県鎌倉市山ノ内1402", official_url: "https://www.city.kamakura.kanagawa.jp/kamakura-kankou/meisho/03joutiji.html"},
  {title: "浄土寺", address: "兵庫県小野市浄谷町2094", official_url: "http://www.city.ono.hyogo.jp/p/2/7/4/"},
  {title: "正福寺", address: "東京都東村山市野口町４丁目６ 野口町４丁目６−１", official_url: "https://www.city.higashimurayama.tokyo.jp/tanoshimi/rekishi/furusato/bunkazai/fukikae.html"},
  {title: "正法寺", address: "岩手県奥州市水沢区黒石町正法寺", official_url: nil},
  {title: "上品蓮台寺", address: "京都府京都市北区紫野十二坊町３３−１", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000119"},
  {title: "常楽寺", address: "滋賀県湖南市西寺６丁目５−１", official_url: "http://www.eonet.ne.jp/~jo-rakuji/"},
  {title: "聖林寺", address: "奈良県桜井市下６９２", official_url: "http://www.shorinji-temple.jp/"},
  {title: "青蓮院", address: "京都府京都市東山区粟田口三条坊町６９−１", official_url: "http://www.shorenin.com/"},
  {title: "青蓮寺", address: "神奈川県鎌倉市手広５丁目１−８", official_url: "http://kusaridaishi.jp/"},
  {title: "浄瑠璃寺(京都府)", address: "京都府木津川市加茂町西小札場札場40", official_url: "http://0774.or.jp/temple/jyoruriji.html"},
  {title: "丈六寺", address: "徳島県徳島市丈六町丈領 丈六町丈領32", official_url: nil},
  {title: "白水阿弥陀堂", address: "福島県いわき市内郷白水町広畑２１９", official_url: "http://shiramizu-amidado.org/"},
  {title: "神護寺", address: "京都府京都市右京区梅ケ畑高雄町５", official_url: "http://www.jingoji.or.jp/"},
  {title: "真正極楽寺", address: "京都府京都市左京区浄土寺真如町８２", official_url: "http://shin-nyo-do.jp/"},
  {title: "深大寺", address: "東京都三鷹市深大寺", official_url: nil},
  {title: "新薬師寺(奈良県)", address: "奈良県奈良市高畑町 高畑町１３５２", official_url: "http://www.shinyakushiji.or.jp/"},
  {title: "瑞巌寺", address: "宮城県宮城郡松島町松島字町内９１", official_url: "http://www.zuiganji.or.jp/"},
  {title: "随願寺", address: "兵庫県姫路市白国５", official_url: nil},
  {title: "随心院", address: "京都府京都市山科区小野御霊町３５", official_url: "http://www.zuishinin.or.jp/"},
  {title: "瑞泉寺", address: "神奈川県鎌倉市二階堂７１０", official_url: "http://www.kamakura-zuisenji.or.jp/"},
  {title: "瑞峯院", address: "京都府京都市北区紫野大徳寺町 北区紫野大徳寺町81", official_url: nil},
  {title: "瑞龍寺", address: "富山県高岡市関本町３５", official_url: "http://www.zuiryuji.jp/"},
  {title: "須磨寺", address: "兵庫県神戸市須磨区須磨寺町", official_url: nil},
  {title: "清巌寺", address: "栃木県宇都宮市大通り５丁目３−１４", official_url: nil},
  {title: "清龍寺", address: "新潟県十日町市霜条５９０", official_url: nil},
  {title: "青岸渡寺", address: "和歌山県東牟婁郡那智勝浦町大字那智山８", official_url: "http://www.nachikan.jp/kumano/seigantoji/"},
  {title: "清白寺", address: "山梨県山梨市三ヶ所６２０", official_url: nil},
  {title: "清凉寺", address: "京都府京都市右京区嵯峨釈迦堂藤ノ木町４６", official_url: "http://seiryoji.or.jp/"},
  {title: "施福寺", address: "大阪府和泉市槇尾山町136", official_url: "http://saikoku33.gr.jp/place/4"},
  {title: "泉岳寺", address: "東京都港区高輪２丁目２０", official_url: nil},
  {title: "千光寺", address: "奈良県生駒郡平群町鳴川１８８", official_url: "http://motosanjyo-senkouji.com/"},
  {title: "善光寺", address: "長野県長野市長野元善町４９１", official_url: "http://www.zenkoji.jp/"},
  {title: "千手院", address: "島根県松江市石橋町３８５", official_url: "http://www.senjyuin.com/"},
  {title: "専修寺", address: "栃木県真岡市高田１４８２", official_url: "http://www.senjuji.or.jp/about/honji.php"},
  {title: "善水寺", address: "滋賀県湖南市岩根３５１８", official_url: "http://www.zensuiji.jp/"},
  {title: "浅草寺", address: "東京都台東区浅草２丁目３−１", official_url: "http://www.senso-ji.jp/"},
  {title: "善通寺", address: "香川県善通寺市", official_url: nil},
  {title: "善導寺", address: "福岡県久留米市善導寺町飯田５５０", official_url: "http://www.zendoji.jp/"},
  {title: "泉涌寺", address: "京都府京都市東山区泉涌寺山内町２７", official_url: "http://www.mitera.org/"},
  {title: "善福院", address: "和歌山県海南市下津町梅田２７１", official_url: nil},
  {title: "禅瀧寺", address: "兵庫県加東市栄枝", official_url: nil},
  {title: "禅林寺", address: "京都府京都市左京区永観堂町48", official_url: "http://www.eikando.or.jp/"},
  {title: "總持寺", address: "東京都足立区西新井１丁目１５−１", official_url: "http://www.nishiaraidaishi.or.jp/"},
  {title: "総持寺(大阪府)", address: "大阪府茨木市総持寺", official_url: nil},
  {title: "総持寺(和歌山県)", address: "和歌山県和歌山市梶取８６", official_url: nil},
  {title: "惣宗寺", address: "栃木県佐野市金井上町２２３３", official_url: "http://www.sanoyakuyokedaishi.or.jp/"},
  {title: "増上寺", address: "東京都港区芝公園４丁目4−7−35", official_url: "http://www.zojoji.or.jp/map/index.html"},
  {title: "崇福寺", address: "長崎県長崎市鍛冶屋町７−５", official_url: nil},
  {title: "大安寺", address: "奈良県奈良市大安寺", official_url: nil},
  {title: "大雲寺", address: "京都府亀岡市旭町父畑５２", official_url: nil},
  {title: "大雄寺", address: "栃木県大田原市黒羽田町４５０", official_url: "http://www.daiouji.or.jp/"},
  {title: "大覚寺", address: "京都府京都市右京区嵯峨大沢町４", official_url: "http://www.daikakuji.or.jp/"},
  {title: "泰岳寺", address: "愛知県春日井市上条町１０丁目１９８", official_url: "http://www.taigakuji.net/"},
  {title: "退耕庵", address: "京都府京都市東山区本町１５丁目７９３", official_url: nil},
  {title: "醍醐寺", address: "京都府京都市伏見区醍醐東大路町２２", official_url: "http://www.daigoji.or.jp/"},
  {title: "大國寺", address: "兵庫県篠山市味間奥１６１", official_url: "http://sasayama-daikokuji.com/"},
  {title: "大慈寺", address: "栃木県栃木市岩舟町小野寺 岩舟町小野寺２２４７", official_url: "http://www.cc9.ne.jp/~daijiji/"},
  {title: "大樹寺", address: "愛知県岡崎市鴨田町広元５−１", official_url: "http://home1.catvmics.ne.jp/~daijuji/"},
  {title: "大照院", address: "山口県萩市椿（大字） 山口県萩市大字椿青海4132", official_url: "http://www.hagibukkyo.org/bhp-daisyoin/j-daisyoin.htm"},
  {title: "大聖寺", address: "岡山県美作市大聖寺１", official_url: "http://daisyouji.or.jp/"},
  {title: "大乗寺", address: "石川県金沢市長坂町ル 石川県金沢市長坂町ル−10", official_url: "http://www.daijoji.or.jp/"},
  {title: "大聖勝軍寺", address: "大阪府八尾市太子堂３丁目３−１６", official_url: "http://kazu1000.muragon.com/entry/320.html"},
  {title: "大石寺", address: "静岡県富士宮市上条２０５７", official_url: "http://www.nichirenshoshu.or.jp/page/taisekiji/jpn/taisekiji_j.html"},
  {title: "大仙院", address: "京都府京都市北区紫野大徳寺町５４−１", official_url: "http://www.b-model.net/daisen-in/"},
  {title: "大山寺(鳥取県)", address: "鳥取県西伯郡大山町大山９", official_url: "http://daisenji.jp/"},
  {title: "大泉寺（犬山市）", address: "愛知県犬山市栗栖寺前 栗栖768", official_url: "http://daisenji.web.fc2.com/index.html"},
  {title: "大善寺", address: "山梨県甲州市勝沼町勝沼３５５９", official_url: "http://www.katsunuma.ne.jp/~daizenji/"},
  {title: "退蔵院", address: "京都府京都市右京区花園妙心寺町３５", official_url: "http://www.taizoin.com/main.html"},
  {title: "大中寺", address: "栃木県栃木市大平町西山田２５２", official_url: "http://www.kuranomachi.jp/spot/ohirasan/daichuji/"},
  {title: "大通寺", address: "滋賀県長浜市元浜町３２−９", official_url: "http://www.daitsuji.or.jp/"},
  {title: "大徳寺", address: "京都府京都市北区紫野大徳寺町５３", official_url: "http://www.rinnou.net/cont_03/07daitoku/"},
  {title: "大日坊", address: "山形県鶴岡市大網入道１１", official_url: "http://dainichibou.or.jp/"},
  {title: "大福田寺", address: "三重県桑名市東方１４２６", official_url: nil},
  {title: "大平寺", address: "愛知県豊橋市老津町東高縄２０４", official_url: nil},
  {title: "大蓮寺", address: "石川県金沢市野町２丁目１−１４", official_url: "http://dairenji.net/"},
  {title: "泰平寺", address: "鹿児島県薩摩川内市大小路町４８ 鹿児島県薩摩川内市大小路町４８－３７", official_url: nil},
  {title: "大報恩寺", address: "京都府京都市上京区溝前町 七本松通今出川上ル溝前町1034番地", official_url: "http://www.daihoonji.com/"},
  {title: "大法寺", address: "長野県小県郡青木村当郷２０５２", official_url: "https://www.daihoujitemple.com/"},
  {title: "當麻寺", address: "奈良県葛城市當麻１２６３", official_url: "http://www.taimadera.org/"},
  {title: "高尾山薬王院", address: "東京都八王子市高尾町２１７７", official_url: "http://www.takaosan.or.jp/"},
  {title: "大龍寺", address: "福島県会津若松市慶山２丁目７", official_url: nil},
  {title: "滝山寺", address: "愛知県岡崎市滝町山籠 愛知県岡崎市滝町山籠１０７", official_url: "http://takisanji.net/oni.html"},
  {title: "橘寺", address: "奈良県高市郡明日香村橘５３２", official_url: "http://www.bell.jp/pancho/asuka-sansaku/tatibana-dera.htm"},
  {title: "達磨寺", address: "奈良県北葛城郡王寺町本町２丁目１−４０", official_url: "http://www.darumaji.jp/"},
  {title: "誕生寺", address: "千葉県鴨川市小湊１８３", official_url: "http://www.tanjoh-ji.jp/"},
  {title: "知恩院", address: "京都府京都市東山区林下町４００", official_url: "http://www.chion-in.or.jp/index.php"},
  {title: "知恩寺", address: "京都府京都市左京区田中門前町103", official_url: "http://hyakusan.jp/"},
  {title: "智恩寺", address: "京都府宮津市文珠４６６", official_url: "http://www.monjudo-chionji.jp/"},
  {title: "竹林寺", address: "高知県高知市五台山 五台山３５７７", official_url: "http://www.chikurinji.com/"},
  {title: "智積院", address: "京都府京都市東山区東瓦町 東大路通り七条下る東瓦町964番地", official_url: "http://www.chisan.or.jp/"},
  {title: "中宮寺", address: "奈良県生駒郡斑鳩町法隆寺北１丁目１ 奈良県生駒郡斑鳩町法隆寺北１丁目１−２", official_url: "http://www.chuguji.jp/"},
  {title: "中禅寺", address: "栃木県日光市中宮祠 中宮祠２５７８", official_url: "http://www.bandou.gr.jp/"},
  {title: "中尊寺", address: "岩手県西磐井郡平泉町平泉衣関２０２", official_url: "http://www.chusonji.or.jp/"},
  {title: "長岳寺", address: "奈良県天理市柳本町５０８", official_url: "http://www.chogakuji.or.jp/"},
  {title: "長弓寺", address: "奈良県生駒市上町４４４５ 長弓寺", official_url: nil},
  {title: "長久寺", address: "滋賀県米原市長久寺", official_url: nil},
  {title: "長慶寺", address: "大阪府泉南市信達市場815", official_url: "http://welcome-sennan.com/tourist-spots/chokeiji"},
  {title: "朝光寺", address: "兵庫県加東市畑６０９", official_url: "http://www.kita-harima.jp/modules/xdirectory/singlelink.php?lid=171"},
  {title: "朝護孫子寺", address: "奈良県生駒郡平群町信貴山２２８０−１", official_url: "http://www.sigisan.or.jp/"},
  {title: "長寿寺", address: "滋賀県湖南市東寺５丁目１ 滋賀県湖南市東寺５丁目２−２７", official_url: nil},
  {title: "長勝寺", address: "茨城県潮来市潮来４２８", official_url: nil},
  {title: "長保寺", address: "和歌山県海南市下津町上６８９", official_url: "http://www.chohoji.or.jp/"},
  {title: "頂法寺", address: "京都府京都市中京区六角通東洞院西入堂之前町", official_url: "http://www.ikenobo.jp/rokkakudo"},
  {title: "長命寺", address: "滋賀県近江八幡市長命寺町１５７", official_url: "http://www.saikoku33.gr.jp/place/31"},
  {title: "徹心寺", address: "兵庫県神崎郡神河町福本４０２", official_url: nil},
  {title: "天授庵", address: "京都府京都市左京区南禅寺福地町 京都府京都市左京区南禅寺福地町", official_url: "http://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000279"},
  {title: "伝通院", address: "東京都文京区小石川３丁目１４−６", official_url: "http://www.denzuin.or.jp/"},
  {title: "天龍寺", address: "京都府京都市右京区嵯峨天龍寺芒ノ馬場町 嵯峨天龍寺芒ノ馬場町68", official_url: "http://www.tenryuji.com/"},
  {title: "童学寺", address: "徳島県名西郡石井町石井城ノ内城ノ内６０５", official_url: "http://www001.upp.so-net.ne.jp/ss45988/bangai/b2/B2.htm"},
  {title: "東慶寺", address: "神奈川県鎌倉市山ノ内１３６７", official_url: "http://www.tokeiji.com/"},
  {title: "東光寺", address: "山口県萩市椿東１６４７", official_url: "http://www.toukouji.net/"},
  {title: "東寺", address: "京都府京都市南区九条町１", official_url: "http://www.toji.or.jp/"},
  {title: "等持院", address: "京都府京都市北区等持院北町６３", official_url: "http://toujiin.jp/"},
  {title: "道成寺", address: "和歌山県日高郡日高川町鐘巻１７３８", official_url: "http://www.dojoji.com/"},
  {title: "唐招提寺", address: "奈良県奈良市五条町１３−４６", official_url: "http://www.toshodaiji.jp/"},
  {title: "東大寺", address: "奈良県奈良市雑司町４０６−１", official_url: "http://www.todaiji.or.jp/"},
  {title: "東福寺", address: "京都府京都市東山区本町15−778", official_url: "http://www.tofukuji.jp/"},
  {title: "塔福寺", address: "熊本県宇城市小川町東海東４５", official_url: nil},
  {title: "道明寺", address: "大阪府藤井寺市道明寺", official_url: nil},
  {title: "土佐国分寺", address: "高知県南国市国分546", official_url: "http://www.tosakokubunji.org/"},
  {title: "豊川稲荷", address: "愛知県豊川市豊川町 豊川稲荷", official_url: nil},
  {title: "道樹寺", address: "岐阜県美濃市大矢田８７０−１", official_url: "http://www.t3create.com/minoshi-bukkyokai/doujuji/index.html"},
  {title: "中山寺", address: "兵庫県宝塚市中山寺", official_url: nil},
  {title: "那谷寺", address: "石川県小松市那谷町ユ−１２２", official_url: "http://www.natadera.com/"},
  {title: "成相寺", address: "京都府宮津市成相寺", official_url: nil},
  {title: "南宗寺", address: "大阪府堺市堺区南旅篭町東３丁１", official_url: nil},
  {title: "南禅院", address: "京都府京都市左京区南禅寺風呂山町８６", official_url: "http://www.nanzen.net/keidai_nanzenin.html#_=_"},
  {title: "南禅寺", address: "京都府京都市左京区南禅寺福地町", official_url: "http://www.nanzen.net/"},
  {title: "西本願寺(京都府)", address: "京都府京都市下京区門前町 本願寺門前町堀川通花屋町下る", official_url: "http://www.hongwanji.or.jp/"},
  {title: "西山興隆寺", address: "愛媛県西条市丹原町古田甲1657", official_url: "http://www.bekkaku.com/?page_id=33"},
  {title: "如意輪寺(奈良県)", address: "奈良県吉野郡吉野町吉野山１０２４", official_url: "http://www.nyoirinji.com/"},
  {title: "如意輪寺(千葉県)", address: "千葉県茂原市国府関６２４", official_url: nil},
  {title: "仁和寺", address: "京都府京都市右京区御室大内３３", official_url: "http://www.ninnaji.or.jp/"},
  {title: "根来寺", address: "和歌山県岩出市根来２２８６", official_url: "http://www.negoroji.org/"},
  {title: "梅林寺", address: "大阪府茨木市片桐町１ 大阪府茨木市片桐町１－３", official_url: nil},
  {title: "羽賀寺", address: "福井県小浜市羽賀８２−２", official_url: "http://www1.city.obama.fukui.jp/category/page.asp?Page=1223"},
  {title: "長谷観音", address: "茨城県古河市長谷町５−１", official_url: "http://www.hasekannon.org/"},
  {title: "長谷寺(奈良県)", address: "奈良県桜井市初瀬７３１−１", official_url: "http://www.hasedera.or.jp/"},
  {title: "長谷寺(神奈川県)", address: "神奈川県鎌倉市長谷３丁目１１−２", official_url: "http://www.hasedera.jp/"},
  {title: "法多山尊永寺", address: "静岡県袋井市豊沢2777", official_url: "http://www.hattasan.or.jp/"},
  {title: "斑鳩寺", address: "兵庫県揖保郡太子町鵤７０９", official_url: "http://www.ikarugadera.jp/"},
  {title: "鑁阿寺", address: "栃木県足利市家富町2220", official_url: "http://www.ashikaga-bannaji.org/"},
  {title: "般若寺", address: "奈良県奈良市般若寺町２２１", official_url: "http://www.hannyaji.com/"},
  {title: "東本願寺(京都府)", address: "京都府京都市下京区常葉町 烏丸通七条上る", official_url: "http://www.higashihonganji.or.jp/"},
  {title: "東本願寺(東京都)", address: "東京都台東区西浅草１丁目５−５", official_url: "http://www.honganji.or.jp/"},
  {title: "毘沙門堂", address: "京都府京都市山科区安朱稲荷山町１８", official_url: "http://www.bishamon.or.jp/"},
  {title: "日向薬師", address: "神奈川県伊勢原市日向１６４４", official_url: "http://hinatayakushi.com/"},
  {title: "百済寺(滋賀県)", address: "滋賀県東近江市百済寺町３２３", official_url: "http://www.hyakusaiji.jp/"},
  {title: "白毫寺", address: "奈良県奈良市白毫寺町３９２", official_url: "http://narashikanko.or.jp/spot/index.php?m=d&id=57"},
  {title: "平等院", address: "京都府宇治市宇治蓮華１１６", official_url: "http://www.byodoin.or.jp/"},
  {title: "富貴寺(大分県)", address: "大分県豊後高田市田染蕗２３９５", official_url: nil},
  {title: "富貴寺(奈良県)", address: "奈良県磯城郡川西町保田 奈良県磯城郡川西町保田３３", official_url: nil},
  {title: "福禅寺", address: "広島県福山市鞆町鞆２", official_url: "http://www.fukuyama-kanko.com/hyaka/spot059.html"},
  {title: "普光寺", address: "神奈川県横浜市泉区岡津町９４", official_url: "http://www.fukouji.jp/"},
  {title: "普済寺", address: "東京都立川市柴崎町４丁目２０−４６", official_url: "http://www.fusaiji.or.jp/"},
  {title: "葛井寺", address: "大阪府藤井寺市藤井寺１丁目１６−２１", official_url: "http://www.fujiidera-temple.or.jp/"},
  {title: "不退寺", address: "奈良県奈良市法蓮町５１７", official_url: "http://www3.kcn.ne.jp/~futaiji/"},
  {title: "補陀洛山寺", address: "和歌山県東牟婁郡那智勝浦町浜ノ宮348", official_url: "http://www.nachikan.jp/kumano/fudarakusanji/"},
  {title: "佛光寺", address: "京都府京都市下京区新開町３９７", official_url: "http://www.bukkoji.or.jp/"},
  {title: "仏隆寺", address: "奈良県宇陀市榛原赤埴１６８４", official_url: "http://www.city.uda.nara.jp/sin-kankou/guide/shrine_temple/t11.html"},
  {title: "普門寺", address: "大阪府高槻市富田町４丁目１０−１０", official_url: nil},
  {title: "豊楽寺", address: "高知県長岡郡大豊町寺内３１４", official_url: nil},
  {title: "芬陀院", address: "京都府京都市東山区本町１５丁目８０３", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000202"},
  {title: "不動院", address: "大阪府豊中市服部本町１丁目１−８−２１", official_url: nil},
  {title: "法界寺", address: "京都府京都市伏見区日野西大道町１９", official_url: "http://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000206"},
  {title: "法観寺", address: "京都府京都市東山区清水八坂上町388", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000273"},
  {title: "法起寺", address: "奈良県生駒郡斑鳩町岡本１８７３番地", official_url: "http://www.horyuji.or.jp/hokiji.htm"},
  {title: "放光寺(山梨県)", address: "山梨県甲州市塩山藤木２４３８", official_url: "http://www.hokoji.org/"},
  {title: "放光寺(長野県)", address: "長野県松本市蟻ケ崎（大字） 長野県松本市蟻ケ崎1283", official_url: "http://houkouji.com/"},
  {title: "方広寺(京都府)", address: "京都府京都市東山区正面通大和大路東入茶屋町５２７−２", official_url: nil},
  {title: "方広寺(静岡県)", address: "静岡県浜松市北区引佐町奥山１５７７−１", official_url: "http://www.houkouji.or.jp/"},
  {title: "宝厳院", address: "京都府京都市右京区嵯峨天龍寺芒ノ馬場町 右京区嵯峨天龍寺芒ノ馬場町３６", official_url: "http://www.hogonin.jp/"},
  {title: "法金剛院", address: "京都府京都市右京区花園扇野町 京都府京都市右京区花園扇野町４９", official_url: "http://www.y-morimoto.com/hananotera/13hokongo.html"},
  {title: "宝厳寺", address: "滋賀県長浜市早崎町１６６４−１", official_url: "http://www.chikubushima.jp/"},
  {title: "宝山寺", address: "奈良県生駒市門前町１−１", official_url: "http://www.hozanji.com/"},
  {title: "法住寺", address: "京都府京都市東山区三十三間堂廻リ６５５", official_url: "http://hojyuji.jp/"},
  {title: "宝泉院", address: "京都府京都市左京区大原勝林院町 左京区大原勝林院町187番地", official_url: "http://www.hosenin.net/"},
  {title: "法善寺", address: "山梨県南アルプス市加賀美 山梨県南アルプス市加賀美3509", official_url: nil},
  {title: "法然院", address: "京都府京都市左京区鹿ケ谷御所ノ段町３０番地", official_url: "http://www.honen-in.jp/"},
  {title: "法隆寺", address: "奈良県生駒郡斑鳩町法隆寺", official_url: nil},
  {title: "法輪寺", address: "奈良県生駒郡斑鳩町三井１５７０", official_url: "http://www1.kcn.ne.jp/~horinji/"},
  {title: "法華経寺", address: "千葉県市川市中山２丁目２−１０−１", official_url: "http://hokekyoji2101.wixsite.com/nakayama"},
  {title: "法華寺", address: "奈良県奈良市法華寺町882", official_url: "http://www.hokkeji-nara.jp/"},
  {title: "本願寺(京都府)", address: "京都府京都市下京区常葉町 烏丸通七条上る", official_url: "http://www.higashihonganji.or.jp/"},
  {title: "本行院", address: "埼玉県川越市久保町９−２", official_url: "http://www.kawagoe-naritasan.net/"},
  {title: "本興寺", address: "兵庫県尼崎市開明町３丁目１３", official_url: "http://www.hokkeshu.or.jp/honzan/honkoji.html"},
  {title: "本圀寺", address: "京都府京都市山科区御陵大岩６", official_url: "http://temple.nichiren.or.jp/5011092-honkokuji/"},
  {title: "本山寺(大阪府)", address: "大阪府高槻市原３２９８", official_url: nil},
  {title: "本成寺", address: "新潟県三条市西本成寺１丁目１−２０", official_url: "http://www.city.sanjo.niigata.jp/eigyo/page00084.html"},
  {title: "本禅寺", address: "京都府京都市上京区北之辺町 京都府京都市上京区寺町通広小路上る北之辺町394", official_url: nil},
  {title: "本能寺", address: "京都府京都市中京区下本能寺前町 京都府京都市中京区寺町通御池下る下本能寺前町５２２", official_url: "http://www.kyoto-honnouji.jp/"},
  {title: "本法寺", address: "京都府京都市上京区本法寺前町 小川通寺ノ内上ル本法寺前町617番地", official_url: "http://eishouzan.honpouji.nichiren-shu.jp/info/info.htm"},
  {title: "松尾寺(京都府)", address: "京都府舞鶴市松尾５３２", official_url: "http://www.matsunoodera.com/"},
  {title: "松尾寺(奈良県)", address: "奈良県大和郡山市山田町683", official_url: "http://www.matsuodera.com/information/section3.html#sec12"},
  {title: "満願寺(栃木県)", address: "栃木県栃木市出流町２８８", official_url: "http://www.idurusan.com/"},
  {title: "満願寺(東京都)", address: "東京都世田谷区等々力３丁目１５−１", official_url: "http://manganji.or.jp/"},
  {title: "曼殊院", address: "京都府京都市左京区一乗寺竹ノ内町４２", official_url: "http://www.manshuinmonzeki.jp/"},
  {title: "万寿寺", address: "京都府京都市下京区万寿寺町", official_url: nil},
  {title: "萬福寺", address: "京都府宇治市五ケ庄三番割３４", official_url: "http://www.obakusan.or.jp/"},
  {title: "水間寺", address: "大阪府貝塚市水間６３８", official_url: "http://www.mizumadera.or.jp/index.html"},
  {title: "壬生寺(京都府)", address: "京都府京都市中京区中京区壬生梛ノ宮町３１", official_url: "http://www.mibudera.com/"},
  {title: "壬生寺(栃木県)", address: "栃木県下都賀郡壬生町大師町１１−１７", official_url: "http://www.jikakudaishi.com/"},
  {title: "南法華寺", address: "奈良県高市郡高取町壷阪3", official_url: "http://www.tsubosaka1300.or.jp/"},
  {title: "三室戸寺", address: "京都府宇治市莵道滋賀谷２１", official_url: "http://www.mimurotoji.com/"},
  {title: "明王院(滋賀県)", address: "滋賀県大津市葛川坊村町１５５", official_url: nil},
  {title: "明王院(広島県)", address: "広島県福山市草戸町 広島県福山市草戸町", official_url: nil},
  {title: "妙喜庵", address: "京都府乙訓郡大山崎町大山崎竜光５６", official_url: "http://oyamazaki.info/archives/761"},
  {title: "妙顕寺", address: "京都府京都市上京区妙顕寺前町 京都府京都市上京区寺之内通新町西入妙顕寺前町514", official_url: "https://www.shikaishodo-myokenji.org/"},
  {title: "妙心寺", address: "京都府京都市右京区花園妙心寺町64", official_url: "http://www.myoshinji.or.jp/"},
  {title: "明通寺", address: "福井県小浜市門前５−21", official_url: "http://www1.city.obama.fukui.jp/category/page.asp?Page=96"},
  {title: "妙法院", address: "京都府京都市東山区妙法院前側町４４７", official_url: "https://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000224"},
  {title: "妙満寺", address: "京都府京都市左京区左京区岩倉幡枝町 岩倉幡枝町９１", official_url: "http://www.myomanji.jp/"},
  {title: "妙蓮寺", address: "京都府京都市上京区妙蓮寺前町 寺之内通大宮東入妙蓮寺前町８７５", official_url: "http://myorenji.or.jp/"},
  {title: "室生寺", address: "奈良県宇陀市室生７８", official_url: "http://www.murouji.or.jp/"},
  {title: "明月院", address: "神奈川県鎌倉市山ノ内１８９", official_url: nil},
  {title: "毛越寺", address: "岩手県西磐井郡平泉町平泉大沢大沢５８", official_url: "http://www.motsuji.or.jp/"},
  {title: "本山寺(香川県)", address: "香川県三豊市豊中町本山甲1445", official_url: "http://www.88shikokuhenro.jp/kagawa/70motoyamaji/index.html"},
  {title: "薬王寺", address: "徳島県海部郡美波町奥河内寺前285−1", official_url: "http://yakuouji.net/"},
  {title: "薬師寺(奈良県)", address: "奈良県奈良市西ノ京町４５７", official_url: "http://www.nara-yakushiji.com/index.html"},
  {title: "矢田寺", address: "奈良県大和郡山市矢田町３５４９", official_url: "http://www.yatadera.or.jp/"},
  {title: "野中寺", address: "大阪府羽曳野市野々上５丁目９−２４", official_url: nil},
  {title: "養源院", address: "京都府京都市東山区三十三間堂廻リ 東山区三十三間堂廻り町656", official_url: "http://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000229"},
  {title: "横蔵寺", address: "岐阜県揖斐郡揖斐川町谷汲神原１１６０", official_url: nil},
  {title: "善峯寺", address: "京都府京都市西京区大原野小塩町1372", official_url: "http://www.yoshiminedera.com/"},
  {title: "與田寺", address: "香川県東かがわ市中筋４６５", official_url: nil},
  {title: "来迎院", address: "京都府京都市左京区大原来迎院町５３７", official_url: nil},
  {title: "楽法寺", address: "茨城県桜川市本木１", official_url: "http://www.amabiki.or.jp/"},
  {title: "櫟野寺", address: "滋賀県甲賀市甲賀町櫟野１３７７", official_url: "http://www.rakuyaji.jp/"},
  {title: "立石寺", address: "山形県山形市山寺４４５６−１", official_url: "http://www.rissyakuji.jp/"},
  {title: "龍興寺", address: "福島県大沼郡会津美里町龍興寺北 福島県大沼郡会津美里町字龍興寺北甲２２２２−３", official_url: nil},
  {title: "龍角寺", address: "千葉県印旛郡栄町龍角寺", official_url: nil},
  {title: "龍安寺", address: "京都府京都市右京区龍安寺御陵ノ下町１３", official_url: "http://www.ryoanji.jp/"},
  {title: "龍吟庵", address: "京都府京都市東山区本町１５丁目８１２", official_url: "http://www.tofukuji.jp/"},
  {title: "龍源院", address: "京都府京都市北区紫野大徳寺町82−１", official_url: "http://www.kyoto-kankou.or.jp/info_search/?id=684&r=1475033544.3284"},
  {title: "龍光院", address: "京都府京都市北区紫野大徳寺町１４", official_url: nil},
  {title: "霊山寺(奈良県)", address: "奈良県奈良市中町3879", official_url: "http://www.ryosenji.jp/"},
  {title: "霊山寺(徳島県)", address: "徳島県鳴門市大麻町板東字塚鼻126", official_url: "http://www.88shikokuhenro.jp/tokushima/01ryozenji/index.html"},
  {title: "林昌寺", address: "大阪府泉南市信達岡中３９５", official_url: nil},
  {title: "輪王寺", address: "栃木県日光市山内 栃木県日光市山内２３００", official_url: "http://rinnoji.or.jp/precincts/houmotsuden"},
  {title: "瑠璃光寺", address: "山口県山口市香山町７−１", official_url: "http://yamaguchi-city.jp/details/aa_ruri_tou.html"},
  {title: "瑠璃寺(兵庫県)", address: "兵庫県佐用郡佐用町船越８７７", official_url: nil},
  {title: "霊雲院", address: "京都府京都市東山区本町１５丁目８０１", official_url: "http://www.gshuhou.com/LP/reiunn/"},
  {title: "霊雲寺", address: "東京都文京区湯島２丁目２１−６", official_url: nil},
  {title: "蓮華峰寺", address: "新潟県佐渡市小比叡１８２", official_url: nil},
  {title: "鹿苑寺", address: "京都府京都市北区金閣寺町１", official_url: "http://www.shokoku-ji.jp/k_access.html"},
  {title: "六波羅蜜寺", address: "京都府京都市東山区轆轤町 五条通大和大路上ル東", official_url: "http://rokuhara.or.jp/"},
  {title: "廬山寺", address: "京都府京都市上京区北之辺町３９７", official_url: "http://www7a.biglobe.ne.jp/~rozanji/"},
  {title: "公会堂", address: "北海道小樽市花園５丁目２−１", official_url: "http://otarushiminkaikan.jp/koukai/"},
  {title: "札幌市教育文化会館", address: "北海道札幌市中央区北１条西１３丁目", official_url: "http://www.kyobun.org/"},
  {title: "伝統芸能伝承館森舞台", address: "宮城県登米市登米町寺池桜小路 宮城県登米市登米町寺池上町42", official_url: "http://toyoma.co.jp/facilities-densho/"},
  {title: "庄内能楽館", address: "山形県酒田市浜松町１ 山形県酒田市浜松町1−1", official_url: nil},
  {title: "阿能川会館", address: "群馬県利根郡みなかみ町阿能川５５２", official_url: nil},
  {title: "国立能楽堂", address: "東京都渋谷区千駄ヶ谷４丁目４−１８−１", official_url: "http://www.ntj.jac.go.jp/nou.html"},
  {title: "宝生能楽堂", address: "東京都文京区本郷１丁目５ 本郷1丁目5−9", official_url: "http://www.hosho.or.jp/"},
  {title: "矢来能楽堂", address: "東京都新宿区矢来町６０", official_url: "http://yarai-nohgakudo.com/"},
  {title: "梅若能楽学院会館", address: "東京都中野区東中野２丁目６−１４", official_url: "http://umewakanoh.exblog.jp/"},
  {title: "十四世喜多六平太記念能楽堂", address: "東京都品川区上大崎４丁目６−９", official_url: "http://kita-noh.com/"},
  {title: "観世能楽堂", address: "東京都中央区銀座６丁目１０−１ B3F", official_url: "http://kanze.net/"},
  {title: "公益社団法人 能楽協会", address: "東京都新宿区高田馬場４丁目４０−１３ 双秀ビル", official_url: "http://www.nohgaku.or.jp/"},
  {title: "銕仙会能楽研修所", address: "東京都港区南青山４丁目２１−２１−２９", official_url: "http://www.tessen.org/"},
  {title: "セルリアンタワー能楽堂", address: "東京都渋谷区桜丘町２６−１", official_url: "http://www.ceruleantower-noh.com/"},
  {title: "代々木能舞台", address: "東京都渋谷区代々木４丁目３６ 代々木４丁目３６−１４", official_url: "http://www.yoyoginoubutai.com/"},
  {title: "能楽書林", address: "東京都千代田区神田神保町３丁目 東京都千代田区神田神保町3丁目6−1", official_url: "http://nohgakushorin.co.jp/"},
  {title: "杉並能楽堂", address: "東京都杉並区和田１丁目５５ 和田１丁目５５−９", official_url: "http://www.city.suginami.tokyo.jp/kyouiku/bunkazai/hyouji/1008023.html"},
  {title: "横浜能楽堂", address: "神奈川県横浜市西区紅葉ケ丘２７−２", official_url: "http://ynt.yafjp.org/"},
  {title: "金井能楽堂", address: "新潟県佐渡市中興 新潟県佐渡市中興甲371", official_url: nil},
  {title: "本間家能舞台", address: "新潟県佐渡市吾潟 新潟県佐渡市吾潟丙987", official_url: nil},
  {title: "富山市役所 富山能楽堂", address: "富山県富山市友杉１０９７", official_url: nil},
  {title: "石川県立能楽堂", address: "石川県金沢市石引４丁目１８−３", official_url: "http://www.pref.ishikawa.lg.jp/nougakudo/nougakudoutop.html"},
  {title: "能化公会堂", address: "長野県飯田市北方３４８９−２", official_url: nil},
  {title: "名古屋能楽堂", address: "愛知県名古屋市中区三の丸１丁目１−１−１", official_url: "http://www.bunka758.or.jp/scd24_top.html"},
  {title: "栄能楽堂", address: "愛知県名古屋市中区栄５丁目６−４", official_url: "http://www.k4.dion.ne.jp/~gotou/"},
  {title: "岡崎城二の丸能楽堂", address: "愛知県岡崎市康生町５６１−１", official_url: "http://okazakipark.com/nougalkudou/nougakudou.htm"},
  {title: "大津市立会館伝統芸能会館", address: "滋賀県大津市園城寺町２４６−２４", official_url: "http://www.dentogeinokaikan.net/"},
  {title: "伴能十全堂", address: "吉身一丁目6-31, １丁目-６ 吉身 守山市 滋賀県 524-0021 日本", official_url: "http://www.eonet.ne.jp/~hyougu/"},
  {title: "金剛能楽堂", address: "京都府京都市上京区龍前町 上京区烏丸通一条下る龍前町590", official_url: "http://www.kongou-net.com/"},
  {title: "河村能舞台", address: "京都府京都市上京区柳図子町 京都府京都市上京区烏丸通上立売上る柳図子町320−14", official_url: "http://www.omosiro-noh-taiken.kyoto.jp/"},
  {title: "京都観世会館", address: "京都府京都市左京区岡崎円勝寺町 左京区岡崎円勝寺町44", official_url: "http://www.kyoto-kanze.jp/"},
  {title: "大江能楽堂", address: "京都府京都市中京区橘町（押小路通） 京都府京都市中京区押小路通柳馬場東入橘町646", official_url: "http://www.asahi-net.or.jp/~tn4m-ooe/"},
  {title: "大江能楽会", address: "京都府京都市東山区本町２０丁目４２８", official_url: "http://www.asahi-net.or.jp/~tn4m-ooe/"},
  {title: "京都・市民放射能測定所", address: "京都府京都市伏見区両替町９丁目 京都府京都市伏見区両替町9丁目254−203", official_url: "http://nukecheck.namaste.jp/"},
  {title: "能楽幸流小鼓教室 林木双会", address: "京都府京都市中京区橘町（押小路通）", official_url: "http://mokusoukai.net/"},
  {title: "能楽名盤会", address: "京都府京都市左京区田中上柳町 京都府京都市左京区田中上柳町９０", official_url: nil},
  {title: "北能舞台", address: "京都府京都市下京区門前町", official_url: nil},
  {title: "山本能楽堂", address: "大阪府大阪市中央区徳井町１丁目３−６", official_url: "http://www.noh-theater.com/"},
  {title: "大槻能楽堂", address: "大阪府大阪市中央区上町Ａ 大阪府大阪市中央区上町A−7", official_url: "http://www.noh-kyogen.com/"},
  {title: "本城能楽堂", address: "兵庫県姫路市元塩町１４１", official_url: nil},
  {title: "面塚 観世能楽発祥の地", address: "〒636-0202, 結崎 川西町 磯城郡 奈良県 636-0202 日本", official_url: "http://www.town.nara-kawanishi.lg.jp/contents_detail.php?co=kak&frmId=193"},
  {title: "大濠公園能楽堂", address: "福岡県福岡市中央区大濠公園１−５", official_url: "http://www.ohori-nougaku.jp/"},
  {title: "能学館長崎南教室", address: "長崎県長崎市末石町３７０−５５ シティーハウス伸 2F", official_url: nil},
  {title: "能楽殿", address: "熊本県熊本市中央区水前寺公園７−３４ 〒862-0956", official_url: nil},
  {title: "藤崎八幡宮御旅所能舞台", address: "熊本県熊本市中央区新町３丁目１−２６", official_url: nil},
  {title: "菊池市松囃子能舞台", address: "熊本県菊池市隈府 隈府２１６−５", official_url: nil},
  {title: "平和市民公園能楽堂", address: "大分県大分市牧緑町１−３０", official_url: "http://www.nogaku.jp/"},
  {title: "小能公民館", address: "鹿児島県曽於郡大崎町井俣", official_url: nil}
])

Program.create!([
  {title: "藍染川", category: "四番目", shimai: true, duration: 25, place_id: 233},
  {title: "葵上", category: "四番目", shimai: true, duration: 15, place_id: 45},
  {title: "阿漕", category: "四番目", shimai: true, duration: 60, place_id: 264},
  {title: "芦刈", category: "四番目", shimai: true, duration: 40, place_id: 107},
  {title: "安宅", category: "四番目", shimai: true, duration: 46, place_id: 87},
  {title: "愛宕空也", category: "五番目", shimai: true, duration: 33, place_id: 213},
  {title: "黒塚", category: "番目", shimai: true, duration: 33, place_id: 9},
  {title: "敦盛", category: "二番目", shimai: true, duration: 25, place_id: 219},
  {title: "海人", category: "五番目", shimai: true, duration: 18, place_id: 83},
  {title: "綾鼓", category: "四番目", shimai: true, duration: 29, place_id: 116},
  {title: "嵐山", category: "一番目", shimai: true, duration: 40, place_id: 188},
  {title: "蟻通", category: "四番目", shimai: true, duration: 30, place_id: 61},
  {title: "淡路", category: "番目", shimai: true, duration: 50, place_id: 329},
  {title: "碇潜", category: "五番目", shimai: true, duration: 12, place_id: 239},
  {title: "生田敦盛", category: "二番目", shimai: true, duration: 3, place_id: 93},
  {title: "一角仙人", category: "五番目", shimai: true, duration: 25, place_id: 33},
  {title: "井筒", category: "三番目", shimai: true, duration: 57, place_id: 305},
  {title: "岩舟", category: "一番目", shimai: true, duration: 12, place_id: 57},
  {title: "鵜飼", category: "五番目", shimai: true, duration: 42, place_id: 331},
  {title: "浮船", category: "四番目", shimai: true, duration: 29, place_id: 177},
  {title: "雨月", category: "四番目", shimai: true, duration: 31, place_id: 207},
  {title: "歌占", category: "四番目", shimai: true, duration: 41, place_id: 338},
  {title: "内外詣", category: "番目", shimai: true, duration: 22, place_id: 238},
  {title: "善知鳥", category: "四番目", shimai: true, duration: 9, place_id: 51},
  {title: "采女", category: "三番目", shimai: true, duration: 43, place_id: 71},
  {title: "梅", category: "番目", shimai: true, duration: 7, place_id: 323},
  {title: "梅枝", category: "四番目", shimai: true, duration: 36, place_id: 83},
  {title: "鱗形", category: "四番目", shimai: true, duration: 48, place_id: 306},
  {title: "雲林院", category: "三番目", shimai: true, duration: 37, place_id: 378},
  {title: "江口", category: "三番目", shimai: true, duration: 17, place_id: 346},
  {title: "江島", category: "一番目", shimai: true, duration: 58, place_id: 143},
  {title: "江野島", category: "番目", shimai: true, duration: 32, place_id: 147},
  {title: "箙", category: "二番目", shimai: true, duration: 55, place_id: 89},
  {title: "烏帽子折", category: "四番目", shimai: true, duration: 21, place_id: 318},
  {title: "絵馬", category: "一番目", shimai: true, duration: 20, place_id: 347},
  {title: "老松", category: "一番目", shimai: true, duration: 27, place_id: 327},
  {title: "大瓶猩猩", category: "五番目", shimai: true, duration: 35, place_id: 261},
  {title: "大江山", category: "五番目", shimai: true, duration: 33, place_id: 286},
  {title: "鸚鵡小町", category: "三番目", shimai: true, duration: 12, place_id: 286},
  {title: "大社", category: "番目", shimai: true, duration: 33, place_id: 143},
  {title: "小塩", category: "三番目", shimai: true, duration: 57, place_id: 263},
  {title: "姨捨", category: "三番目", shimai: true, duration: 46, place_id: 235},
  {title: "大原御幸", category: "三番目", shimai: true, duration: 40, place_id: 310},
  {title: "女郎花", category: "四番目", shimai: true, duration: 6, place_id: 364},
  {title: "杜若", category: "三番目", shimai: true, duration: 60, place_id: 131},
  {title: "籠祇王", category: "三番目", shimai: true, duration: 58, place_id: 93},
  {title: "翁", category: "一番目", shimai: true, duration: 27, place_id: 161},
  {title: "景清", category: "四番目", shimai: true, duration: 13, place_id: 295},
  {title: "花月", category: "四番目", shimai: true, duration: 58, place_id: 312},
  {title: "柏崎", category: "番目", shimai: true, duration: 55, place_id: 295},
  {title: "春日龍神", category: "五番目", shimai: true, duration: 9, place_id: 271},
  {title: "葛城", category: "四番目", shimai: true, duration: 12, place_id: 351},
  {title: "葛城天狗", category: "五番目", shimai: true, duration: 51, place_id: 70},
  {title: "合浦", category: "番目", shimai: true, duration: 59, place_id: 134},
  {title: "鉄輪", category: "四番目", shimai: true, duration: 44, place_id: 114},
  {title: "", category: "二番目", shimai: true, duration: 5, place_id: 358},
  {title: "賀茂", category: "一番目", shimai: true, duration: 28, place_id: 143},
  {title: "通小町", category: "四番目", shimai: true, duration: 54, place_id: 362},
  {title: "邯鄲", category: "四番目", shimai: true, duration: 35, place_id: 180},
  {title: "咸陽殿", category: "番目", shimai: true, duration: 45, place_id: 267},
  {title: "祇王", category: "三番目", shimai: true, duration: 53, place_id: 246},
  {title: "俊寛", category: "番目", shimai: true, duration: 31, place_id: 233},
  {title: "枕慈童", category: "四番目", shimai: true, duration: 22, place_id: 279},
  {title: "木曽", category: "四番目", shimai: true, duration: 5, place_id: 181},
  {title: "砧", category: "四番目", shimai: true, duration: 38, place_id: 363},
  {title: "清経", category: "二番目", shimai: true, duration: 43, place_id: 284},
  {title: "草薙", category: "五番目", shimai: true, duration: 8, place_id: 266},
  {title: "国栖", category: "五番目", shimai: true, duration: 1, place_id: 129},
  {title: "熊坂", category: "五番目", shimai: true, duration: 59, place_id: 99},
  {title: "鞍馬天狗", category: "五番目", shimai: true, duration: 53, place_id: 55},
  {title: "車僧", category: "五番目", shimai: true, duration: 31, place_id: 359},
  {title: "呉服", category: "番目", shimai: true, duration: 45, place_id: 348},
  {title: "鶴亀", category: "番目", shimai: true, duration: 29, place_id: 204},
  {title: "源氏供養", category: "三番目", shimai: true, duration: 24, place_id: 47},
  {title: "現在七面", category: "四番目", shimai: true, duration: 18, place_id: 27},
  {title: "絃上", category: "五番目", shimai: true, duration: 10, place_id: 225},
  {title: "恋松原", category: "四番目", shimai: true, duration: 22, place_id: 277},
  {title: "恋重荷", category: "四番目", shimai: true, duration: 58, place_id: 49},
  {title: "項羽", category: "五番目", shimai: true, duration: 29, place_id: 165},
  {title: "皇帝", category: "番目", shimai: true, duration: 16, place_id: 271},
  {title: "高野物狂", category: "四番目", shimai: true, duration: 26, place_id: 214},
  {title: "小鍛冶", category: "五番目", shimai: true, duration: 2, place_id: 95},
  {title: "小督", category: "四番目", shimai: true, duration: 10, place_id: 190},
  {title: "小袖曽我", category: "四番目", shimai: true, duration: 52, place_id: 43},
  {title: "胡蝶", category: "三番目", shimai: true, duration: 3, place_id: 13},
  {title: "西行桜", category: "四番目", shimai: true, duration: 48, place_id: 252},
  {title: "佐保山", category: "番目", shimai: true, duration: 60, place_id: 167},
  {title: "逆矛", category: "番目", shimai: true, duration: 46, place_id: 181},
  {title: "鷺", category: "四番目", shimai: true, duration: 51, place_id: 185},
  {title: "桜川", category: "四番目", shimai: true, duration: 37, place_id: 150},
  {title: "桜井", category: "四番目", shimai: true, duration: 13, place_id: 174},
  {title: "桜井駅", category: "四番目", shimai: true, duration: 13, place_id: 24},
  {title: "実方", category: "番目", shimai: true, duration: 46, place_id: 332},
  {title: "実盛", category: "二番目", shimai: true, duration: 33, place_id: 279},
  {title: "志賀", category: "番目", shimai: true, duration: 7, place_id: 133},
  {title: "七騎落", category: "四番目", shimai: true, duration: 23, place_id: 127},
  {title: "自然居士", category: "四番目", shimai: true, duration: 43, place_id: 352},
  {title: "石橋", category: "五番目", shimai: true, duration: 36, place_id: 213},
  {title: "舎利", category: "五番目", shimai: true, duration: 11, place_id: 252},
  {title: "春栄", category: "番目", shimai: true, duration: 23, place_id: 330},
  {title: "鍾馗", category: "五番目", shimai: true, duration: 48, place_id: 277},
  {title: "昭君", category: "五番目", shimai: true, duration: 19, place_id: 214},
  {title: "猩々", category: "五番目", shimai: true, duration: 42, place_id: 311},
  {title: "正尊", category: "四番目", shimai: true, duration: 3, place_id: 204},
  {title: "白髭", category: "番目", shimai: true, duration: 24, place_id: 80},
  {title: "代主", category: "番目", shimai: true, duration: 13, place_id: 228},
  {title: "須磨源氏", category: "番目", shimai: true, duration: 29, place_id: 162},
  {title: "隅田川", category: "四番目", shimai: true, duration: 21, place_id: 288},
  {title: "住吉詣", category: "番目", shimai: true, duration: 51, place_id: 46},
  {title: "西王母", category: "一番目", shimai: true, duration: 38, place_id: 327},
  {title: "誓願寺", category: "番目", shimai: true, duration: 41, place_id: 194},
  {title: "善界", category: "五番目", shimai: true, duration: 40, place_id: 126},
  {title: "関寺小町", category: "三番目", shimai: true, duration: 34, place_id: 228},
  {title: "殺生石", category: "四番目", shimai: true, duration: 48, place_id: 252},
  {title: "蝉丸 (能)", category: "四番目", shimai: true, duration: 18, place_id: 21},
  {title: "千手", category: "三番目", shimai: true, duration: 50, place_id: 330},
  {title: "草子洗小町", category: "三番目", shimai: true, duration: 49, place_id: 234},
  {title: "卒都婆小町", category: "四番目", shimai: true, duration: 29, place_id: 237},
  {title: "大会", category: "五番目", shimai: true, duration: 5, place_id: 297},
  {title: "泰山府君", category: "五番目", shimai: true, duration: 17, place_id: 350},
  {title: "大仏供養", category: "四番目", shimai: true, duration: 15, place_id: 327},
  {title: "第六天", category: "五番目", shimai: true, duration: 44, place_id: 369},
  {title: "当麻", category: "五番目", shimai: true, duration: 53, place_id: 257},
  {title: "高砂", category: "一番目", shimai: true, duration: 33, place_id: 204},
  {title: "忠信", category: "四番目", shimai: true, duration: 27, place_id: 89},
  {title: "忠度", category: "二番目", shimai: true, duration: 23, place_id: 184},
  {title: "龍田", category: "四番目", shimai: true, duration: 1, place_id: 323},
  {title: "谷行", category: "四番目", shimai: true, duration: 29, place_id: 47},
  {title: "玉鬘", category: "四番目", shimai: true, duration: 54, place_id: 367},
  {title: "田村", category: "二番目", shimai: true, duration: 5, place_id: 243},
  {title: "竹生島", category: "一番目", shimai: true, duration: 28, place_id: 67},
  {title: "土蜘蛛", category: "五番目", shimai: true, duration: 48, place_id: 247},
  {title: "土車", category: "番目", shimai: true, duration: 43, place_id: 69},
  {title: "経正", category: "二番目", shimai: true, duration: 48, place_id: 37},
  {title: "妻戸", category: "五番目", shimai: true, duration: 25, place_id: 142},
  {title: "定家", category: "三番目", shimai: true, duration: 23, place_id: 169},
  {title: "点鼓", category: "四番目", shimai: true, duration: 51, place_id: 235},
  {title: "道成寺", category: "四番目", shimai: true, duration: 16, place_id: 26},
  {title: "唐船", category: "四番目", shimai: true, duration: 35, place_id: 260},
  {title: "東方朔", category: "一番目", shimai: true, duration: 40, place_id: 274},
  {title: "東北", category: "三番目", shimai: true, duration: 44, place_id: 79},
  {title: "道明寺", category: "一番目", shimai: true, duration: 39, place_id: 161},
  {title: "融", category: "五番目", shimai: true, duration: 42, place_id: 358},
  {title: "木賊", category: "四番目", shimai: true, duration: 38, place_id: 13},
  {title: "巴", category: "二番目", shimai: true, duration: 22, place_id: 53},
  {title: "朝長", category: "二番目", shimai: true, duration: 38, place_id: 230},
  {title: "知章", category: "二番目", shimai: true, duration: 32, place_id: 370},
  {title: "満仲", category: "番目", shimai: true, duration: 29, place_id: 144},
  {title: "難波", category: "一番目", shimai: true, duration: 35, place_id: 97},
  {title: "錦木", category: "番目", shimai: true, duration: 4, place_id: 154},
  {title: "鵺", category: "五番目", shimai: true, duration: 30, place_id: 378},
  {title: "野宮", category: "三番目", shimai: true, duration: 18, place_id: 328},
  {title: "野守", category: "五番目", shimai: true, duration: 23, place_id: 169},
  {title: "羽衣", category: "三番目", shimai: true, duration: 15, place_id: 227},
  {title: "半蔀", category: "三番目", shimai: true, duration: 17, place_id: 319},
  {title: "橋弁慶", category: "四番目", shimai: true, duration: 54, place_id: 176},
  {title: "芭蕉", category: "番目", shimai: true, duration: 13, place_id: 131},
  {title: "鉢木", category: "四番目", shimai: true, duration: 31, place_id: 138},
  {title: "初雪", category: "三番目", shimai: true, duration: 23, place_id: 146},
  {title: "花軍", category: "三番目", shimai: true, duration: 30, place_id: 154},
  {title: "花筐", category: "四番目", shimai: true, duration: 31, place_id: 60},
  {title: "班女", category: "四番目", shimai: true, duration: 43, place_id: 343},
  {title: "飛雲", category: "五番目", shimai: true, duration: 57, place_id: 142},
  {title: "檜垣", category: "三番目", shimai: true, duration: 18, place_id: 67},
  {title: "雲雀山", category: "四番目", shimai: true, duration: 6, place_id: 284},
  {title: "氷室", category: "番目", shimai: true, duration: 38, place_id: 228},
  {title: "百万", category: "四番目", shimai: true, duration: 4, place_id: 224},
  {title: "豊干", category: "四番目", shimai: true, duration: 50, place_id: 120},
  {title: "富士太鼓", category: "四番目", shimai: true, duration: 30, place_id: 368},
  {title: "藤戸", category: "四番目", shimai: true, duration: 8, place_id: 318},
  {title: "二人静", category: "四番目", shimai: true, duration: 58, place_id: 251},
  {title: "船弁慶", category: "五番目", shimai: true, duration: 20, place_id: 280},
  {title: "放下僧", category: "四番目", shimai: true, duration: 15, place_id: 246},
  {title: "放生川", category: "一番目", shimai: true, duration: 15, place_id: 277},
  {title: "巻絹", category: "四番目", shimai: true, duration: 15, place_id: 204},
  {title: "松風", category: "三番目", shimai: true, duration: 13, place_id: 351},
  {title: "松虫", category: "四番目", shimai: true, duration: 34, place_id: 184},
  {title: "松山鏡", category: "四番目", shimai: true, duration: 57, place_id: 109},
  {title: "松山天狗", category: "五番目", shimai: true, duration: 39, place_id: 239},
  {title: "三井寺", category: "四番目", shimai: true, duration: 56, place_id: 384},
  {title: "通盛", category: "二番目", shimai: true, duration: 56, place_id: 322},
  {title: "水無瀬", category: "四番目", shimai: true, duration: 39, place_id: 104},
  {title: "御裳濯", category: "番目", shimai: true, duration: 52, place_id: 215},
  {title: "三輪", category: "四番目", shimai: true, duration: 47, place_id: 302},
  {title: "室君", category: "四番目", shimai: true, duration: 30, place_id: 371},
  {title: "和布刈", category: "一番目", shimai: true, duration: 43, place_id: 24},
  {title: "望月", category: "四番目", shimai: true, duration: 54, place_id: 50},
  {title: "求塚", category: "四番目", shimai: true, duration: 12, place_id: 69},
  {title: "紅葉狩", category: "五番目", shimai: true, duration: 23, place_id: 75},
  {title: "盛久", category: "四番目", shimai: true, duration: 33, place_id: 335},
  {title: "屋島", category: "二番目", shimai: true, duration: 35, place_id: 34},
  {title: "山姥", category: "五番目", shimai: true, duration: 23, place_id: 234},
  {title: "雪", category: "三番目", shimai: true, duration: 58, place_id: 380},
  {title: "遊行桜", category: "三番目", shimai: true, duration: 51, place_id: 130},
  {title: "遊行柳", category: "三番目", shimai: true, duration: 14, place_id: 176},
  {title: "弓八幡", category: "番目", shimai: true, duration: 1, place_id: 239},
  {title: "熊野", category: "三番目", shimai: true, duration: 45, place_id: 6},
  {title: "楊貴妃", category: "三番目", shimai: true, duration: 45, place_id: 73},
  {title: "夜討曽我", category: "四番目", shimai: true, duration: 46, place_id: 66},
  {title: "養老", category: "一番目", shimai: true, duration: 42, place_id: 121},
  {title: "吉野静", category: "番目", shimai: true, duration: 11, place_id: 291},
  {title: "吉野天人", category: "三番目", shimai: true, duration: 7, place_id: 6},
  {title: "頼政", category: "二番目", shimai: true, duration: 44, place_id: 305},
  {title: "弱法師", category: "四番目", shimai: true, duration: 3, place_id: 234},
  {title: "雷電", category: "五番目", shimai: true, duration: 32, place_id: 265},
  {title: "羅生門", category: "五番目", shimai: true, duration: 17, place_id: 339},
  {title: "龍虎", category: "五番目", shimai: true, duration: 33, place_id: 331},
  {title: "輪蔵", category: "四番目", shimai: true, duration: 15, place_id: 155},
  {title: "籠太鼓", category: "四番目", shimai: true, duration: 8, place_id: 321}
])

User.create!([
  {name: "good example", email: "example@gmail.com", information: nil, password_digest: "$2a$10$If3v20WRuqY9lZWkfa3GPuOJwwx.KAihgrJ1nYoQUl6GUO4VXpR8S"},
  {name: "gen uchida", email: "uchida@gmail.com", information: nil, password_digest: "$2a$10$y.CXy7DGsFKFfAQqfQq1n./l2aQlNGElrko0yFbzdqLiTsSHOt1YS"},
  {name: "yasu takagi", email: "takagi@gmail.com", information: nil, password_digest: "$2a$10$hH2W67gAlrhTfV4bFMWVC.sxJi6z5YNoUf5CUTRQpUqJvNuFXcxWa"},
  {name: "ai ouchi", email: "ouchi@gmail.com", information: nil, password_digest: "$2a$10$hBTjFBQHLUjavbpw.mOViecnKftSORF/1unY3dfgYHbls0x.orPlW"},
  {name: "fumihisa taguchi", email: "taguchi@gmail.com", information: nil, password_digest: "$2a$10$A6UMnu6YYLkGcpF3rJGGE.X.37ril2eKr5e.zXWUIIiIvtwEYLCjO"},
  {name: "goro yoshida", email: "yoshida@gmail.com", information: nil, password_digest: "$2a$10$ssJzldzgcZ93534.T3n85u3rxHkB8elEItDGodRUPpKSFaZEuGfLW"},
  {name: "johny honda", email: "honda@gmail.com", information: nil, password_digest: "$2a$10$2hpotimDbzxg4aj7VR15jeqf0skN6e1un9VYMyNAUm6.t5w2q86gK"},
  {name: "eiji ito", email: "ito@gmail.com", information: nil, password_digest: "$2a$10$SqrCbj0Q7XqQDCOucfjN1.0ZxVJuuI6en52g4HHRqCucORWomeE12"},
  {name: "junta tanaka", email: "tanaka@gmail.com", information: nil, password_digest: "$2a$10$FOk.sxLbHaX4.X0TVvwtnu9.T4VtKjCvDnAsqzEWaki/gLD8A6HA."},
  {name: "maruko okamoto", email: "okamoto@gmail.com", information: nil, password_digest: "$2a$10$MbkDK9UjbA2iXIiswZHk0u9o8VodjNNc02p9ZlgAbvZuT32wZzaoS"},
  {name: "shinichiro higashihara", email: "higashihara@gmail.com", information: nil, password_digest: "$2a$10$ULuLosrl1d9IoKnDr6g.d.mMFX6SBqnFHa/E.2bwKXBrhH.h4XsUi"},
  {name: "sota otuska", email: "otuska@gmail.com", information: nil, password_digest: "$2a$10$1zQ9elsufZ07zfa3ptk.q.XpZxN4mmzNNMTSEl6wptRs2bdgEhA4W"},
  {name: "shun kaito", email: "kaito@gmail.com", information: nil, password_digest: "$2a$10$ux9GFA3YMkHhyOli.sqHseqLlwOENMCLZM3VZAS1eRsT.T5iZRY1S"},
  {name: "junta nakata", email: "nakata@gmail.com", information: nil, password_digest: "$2a$10$tP60yjBHrwWqiYLPlQboLexrp83jSokpGs4My0mbif9balFwKDgxy"},
  {name: "hidekazu mukai", email: "mukai@gmail.com", information: nil, password_digest: "$2a$10$Fn7CNYoSM0do5HDdVP7yiOwyw3us2/gXUUHTH6HB.zZVWxaLEMxYS"}
])
