Event.create!([
  {place_id: 1, user_id: 1, title: "第28回　廣田鑑賞会能", start_date: "2017-05-14 13:30:00", end_date: nil, information: "主役を勤める五流派（観世・宝生・金春・喜多・金剛）をシテ方といいます。\n                     そのシテの相手役を務めるワキ方と、笛・小鼓・大鼓・太鼓を演奏する囃子方、\n                     そして狂言方があります。シテとワキに連れられて出てくる役をツレ・ワキツレと呼びます。", official_url: "http://www.example.com/index.html"},
  {place_id: 2, user_id: 1, title: "京都観世会5月例会", start_date: "2017-05-28 11:00:00", end_date: nil, information: "", official_url: "http://www.kanzei.com/5th-kai.html"},
  {place_id: 1, user_id: 2, title: "金剛定期能", start_date: "2017-05-31 13:20:00", end_date: nil, information: "平成29年度の金剛定期能は年10回公演となります。\n                     毎月、宗家以下総出演で佳曲を揃えました。 また上演前に演目の解説も行います。\n                     29年度も多くの皆様にご鑑賞願いたく、絶大のご後援を賜ります様宜しくお願い申し上げます。\n                     皆様のご入会を心よりお待ち申し上げております。\n                     なお4月は特別公演として東本願寺能舞台にて開催いたします。", official_url: "http://www.example.com/regular.html"},
  {place_id: 2, user_id: 3, title: "市民狂言会", start_date: "2017-06-09 19:00:00", end_date: nil, information: "KAC　Performing　Arts　Program　/　Contemporary　Danceでは、\n                     京都芸術センターの創作環境を活かし、コンテンポラリーダンス表現の最前線で活躍する\n                     振付家・ダンサーを迎えて新作の創作・上演および旧作の再創作を行う。", official_url: "http://www.kac.or.jp/program/9443/"},
  {place_id: 2, user_id: 1, title: "独立25周年記念 第16回 吉浪壽晃 能の会", start_date: "2017-06-11 13:30:00", end_date: nil, information: "", official_url: "http://www.ecample.com/noh-no-kai.html"}
])
EventPerformer.create!([
  {event_program_id: 1, performer_id: 80},
  {event_program_id: 2, performer_id: 135},
  {event_program_id: 3, performer_id: 86},
  {event_program_id: 4, performer_id: 39},
  {event_program_id: 5, performer_id: 130},
  {event_program_id: 6, performer_id: 80},
  {event_program_id: 7, performer_id: 111},
  {event_program_id: 8, performer_id: 80},
  {event_program_id: 9, performer_id: 65},
  {event_program_id: 10, performer_id: 143},
  {event_program_id: 11, performer_id: 131},
  {event_program_id: 12, performer_id: 132},
  {event_program_id: 13, performer_id: 90},
  {event_program_id: 14, performer_id: 132}
])
EventProgram.create!([
  {event_id: 1, program_id: 1, style: "金剛流", genre: "舞囃子"},
  {event_id: 1, program_id: 2, style: "大蔵流", genre: "狂言"},
  {event_id: 1, program_id: 3, style: "金剛流", genre: "能"},
  {event_id: 2, program_id: 4, style: "観世流", genre: "能"},
  {event_id: 2, program_id: 2, style: "観世流", genre: "狂言"},
  {event_id: 2, program_id: 5, style: "金剛流", genre: "能"},
  {event_id: 3, program_id: 6, style: "金剛流", genre: "能"},
  {event_id: 3, program_id: 7, style: "金剛流", genre: "狂言"},
  {event_id: 3, program_id: 8, style: "金剛流", genre: "能"},
  {event_id: 4, program_id: 9, style: "観世流", genre: "狂言"},
  {event_id: 4, program_id: 10, style: "大蔵流", genre: "狂言"},
  {event_id: 4, program_id: 11, style: "観世流", genre: "狂言"},
  {event_id: 5, program_id: 12, style: "観世流", genre: "能"},
  {event_id: 5, program_id: 13, style: "観世流", genre: "能"}
])
Performer.create!([
  {full_name: "青木 道喜", last_name: "あおき", first_name: "みちよし", style_id: 1},
  {full_name: "浅井 通昭", last_name: "あさい", first_name: "みちあき", style_id: 1},
  {full_name: "浅野 篤義", last_name: "あさの", first_name: "あつよし", style_id: 1},
  {full_name: "井上 裕久", last_name: "いのうえ", first_name: "ひろひさ", style_id: 1},
  {full_name: "井上 和幸", last_name: "いのうえ", first_name: "かずゆき", style_id: 1},
  {full_name: "井上 貴美子", last_name: "いのうえ", first_name: "きみこ", style_id: 1},
  {full_name: "梅田 嘉宏", last_name: "うめだ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦田 保浩", last_name: "うらた", first_name: "やすひろ", style_id: 1},
  {full_name: "浦田 保親", last_name: "うらた", first_name: "やすちか", style_id: 1},
  {full_name: "浦部 好弘", last_name: "うらべ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦部 幸裕", last_name: "うらべ", first_name: "ゆきひろ", style_id: 1},
  {full_name: "大江 又三郎", last_name: "おおえ", first_name: "またさぶろう", style_id: 1},
  {full_name: "大江 信行", last_name: "おおえ", first_name: "のぶゆき", style_id: 1},
  {full_name: "大江 泰正", last_name: "おおえ", first_name: "やすまさ", style_id: 1},
  {full_name: "大江 広祐", last_name: "おおえ", first_name: "こうすけ", style_id: 1},
  {full_name: "大塚 嘉則", last_name: "おおつか", first_name: "よしのり", style_id: 1},
  {full_name: "岡田 すみ子", last_name: "おかだ", first_name: "すみこ", style_id: 1},
  {full_name: "片山 九郎右衛門", last_name: "かたやま", first_name: "くろうえもん", style_id: 1},
  {full_name: "片山 伸吾", last_name: "かたやま", first_name: "しんご", style_id: 1},
  {full_name: "河村 和重", last_name: "かわむら", first_name: "かずしげ", style_id: 1},
  {full_name: "河村 和貴", last_name: "かわむら", first_name: "かずたか", style_id: 1},
  {full_name: "河村 和晃", last_name: "かわむら", first_name: "かずあき", style_id: 1},
  {full_name: "河村 博重", last_name: "かわむら", first_name: "ひろしげ", style_id: 1},
  {full_name: "河村 晴久", last_name: "かわむら", first_name: "はるひさ", style_id: 1},
  {full_name: "河村 晴道", last_name: "かわむら", first_name: "はるみち", style_id: 1},
  {full_name: "河本 望", last_name: "かわもと", first_name: "のぞむ", style_id: 1},
  {full_name: "越賀 隆之", last_name: "こしか", first_name: "たかゆき", style_id: 1},
  {full_name: "小林 慶三", last_name: "こばやし", first_name: "けいぞう", style_id: 1},
  {full_name: "實川 紀", last_name: "じつかわ", first_name: "おさむ", style_id: 1},
  {full_name: "杉浦 豊彦", last_name: "すぎうら", first_name: "とよひこ", style_id: 1},
  {full_name: "武田 欣司", last_name: "たけだ", first_name: "きんじ", style_id: 1},
  {full_name: "武田 邦弘", last_name: "たけだ", first_name: "くにひろ", style_id: 1},
  {full_name: "武田 大志", last_name: "たけだ", first_name: "ひろし", style_id: 1},
  {full_name: "田中 隆夫", last_name: "たなか", first_name: "たかお", style_id: 1},
  {full_name: "田茂井 廣和", last_name: "たもい", first_name: "ひろかず", style_id: 1},
  {full_name: "田茂井 廣道", last_name: "たもい", first_name: "ひろみち", style_id: 1},
  {full_name: "塚本 和雄", last_name: "つかもと", first_name: "かずお", style_id: 1},
  {full_name: "橋本 雅夫", last_name: "はしもと", first_name: "まさお", style_id: 1},
  {full_name: "橋本 光史", last_name: "はしもと", first_name: "こうじ", style_id: 1},
  {full_name: "橋本 磯道", last_name: "はしもと", first_name: "いそみち", style_id: 1},
  {full_name: "橋本 忠樹", last_name: "はしもと", first_name: "ただき", style_id: 1},
  {full_name: "橋本 擴三郎", last_name: "はしもと", first_name: "こうざぶろう", style_id: 1},
  {full_name: "林 喜右衛門", last_name: "はやし", first_name: "きうえもん", style_id: 1},
  {full_name: "林 宗一郎", last_name: "はやし", first_name: "そういちろう", style_id: 1},
  {full_name: "深野 新次郎", last_name: "ふかの", first_name: "しんじろう", style_id: 1},
  {full_name: "深野 貴彦", last_name: "ふかの", first_name: "たかひこ", style_id: 1},
  {full_name: "藤井 千鶴子", last_name: "ふじい", first_name: "ちずこ", style_id: 1},
  {full_name: "古橋 正邦", last_name: "ふるはし", first_name: "まさくに", style_id: 1},
  {full_name: "牧野 和夫", last_name: "まきの", first_name: "かずお", style_id: 1},
  {full_name: "松井 美樹", last_name: "まつい", first_name: "みき", style_id: 1},
  {full_name: "松野 浩行", last_name: "まつの", first_name: "ひろゆき", style_id: 1},
  {full_name: "味方 健", last_name: "みかた", first_name: "けん", style_id: 1},
  {full_name: "味方 玄", last_name: "みかた", first_name: "しずか", style_id: 1},
  {full_name: "味方 團", last_name: "みかた", first_name: "まどか", style_id: 1},
  {full_name: "宮田 宏之", last_name: "みやた", first_name: "ひろゆき", style_id: 1},
  {full_name: "宮本 茂樹", last_name: "みやもと", first_name: "しげき", style_id: 1},
  {full_name: "山田 芙紗子", last_name: "やまだ", first_name: "ふさこ", style_id: 1},
  {full_name: "山田 修司", last_name: "やまだ", first_name: "しゅうじ", style_id: 1},
  {full_name: "吉田 潔司", last_name: "よしだ", first_name: "きよし", style_id: 1},
  {full_name: "吉田 篤史", last_name: "よしだ", first_name: "あつし", style_id: 1},
  {full_name: "吉浪 壽晃", last_name: "よしなみ", first_name: "としあき", style_id: 1},
  {full_name: "分林 道治", last_name: "わけばやし", first_name: "みちはる", style_id: 1},
  {full_name: "鷲尾 周三", last_name: "わしお", first_name: "しゅうぞう", style_id: 1},
  {full_name: "鷲尾 世志子", last_name: "わしお", first_name: "よしこ", style_id: 1},
  {full_name: "石原 昌和", last_name: "いしはら", first_name: "まさかず", style_id: 2},
  {full_name: "上浦 一道", last_name: "うえうら", first_name: "かずみち", style_id: 2},
  {full_name: "植松 洋", last_name: "うえまつ", first_name: "ひろし", style_id: 2},
  {full_name: "岸田 善三郎", last_name: "きしだ", first_name: "ぜんざぶろう", style_id: 2},
  {full_name: "金春 康之", last_name: "こんぱる", first_name: "やすゆき", style_id: 2},
  {full_name: "辻本 實", last_name: "つじもと", first_name: "みのる", style_id: 2},
  {full_name: "南浦 潔", last_name: "みなみうら", first_name: "きよし", style_id: 2},
  {full_name: "今井 清隆", last_name: "いまい", first_name: "きよたか", style_id: 3},
  {full_name: "今井 克紀", last_name: "いまい", first_name: "かつのり", style_id: 3},
  {full_name: "宇髙 通成", last_name: "うたか", first_name: "みちしげ", style_id: 3},
  {full_name: "宇髙 竜成", last_name: "うたか", first_name: "たつしげ", style_id: 3},
  {full_name: "宇髙 徳成", last_name: "うたか", first_name: "のりしげ", style_id: 3},
  {full_name: "漆垣 謙次", last_name: "うるしがき", first_name: "けんじ", style_id: 3},
  {full_name: "小鴨 梨辺華", last_name: "おがも", first_name: "れべっか", style_id: 3},
  {full_name: "小野 芳朗", last_name: "おの", first_name: "よしろう", style_id: 3},
  {full_name: "金剛 龍謹", last_name: "こんごう", first_name: "たつのり", style_id: 3},
  {full_name: "重本 昌也", last_name: "しげもと", first_name: "まさや", style_id: 3},
  {full_name: "嶋崎 暢久", last_name: "しまざき", first_name: "のぶひさ", style_id: 3},
  {full_name: "種田 道一", last_name: "たねだ", first_name: "みちかず", style_id: 3},
  {full_name: "豊島 晃嗣", last_name: "てしま", first_name: "こうじ", style_id: 3},
  {full_name: "豊島 幸洋", last_name: "てしま", first_name: "ゆきひろ", style_id: 3},
  {full_name: "廣田 幸稔", last_name: "ひろた", first_name: "ゆきとし", style_id: 3},
  {full_name: "廣田 泰三", last_name: "ひろた", first_name: "たいぞう", style_id: 3},
  {full_name: "廣田 泰能", last_name: "ひろた", first_name: "やすのり", style_id: 3},
  {full_name: "松野 恭憲", last_name: "まつの", first_name: "やすのり", style_id: 3},
  {full_name: "山田 安造", last_name: "やまだ", first_name: "やすぞう", style_id: 3},
  {full_name: "和田 次夫", last_name: "わだ", first_name: "つぐお", style_id: 3},
  {full_name: "有松 遼一", last_name: "ありまつ", first_name: "りょういち", style_id: 4},
  {full_name: "岡 充", last_name: "おか", first_name: "みつる", style_id: 4},
  {full_name: "久馬 治彦", last_name: "きゅうま", first_name: "はるひこ", style_id: 4},
  {full_name: "小林 努", last_name: "こばやし", first_name: "つとむ", style_id: 4},
  {full_name: "原 大", last_name: "はら", first_name: "まさる", style_id: 4},
  {full_name: "村山 弘", last_name: "むらやま", first_name: "ひろし", style_id: 4},
  {full_name: "左鴻 泰弘", last_name: "さこう", first_name: "やすひろ", style_id: 5},
  {full_name: "杉 市和", last_name: "すぎ", first_name: "いちかず", style_id: 5},
  {full_name: "杉 信太朗", last_name: "すぎ", first_name: "しんたろう", style_id: 5},
  {full_name: "光田 洋一", last_name: "みつだ", first_name: "よういち", style_id: 5},
  {full_name: "森田 保美", last_name: "もりた", first_name: "やすよし", style_id: 5},
  {full_name: "森田 光廣", last_name: "もりた", first_name: "みつひろ", style_id: 5},
  {full_name: "伊吹 吉博", last_name: "いぶき", first_name: "よしひろ", style_id: 6},
  {full_name: "菅 啓好", last_name: "すが", first_name: "", style_id: 6},
  {full_name: "曽和 鼓堂", last_name: "そわ", first_name: "こどう", style_id: 6},
  {full_name: "竹村 英雄", last_name: "たけむら", first_name: "ひでお", style_id: 6},
  {full_name: "竹村 英敏", last_name: "たけむら", first_name: "ひでとし", style_id: 6},
  {full_name: "丹下 紀香", last_name: "たんげ", first_name: "のりか", style_id: 6},
  {full_name: "林 吉兵衛", last_name: "はやし", first_name: "きちべ", style_id: 6},
  {full_name: "林 大和", last_name: "はやし", first_name: "やまと", style_id: 6},
  {full_name: "林 大輝", last_name: "はやし", first_name: "ひろき", style_id: 6},
  {full_name: "吉阪 一郎", last_name: "きちさか", first_name: "いちろう", style_id: 7},
  {full_name: "石井 保彦", last_name: "いしい", first_name: "やすひこ", style_id: 8},
  {full_name: "井林 清一", last_name: "いばやし", first_name: "せいいち", style_id: 8},
  {full_name: "井林 久登", last_name: "いばやし", first_name: "ひさと", style_id: 8},
  {full_name: "河村 大", last_name: "かわむら", first_name: "まさる", style_id: 8},
  {full_name: "武重 正律", last_name: "たけしげ", first_name: "", style_id: 8},
  {full_name: "谷口 正壽", last_name: "たにぐち", first_name: "まさとし", style_id: 8},
  {full_name: "渡部 諭", last_name: "わたなべ", first_name: "さとる", style_id: 8},
  {full_name: "井上 敬介", last_name: "いのうえ", first_name: "けいすけ", style_id: 9},
  {full_name: "前川 光長", last_name: "まえかわ", first_name: "みつなが", style_id: 10},
  {full_name: "前川 光範", last_name: "まえかわ", first_name: "みつのり", style_id: 10},
  {full_name: "前川 雪", last_name: "まえかわ", first_name: "すぐる", style_id: 10},
  {full_name: "網谷 正美", last_name: "あみたに", first_name: "まさよし", style_id: 11},
  {full_name: "安東 伸元", last_name: "あんどう", first_name: "", style_id: 11},
  {full_name: "井口 竜也", last_name: "いぐち", first_name: "たつや", style_id: 11},
  {full_name: "木村 正雄", last_name: "きむら", first_name: "まさお", style_id: 11},
  {full_name: "茂山 千作", last_name: "しげやま", first_name: "せんさく", style_id: 11},
  {full_name: "茂山 千五郎", last_name: "しげやま", first_name: "せんごろう", style_id: 11},
  {full_name: "茂山 茂", last_name: "しげやま", first_name: "しげる", style_id: 11},
  {full_name: "茂山 七五三", last_name: "しげやま", first_name: "しめ", style_id: 11},
  {full_name: "茂山 宗彦", last_name: "しげやま", first_name: "もとひこ", style_id: 11},
  {full_name: "茂山 逸平", last_name: "しげやま", first_name: "いっぺい", style_id: 11},
  {full_name: "茂山 千三郎", last_name: "しげやま", first_name: "せんざぶろう", style_id: 11},
  {full_name: "茂山 あきら", last_name: "しげやま", first_name: "あきら", style_id: 11},
  {full_name: "茂山 良暢", last_name: "しげやま", first_name: "よしのぶ", style_id: 11},
  {full_name: "島田 洋海", last_name: "しまだ", first_name: "ひろみ", style_id: 11},
  {full_name: "鈴木 実", last_name: "すずき", first_name: "みのる", style_id: 11},
  {full_name: "田賀屋 夙", last_name: "たがや", first_name: "なぎさ", style_id: 11},
  {full_name: "古川 道郎", last_name: "ふるかわ", first_name: "みちろう", style_id: 11},
  {full_name: "増田 浩紀", last_name: "ました", first_name: "こうき", style_id: 11},
  {full_name: "松本 薫", last_name: "まつもと", first_name: "かおる", style_id: 11},
  {full_name: "丸石 やすし", last_name: "まるいし", first_name: "やすし", style_id: 11},
  {full_name: "山口 耕道", last_name: "やまぐち", first_name: "こうどう", style_id: 11},
  {full_name: "山下 守之", last_name: "やました", first_name: "もりゆき", style_id: 11}
])
Place.create!([
  {title: "金剛能楽堂", address: "上京区烏丸通一条下る龍前町590", official_url: "http://www.kongou-net.com/"},
  {title: "京都観世会館", address: "左京区岡崎円勝寺町44", official_url: "http://www.kyoto-kanze.jp/"}
])
Program.create!([
  {title: "船弁慶", category: "五番目", location: nil, shimai: true, duration: 45},
  {title: "鷺", category: "四番目", location: nil, shimai: true, duration: 20},
  {title: "卒塔婆小町", category: "三番目", location: nil, shimai: false, duration: 35},
  {title: "芦刈", category: "二番目", location: nil, shimai: true, duration: 50},
  {title: "雲林院", category: "四番目", location: nil, shimai: true, duration: 40},
  {title: "藤", category: "三番目", location: nil, shimai: true, duration: 35},
  {title: "船橋", category: "二番目", location: nil, shimai: true, duration: 40},
  {title: "鵜飼", category: "五番目", location: nil, shimai: true, duration: 28},
  {title: "熊坂", category: "五番目", location: nil, shimai: true, duration: 35},
  {title: "鶴亀", category: "初番目", location: nil, shimai: true, duration: 9},
  {title: "求塚", category: "四番目", location: nil, shimai: true, duration: 60},
  {title: "橋弁慶", category: "四番目", location: nil, shimai: true, duration: 20},
  {title: "鞍馬天狗", category: "五番目", location: nil, shimai: true, duration: 30}
])
Style.create!([
  {title: "シテ方観世流"},
  {title: "シテ方金春流"},
  {title: "シテ方金剛流"},
  {title: "ワキ方高安流"},
  {title: "笛方森田流"},
  {title: "小鼓方幸流"},
  {title: "小鼓方大倉流"},
  {title: "大鼓方石井流"},
  {title: "太鼓方観世流"},
  {title: "太鼓方金春流"},
  {title: "狂言方大蔵流"}
])
Ticket.create!([
  {event_id: 1, grade: "正面・脇正面", price: 8000},
  {event_id: 1, grade: "中正面", price: 5000},
  {event_id: 1, grade: "学生", price: 2500},
  {event_id: 2, grade: "SS席", price: 4500},
  {event_id: 2, grade: "B席", price: 3500},
  {event_id: 3, grade: "特等席", price: 12500},
  {event_id: 3, grade: "親子シート", price: 7000},
  {event_id: 3, grade: "三等席", price: 5000},
  {event_id: 3, grade: "次世代シート", price: 3000},
  {event_id: 4, grade: "前売券", price: 2300},
  {event_id: 4, grade: "当日券", price: 3500},
  {event_id: 5, grade: "S席(正面)", price: 10000},
  {event_id: 5, grade: "A席", price: 8000},
  {event_id: 5, grade: "B席", price: 6000},
  {event_id: 5, grade: "学生", price: 4000}
])
User.create!([
  {name: "例　学士", email: "example@gmail.com", password_digest: "$2a$10$qvVk.OokG0eZU5XyrOnLz.HEv3wIOTi6Ytet66Dm.2rERHMuXP5aS"},
  {name: "例　見習", email: "pupil@gmail.com", password_digest: "$2a$10$DykqVtccO/nQs9sEEudsi.3gmtjU3f6cUkbHyTFFq7vx/B4CI9EnO"},
  {name: "例　師匠", email: "master@gmail.com", password_digest: "$2a$10$vVVfi21agx7wyia39HHGR.pBrRPIZx0eR5RelyyrWOZASv2Z70bUC"}
])
