Event.create!([
  {place_id: 1, title: "第28回　廣田鑑賞会能", start_date: "2017-05-14 13:30:00", end_date: nil, ticket: nil, information: "主役を勤める五流派（観世・宝生・金春・喜多・金剛）をシテ方といいます。\n                     そのシテの相手役を務めるワキ方と、笛・小鼓・大鼓・太鼓を演奏する囃子方、\n                     そして狂言方があります。シテとワキに連れられて出てくる役をツレ・ワキツレと呼びます。", official_url: "http://www.example.com/index.html", user_id: 1, published: true},
  {place_id: 2, title: "京都観世会5月例会", start_date: "2017-05-28 11:00:00", end_date: nil, ticket: nil, information: "", official_url: "http://www.kanzei.com/5th-kai.html", user_id: 1, published: true},
  {place_id: 1, title: "金剛定期能", start_date: "2017-05-31 13:20:00", end_date: nil, ticket: nil, information: "平成29年度の金剛定期能は年10回公演となります。\n                     毎月、宗家以下総出演で佳曲を揃えました。 また上演前に演目の解説も行います。\n                     29年度も多くの皆様にご鑑賞願いたく、絶大のご後援を賜ります様宜しくお願い申し上げます。\n                     皆様のご入会を心よりお待ち申し上げております。\n                     なお4月は特別公演として東本願寺能舞台にて開催いたします。", official_url: "http://www.example.com/regular.html", user_id: 2, published: true},
  {place_id: 2, title: "市民狂言会", start_date: "2017-06-09 19:00:00", end_date: nil, ticket: nil, information: "KAC　Performing　Arts　Program　/　Contemporary　Danceでは、\n                     京都芸術センターの創作環境を活かし、コンテンポラリーダンス表現の最前線で活躍する\n                     振付家・ダンサーを迎えて新作の創作・上演および旧作の再創作を行う。", official_url: "http://www.kac.or.jp/program/9443/", user_id: 3, published: true},
  {place_id: 2, title: "独立25周年記念 第16回 吉浪壽晃 能の会", start_date: "2017-06-11 13:30:00", end_date: nil, ticket: nil, information: "", official_url: "http://www.ecample.com/noh-no-kai.html", user_id: 1, published: true},
  {place_id: 1, title: "県民のための能を知る会", start_date: "2017-06-25 16:00:00", end_date: nil, ticket: nil, information: "", official_url: "http://www.nohbutai.com/", user_id: 2, published: true},
  {place_id: 6, title: "金春会定期能", start_date: "2017-07-01 17:00:00", end_date: nil, ticket: nil, information: "", official_url: "", user_id: 1, published: true},
  {place_id: 10, title: "演能の会　高崎公演　レクチャー", start_date: "2017-07-08 11:20:00", end_date: nil, ticket: nil, information: "当社（難波八阪神社）の創建年月日など詳しい資料は残っていませんが、社伝によれば古来「\n                     難波下の宮」と称し難波一帯の産土神でした。後三条天皇の延久（1069年から1073年）の頃から祇園牛頭天王（ごずてんのう）を\n                     お祀りする古社として世間に知られていました。\n　                   もとは神仏混淆でしたが、維新後、神仏分離により寺は廃絶し、明治5年(1872年)に郷社となりました。\n                     現在のご本殿は、昭和49年（1974年）5月に完成。\n　                   毎年１月の第３日曜日に行われている綱引神事は当社の御祭神、素盞嗚尊（すさのをのみこと）が八岐大蛇（やまたのおろち）を退治し、\n                     民衆の困苦を除かれた故事に基づき始められたと言われています。「摂津名所図絵」や「摂津名所図会大成」にも紹介されています。また、平成13年(2001年)には、大阪市で初めての無形民俗文化財に指定されました。", official_url: "http://www.takasaki-foundation.or.jp/gallery/moyoosi.html", user_id: 2, published: true},
  {place_id: 1, title: "志の輔らくご at NOH THEATER", start_date: "2017-07-11 13:30:00", end_date: nil, ticket: nil, information: "銀座六丁目に居を移し、新たな歴史を刻み始めた観世能楽堂で初の落語会を銀座花鏡開幕記念公演としてお届けします。\n                     日本の伝統文化の真髄を伝える劇場で、立川志の輔による新たな幕が開きます。\n                     志の輔らくごで、こころ揺さぶられるひとときをお楽しみください。", official_url: "", user_id: 3, published: true},
  {place_id: 24, title: "シア能楽公演 金剛流による能「羽衣」を上演「樂―茶碗の中の宇宙展」開催記念", start_date: "2017-07-25 13:30:00", end_date: nil, ticket: nil, information: "650 年の歴史を持つ能楽界において五流のうち四流の宗家が東京を本拠地とする中で、京都に宗家が存在する唯一の流儀である金剛流。\n                     サンクトペテルブルクの公演では 、二十六世宗家・金剛永謹師の監修・出演による 「羽衣」をはじめ、重厚かつ華やかな舞台を披露し 、\n                     日本が誇る伝統芸能の魅力をお届けします。", official_url: "", user_id: 3, published: true},
  {place_id: 1, title: "お豆腐の和らい「都の賑わい」京都公演", start_date: "2017-07-30 09:10:00", end_date: nil, ticket: nil, information: "毎年恒例の、茂山千五郎家・クラブSOJA企画のお楽しみ狂言会「お豆腐の和らい（わらい）」\n                     今年は「都の賑わい」と題しまして、茂山千五郎家が本家を構える京都にまつわる三演目を上演致します。\n                     色鮮やかな変化に富んだ都の面白さ、可笑しさをどうぞお楽しみくださいませ。", official_url: "http://kyotokyogen.com/schedule/20170505waraikyoto/", user_id: 2, published: true},
  {place_id: 2, title: "水無月狂言の集い", start_date: "2017-08-03 21:30:00", end_date: nil, ticket: nil, information: "", official_url: "http://kyotokyogen.com/schedule/20170624minazuki/", user_id: 1, published: true},
  {place_id: 90, title: "伝統芸能　狂言を楽しむ会", start_date: "2017-08-04 09:30:00", end_date: nil, ticket: nil, information: "", official_url: "http://kyotokyogen.com/schedule/20170709kagoshima/", user_id: 1, published: true},
  {place_id: 2, title: "第2回加西能", start_date: "2017-08-13 13:15:00", end_date: nil, ticket: nil, information: "新作能『針間」は哲学者梅原猛さんの書き下ろしによるもので、2人の皇子（意奚と袁奚）が\n                     皇位継承争いの続く都から志染の里（現三木市）に逃れて、それぞれ牛飼いと馬飼いになり、\n                     後に都で仁賢天皇と顕宗天皇になった話を描いています。\n                     『高砂』には観世銕之丞さんら、『針間』には人間国宝の大槻文蔵さんら能楽師の一線級がそろい、\n                     観客らは美しい舞に酔いしれ、延べ約1時間半の上演が終わると、会場は大きな拍手に包まれた。\n                     大槻さんは「（2年前と比べて）今回はホールだったので凝縮した感じで一体感があった。また機会があれば演じたい」と話されました。", official_url: "http://www.fudoki1300.city.kasai.hyogo.jp/nou/kasainou2/", user_id: 3, published: true},
  {place_id: 2, title: "井上同門定期能楽会", start_date: "2017-08-13 19:30:00", end_date: nil, ticket: nil, information: "当初、「薪御能」は、舞台が野外の芝生であったため、紙を敷き踏んで芝の状態を見たとされています。\n                     現在は、敷き舞台の上で行う為、その必要はありませんが、芝の湿り具合いで能のあるなしを決めていたことを今に伝えるため、\n                     演能の前に興福寺衆徒（僧兵）により「舞台あらため」が行われます。\n                     また、その結果を人々に伝えるために「外僉義（げのせんぎ）」文が読み上げられます。\n                     外僉義文は、寺の外部の人達に向けて僉義を発表するものです。\n                     これらの儀式は他では見ることのできない「薪御能」だけの特色です。", official_url: "https://narashikanko.or.jp/event/takigiono/", user_id: 2, published: true},
  {place_id: 12, title: "大槻能楽堂自主公演能　能の魅力を探るシリーズ－能と和歌－", start_date: "2017-08-24 11:00:00", end_date: nil, ticket: nil, information: "", official_url: "http://www.noh-kyogen.com/schedule/2017/05.html", user_id: 2, published: true},
  {place_id: 1, title: "第二回 風の能", start_date: "2017-09-01 12:15:00", end_date: nil, ticket: nil, information: "", official_url: "http://www.susumushingu.com/news.shtml", user_id: 1, published: true},
  {place_id: 210, title: "おうみ狂言図鑑 2017", start_date: "2017-09-03 13:00:00", end_date: nil, ticket: nil, information: "ニンジャカジャと大名、そしてちょっとタロウカジャ", official_url: "", user_id: 1, published: true},
  {place_id: 17, title: "財団設立20周年記念　第209回公演　いばらき能「安達原」", start_date: "2017-09-05 13:40:00", end_date: nil, ticket: nil, information: "解説つきで能の全曲をお楽しみいただける「いばらき能」。\n                     昨年度の「葵上」に続き、鬼女をテーマとした能「安達原」をお送りします。", official_url: "http://www.ibabun.jp/eventLeaf.php?eid=00267", user_id: 3, published: true},
  {place_id: 19, title: "河村定期研能会", start_date: "2017-09-20 10:10:00", end_date: nil, ticket: nil, information: "※ゆかた（その他和装）でお越しの方を対象に7月25日「天神祭能船」の乗船券など豪華景品が当たる抽選会をご用意しています！ ", official_url: "", user_id: 2, published: true}
])
EventPerformer.create!([
  {event_program_id: 1, performer_id: 52},
  {event_program_id: 2, performer_id: 35},
  {event_program_id: 2, performer_id: 45},
  {event_program_id: 3, performer_id: 79},
  {event_program_id: 4, performer_id: 142},
  {event_program_id: 4, performer_id: 75},
  {event_program_id: 5, performer_id: 44},
  {event_program_id: 6, performer_id: 48},
  {event_program_id: 7, performer_id: 70},
  {event_program_id: 7, performer_id: 38},
  {event_program_id: 7, performer_id: 52},
  {event_program_id: 8, performer_id: 70},
  {event_program_id: 9, performer_id: 73},
  {event_program_id: 9, performer_id: 19},
  {event_program_id: 9, performer_id: 112},
  {event_program_id: 10, performer_id: 145},
  {event_program_id: 10, performer_id: 74},
  {event_program_id: 11, performer_id: 139},
  {event_program_id: 12, performer_id: 131},
  {event_program_id: 12, performer_id: 85},
  {event_program_id: 13, performer_id: 108},
  {event_program_id: 14, performer_id: 113},
  {event_program_id: 15, performer_id: 119},
  {event_program_id: 15, performer_id: 56},
  {event_program_id: 16, performer_id: 83},
  {event_program_id: 16, performer_id: 139},
  {event_program_id: 17, performer_id: 63},
  {event_program_id: 18, performer_id: 139},
  {event_program_id: 18, performer_id: 89},
  {event_program_id: 19, performer_id: 63},
  {event_program_id: 19, performer_id: 37},
  {event_program_id: 19, performer_id: 56},
  {event_program_id: 20, performer_id: 29},
  {event_program_id: 20, performer_id: 113},
  {event_program_id: 20, performer_id: 112},
  {event_program_id: 21, performer_id: 111},
  {event_program_id: 21, performer_id: 29},
  {event_program_id: 22, performer_id: 55},
  {event_program_id: 22, performer_id: 39},
  {event_program_id: 23, performer_id: 76},
  {event_program_id: 23, performer_id: 144},
  {event_program_id: 24, performer_id: 18},
  {event_program_id: 25, performer_id: 106},
  {event_program_id: 26, performer_id: 24},
  {event_program_id: 26, performer_id: 84},
  {event_program_id: 26, performer_id: 135},
  {event_program_id: 27, performer_id: 52},
  {event_program_id: 27, performer_id: 98},
  {event_program_id: 27, performer_id: 6},
  {event_program_id: 28, performer_id: 69},
  {event_program_id: 28, performer_id: 22},
  {event_program_id: 28, performer_id: 67},
  {event_program_id: 29, performer_id: 65},
  {event_program_id: 29, performer_id: 67},
  {event_program_id: 29, performer_id: 73},
  {event_program_id: 30, performer_id: 68},
  {event_program_id: 30, performer_id: 123},
  {event_program_id: 31, performer_id: 11},
  {event_program_id: 31, performer_id: 29},
  {event_program_id: 32, performer_id: 12},
  {event_program_id: 32, performer_id: 30},
  {event_program_id: 32, performer_id: 8},
  {event_program_id: 33, performer_id: 14},
  {event_program_id: 33, performer_id: 38},
  {event_program_id: 33, performer_id: 9},
  {event_program_id: 34, performer_id: 87},
  {event_program_id: 35, performer_id: 92},
  {event_program_id: 35, performer_id: 58},
  {event_program_id: 35, performer_id: 8},
  {event_program_id: 36, performer_id: 95},
  {event_program_id: 36, performer_id: 47},
  {event_program_id: 36, performer_id: 16},
  {event_program_id: 37, performer_id: 108},
  {event_program_id: 37, performer_id: 133},
  {event_program_id: 37, performer_id: 12},
  {event_program_id: 38, performer_id: 29},
  {event_program_id: 38, performer_id: 6},
  {event_program_id: 39, performer_id: 135},
  {event_program_id: 39, performer_id: 123},
  {event_program_id: 40, performer_id: 53},
  {event_program_id: 40, performer_id: 57},
  {event_program_id: 40, performer_id: 9},
  {event_program_id: 41, performer_id: 46},
  {event_program_id: 42, performer_id: 11},
  {event_program_id: 42, performer_id: 128},
  {event_program_id: 43, performer_id: 117},
  {event_program_id: 43, performer_id: 135},
  {event_program_id: 43, performer_id: 87},
  {event_program_id: 44, performer_id: 142},
  {event_program_id: 45, performer_id: 58},
  {event_program_id: 45, performer_id: 19},
  {event_program_id: 45, performer_id: 41},
  {event_program_id: 46, performer_id: 37},
  {event_program_id: 46, performer_id: 128},
  {event_program_id: 47, performer_id: 38},
  {event_program_id: 47, performer_id: 64},
  {event_program_id: 47, performer_id: 118},
  {event_program_id: 48, performer_id: 76},
  {event_program_id: 48, performer_id: 30},
  {event_program_id: 48, performer_id: 4},
  {event_program_id: 49, performer_id: 133},
  {event_program_id: 50, performer_id: 2},
  {event_program_id: 51, performer_id: 64},
  {event_program_id: 52, performer_id: 54},
  {event_program_id: 52, performer_id: 1},
  {event_program_id: 53, performer_id: 113},
  {event_program_id: 54, performer_id: 27},
  {event_program_id: 54, performer_id: 61},
  {event_program_id: 54, performer_id: 8},
  {event_program_id: 55, performer_id: 121},
  {event_program_id: 56, performer_id: 16},
  {event_program_id: 57, performer_id: 99},
  {event_program_id: 57, performer_id: 91},
  {event_program_id: 57, performer_id: 122},
  {event_program_id: 58, performer_id: 119},
  {event_program_id: 59, performer_id: 51},
  {event_program_id: 59, performer_id: 75},
  {event_program_id: 60, performer_id: 70},
  {event_program_id: 60, performer_id: 135},
  {event_program_id: 60, performer_id: 59},
  {event_program_id: 61, performer_id: 117},
  {event_program_id: 61, performer_id: 27},
  {event_program_id: 62, performer_id: 2},
  {event_program_id: 63, performer_id: 68},
  {event_program_id: 64, performer_id: 125}
])
EventProgram.create!([
  {event_id: 1, program_id: 204, style: "観世流", genre: "能"},
  {event_id: 1, program_id: 95, style: "金剛流", genre: "舞囃子"},
  {event_id: 2, program_id: 3, style: "大蔵流", genre: "舞囃子"},
  {event_id: 2, program_id: 227, style: "観世流", genre: "能"},
  {event_id: 2, program_id: 96, style: "大蔵流", genre: "能"},
  {event_id: 2, program_id: 27, style: "大蔵流", genre: "舞囃子"},
  {event_id: 3, program_id: 168, style: "大蔵流", genre: "狂言"},
  {event_id: 3, program_id: 16, style: "大蔵流", genre: "狂言"},
  {event_id: 3, program_id: 167, style: "金剛流", genre: "狂言"},
  {event_id: 3, program_id: 242, style: "観世流", genre: "能"},
  {event_id: 4, program_id: 30, style: "金剛流", genre: "舞囃子"},
  {event_id: 4, program_id: 111, style: "観世流", genre: "狂言"},
  {event_id: 4, program_id: 173, style: "金剛流", genre: "能"},
  {event_id: 5, program_id: 138, style: "大蔵流", genre: "舞囃子"},
  {event_id: 5, program_id: 143, style: "観世流", genre: "能"},
  {event_id: 6, program_id: 164, style: "大蔵流", genre: "狂言"},
  {event_id: 6, program_id: 205, style: "金剛流", genre: "狂言"},
  {event_id: 6, program_id: 171, style: "大蔵流", genre: "狂言"},
  {event_id: 7, program_id: 214, style: "大蔵流", genre: "能"},
  {event_id: 7, program_id: 111, style: "大蔵流", genre: "舞囃子"},
  {event_id: 8, program_id: 63, style: "大蔵流", genre: "舞囃子"},
  {event_id: 8, program_id: 63, style: "大蔵流", genre: "狂言"},
  {event_id: 8, program_id: 109, style: "大蔵流", genre: "舞囃子"},
  {event_id: 8, program_id: 183, style: "金剛流", genre: "能"},
  {event_id: 9, program_id: 243, style: "金剛流", genre: "狂言"},
  {event_id: 9, program_id: 58, style: "大蔵流", genre: "舞囃子"},
  {event_id: 9, program_id: 62, style: "観世流", genre: "狂言"},
  {event_id: 10, program_id: 205, style: "金剛流", genre: "舞囃子"},
  {event_id: 10, program_id: 163, style: "大蔵流", genre: "狂言"},
  {event_id: 11, program_id: 137, style: "大蔵流", genre: "舞囃子"},
  {event_id: 11, program_id: 17, style: "金剛流", genre: "能"},
  {event_id: 11, program_id: 118, style: "金剛流", genre: "舞囃子"},
  {event_id: 12, program_id: 173, style: "金剛流", genre: "狂言"},
  {event_id: 12, program_id: 167, style: "大蔵流", genre: "狂言"},
  {event_id: 12, program_id: 123, style: "観世流", genre: "能"},
  {event_id: 13, program_id: 85, style: "観世流", genre: "能"},
  {event_id: 13, program_id: 200, style: "金剛流", genre: "狂言"},
  {event_id: 13, program_id: 101, style: "金剛流", genre: "能"},
  {event_id: 13, program_id: 145, style: "観世流", genre: "舞囃子"},
  {event_id: 14, program_id: 99, style: "金剛流", genre: "狂言"},
  {event_id: 14, program_id: 21, style: "金剛流", genre: "狂言"},
  {event_id: 15, program_id: 79, style: "大蔵流", genre: "舞囃子"},
  {event_id: 15, program_id: 94, style: "大蔵流", genre: "能"},
  {event_id: 15, program_id: 233, style: "大蔵流", genre: "狂言"},
  {event_id: 15, program_id: 174, style: "大蔵流", genre: "舞囃子"},
  {event_id: 16, program_id: 183, style: "観世流", genre: "狂言"},
  {event_id: 16, program_id: 170, style: "金剛流", genre: "舞囃子"},
  {event_id: 16, program_id: 243, style: "大蔵流", genre: "能"},
  {event_id: 16, program_id: 193, style: "大蔵流", genre: "能"},
  {event_id: 17, program_id: 114, style: "観世流", genre: "狂言"},
  {event_id: 17, program_id: 176, style: "大蔵流", genre: "狂言"},
  {event_id: 18, program_id: 31, style: "大蔵流", genre: "舞囃子"},
  {event_id: 18, program_id: 151, style: "大蔵流", genre: "狂言"},
  {event_id: 18, program_id: 209, style: "観世流", genre: "能"},
  {event_id: 18, program_id: 201, style: "大蔵流", genre: "能"},
  {event_id: 19, program_id: 63, style: "大蔵流", genre: "能"},
  {event_id: 19, program_id: 26, style: "金剛流", genre: "能"},
  {event_id: 19, program_id: 50, style: "観世流", genre: "狂言"},
  {event_id: 19, program_id: 189, style: "金剛流", genre: "舞囃子"},
  {event_id: 20, program_id: 129, style: "金剛流", genre: "舞囃子"},
  {event_id: 20, program_id: 221, style: "観世流", genre: "舞囃子"},
  {event_id: 20, program_id: 133, style: "大蔵流", genre: "能"},
  {event_id: 20, program_id: 27, style: "観世流", genre: "狂言"},
  {event_id: 20, program_id: 102, style: "金剛流", genre: "能"}
])
Performer.create!([
  {full_name: "青木 道喜", last_name: "あおき", first_name: "みちよし", style_id: 1},
  {full_name: "浅井 通昭", last_name: "あさい", first_name: "みちあき", style_id: 1},
  {full_name: "浅野 篤義", last_name: "あさの", first_name: "あつよし", style_id: 1},
  {full_name: "井上 裕久", last_name: "いのうえ", first_name: "ひろひさ", style_id: 1},
  {full_name: "井上 和幸", last_name: "いのうえ", first_name: "かずゆき", style_id: 1},
  {full_name: "井上 貴美子", last_name: "いのうえ", first_name: "きみこ", style_id: 1},
  {full_name: "梅田 嘉宏", last_name: "うめだ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦田 保浩", last_name: "うらた", first_name: "やすひろ", style_id: 1},
  {full_name: "浦田 保親", last_name: "うらた", first_name: "やすちか", style_id: 1},
  {full_name: "浦部 好弘", last_name: "うらべ", first_name: "よしひろ", style_id: 1},
  {full_name: "浦部 幸裕", last_name: "うらべ", first_name: "ゆきひろ", style_id: 1},
  {full_name: "大江 又三郎", last_name: "おおえ", first_name: "またさぶろう", style_id: 1},
  {full_name: "大江 信行", last_name: "おおえ", first_name: "のぶゆき", style_id: 1},
  {full_name: "大江 泰正", last_name: "おおえ", first_name: "やすまさ", style_id: 1},
  {full_name: "大江 広祐", last_name: "おおえ", first_name: "こうすけ", style_id: 1},
  {full_name: "大塚 嘉則", last_name: "おおつか", first_name: "よしのり", style_id: 1},
  {full_name: "岡田 すみ子", last_name: "おかだ", first_name: "すみこ", style_id: 1},
  {full_name: "片山 九郎右衛門", last_name: "かたやま", first_name: "くろうえもん", style_id: 1},
  {full_name: "片山 伸吾", last_name: "かたやま", first_name: "しんご", style_id: 1},
  {full_name: "河村 和重", last_name: "かわむら", first_name: "かずしげ", style_id: 1},
  {full_name: "河村 和貴", last_name: "かわむら", first_name: "かずたか", style_id: 1},
  {full_name: "河村 和晃", last_name: "かわむら", first_name: "かずあき", style_id: 1},
  {full_name: "河村 博重", last_name: "かわむら", first_name: "ひろしげ", style_id: 1},
  {full_name: "河村 晴久", last_name: "かわむら", first_name: "はるひさ", style_id: 1},
  {full_name: "河村 晴道", last_name: "かわむら", first_name: "はるみち", style_id: 1},
  {full_name: "河本 望", last_name: "かわもと", first_name: "のぞむ", style_id: 1},
  {full_name: "越賀 隆之", last_name: "こしか", first_name: "たかゆき", style_id: 1},
  {full_name: "小林 慶三", last_name: "こばやし", first_name: "けいぞう", style_id: 1},
  {full_name: "實川 紀", last_name: "じつかわ", first_name: "おさむ", style_id: 1},
  {full_name: "杉浦 豊彦", last_name: "すぎうら", first_name: "とよひこ", style_id: 1},
  {full_name: "武田 欣司", last_name: "たけだ", first_name: "きんじ", style_id: 1},
  {full_name: "武田 邦弘", last_name: "たけだ", first_name: "くにひろ", style_id: 1},
  {full_name: "武田 大志", last_name: "たけだ", first_name: "ひろし", style_id: 1},
  {full_name: "田中 隆夫", last_name: "たなか", first_name: "たかお", style_id: 1},
  {full_name: "田茂井 廣和", last_name: "たもい", first_name: "ひろかず", style_id: 1},
  {full_name: "田茂井 廣道", last_name: "たもい", first_name: "ひろみち", style_id: 1},
  {full_name: "塚本 和雄", last_name: "つかもと", first_name: "かずお", style_id: 1},
  {full_name: "橋本 雅夫", last_name: "はしもと", first_name: "まさお", style_id: 1},
  {full_name: "橋本 光史", last_name: "はしもと", first_name: "こうじ", style_id: 1},
  {full_name: "橋本 磯道", last_name: "はしもと", first_name: "いそみち", style_id: 1},
  {full_name: "橋本 忠樹", last_name: "はしもと", first_name: "ただき", style_id: 1},
  {full_name: "橋本 擴三郎", last_name: "はしもと", first_name: "こうざぶろう", style_id: 1},
  {full_name: "林 喜右衛門", last_name: "はやし", first_name: "きうえもん", style_id: 1},
  {full_name: "林 宗一郎", last_name: "はやし", first_name: "そういちろう", style_id: 1},
  {full_name: "深野 新次郎", last_name: "ふかの", first_name: "しんじろう", style_id: 1},
  {full_name: "深野 貴彦", last_name: "ふかの", first_name: "たかひこ", style_id: 1},
  {full_name: "藤井 千鶴子", last_name: "ふじい", first_name: "ちずこ", style_id: 1},
  {full_name: "古橋 正邦", last_name: "ふるはし", first_name: "まさくに", style_id: 1},
  {full_name: "牧野 和夫", last_name: "まきの", first_name: "かずお", style_id: 1},
  {full_name: "松井 美樹", last_name: "まつい", first_name: "みき", style_id: 1},
  {full_name: "松野 浩行", last_name: "まつの", first_name: "ひろゆき", style_id: 1},
  {full_name: "味方 健", last_name: "みかた", first_name: "けん", style_id: 1},
  {full_name: "味方 玄", last_name: "みかた", first_name: "しずか", style_id: 1},
  {full_name: "味方 團", last_name: "みかた", first_name: "まどか", style_id: 1},
  {full_name: "宮田 宏之", last_name: "みやた", first_name: "ひろゆき", style_id: 1},
  {full_name: "宮本 茂樹", last_name: "みやもと", first_name: "しげき", style_id: 1},
  {full_name: "山田 芙紗子", last_name: "やまだ", first_name: "ふさこ", style_id: 1},
  {full_name: "山田 修司", last_name: "やまだ", first_name: "しゅうじ", style_id: 1},
  {full_name: "吉田 潔司", last_name: "よしだ", first_name: "きよし", style_id: 1},
  {full_name: "吉田 篤史", last_name: "よしだ", first_name: "あつし", style_id: 1},
  {full_name: "吉浪 壽晃", last_name: "よしなみ", first_name: "としあき", style_id: 1},
  {full_name: "分林 道治", last_name: "わけばやし", first_name: "みちはる", style_id: 1},
  {full_name: "鷲尾 周三", last_name: "わしお", first_name: "しゅうぞう", style_id: 1},
  {full_name: "鷲尾 世志子", last_name: "わしお", first_name: "よしこ", style_id: 1},
  {full_name: "石原 昌和", last_name: "いしはら", first_name: "まさかず", style_id: 2},
  {full_name: "上浦 一道", last_name: "うえうら", first_name: "かずみち", style_id: 2},
  {full_name: "植松 洋", last_name: "うえまつ", first_name: "ひろし", style_id: 2},
  {full_name: "岸田 善三郎", last_name: "きしだ", first_name: "ぜんざぶろう", style_id: 2},
  {full_name: "金春 康之", last_name: "こんぱる", first_name: "やすゆき", style_id: 2},
  {full_name: "辻本 實", last_name: "つじもと", first_name: "みのる", style_id: 2},
  {full_name: "南浦 潔", last_name: "みなみうら", first_name: "きよし", style_id: 2},
  {full_name: "今井 清隆", last_name: "いまい", first_name: "きよたか", style_id: 3},
  {full_name: "今井 克紀", last_name: "いまい", first_name: "かつのり", style_id: 3},
  {full_name: "宇髙 通成", last_name: "うたか", first_name: "みちしげ", style_id: 3},
  {full_name: "宇髙 竜成", last_name: "うたか", first_name: "たつしげ", style_id: 3},
  {full_name: "宇髙 徳成", last_name: "うたか", first_name: "のりしげ", style_id: 3},
  {full_name: "漆垣 謙次", last_name: "うるしがき", first_name: "けんじ", style_id: 3},
  {full_name: "小鴨 梨辺華", last_name: "おがも", first_name: "れべっか", style_id: 3},
  {full_name: "小野 芳朗", last_name: "おの", first_name: "よしろう", style_id: 3},
  {full_name: "金剛 龍謹", last_name: "こんごう", first_name: "たつのり", style_id: 3},
  {full_name: "重本 昌也", last_name: "しげもと", first_name: "まさや", style_id: 3},
  {full_name: "嶋崎 暢久", last_name: "しまざき", first_name: "のぶひさ", style_id: 3},
  {full_name: "種田 道一", last_name: "たねだ", first_name: "みちかず", style_id: 3},
  {full_name: "豊島 晃嗣", last_name: "てしま", first_name: "こうじ", style_id: 3},
  {full_name: "豊島 幸洋", last_name: "てしま", first_name: "ゆきひろ", style_id: 3},
  {full_name: "廣田 幸稔", last_name: "ひろた", first_name: "ゆきとし", style_id: 3},
  {full_name: "廣田 泰三", last_name: "ひろた", first_name: "たいぞう", style_id: 3},
  {full_name: "廣田 泰能", last_name: "ひろた", first_name: "やすのり", style_id: 3},
  {full_name: "松野 恭憲", last_name: "まつの", first_name: "やすのり", style_id: 3},
  {full_name: "山田 安造", last_name: "やまだ", first_name: "やすぞう", style_id: 3},
  {full_name: "和田 次夫", last_name: "わだ", first_name: "つぐお", style_id: 3},
  {full_name: "有松 遼一", last_name: "ありまつ", first_name: "りょういち", style_id: 4},
  {full_name: "岡 充", last_name: "おか", first_name: "みつる", style_id: 4},
  {full_name: "久馬 治彦", last_name: "きゅうま", first_name: "はるひこ", style_id: 4},
  {full_name: "小林 努", last_name: "こばやし", first_name: "つとむ", style_id: 4},
  {full_name: "原 大", last_name: "はら", first_name: "まさる", style_id: 4},
  {full_name: "村山 弘", last_name: "むらやま", first_name: "ひろし", style_id: 4},
  {full_name: "左鴻 泰弘", last_name: "さこう", first_name: "やすひろ", style_id: 5},
  {full_name: "杉 市和", last_name: "すぎ", first_name: "いちかず", style_id: 5},
  {full_name: "杉 信太朗", last_name: "すぎ", first_name: "しんたろう", style_id: 5},
  {full_name: "光田 洋一", last_name: "みつだ", first_name: "よういち", style_id: 5},
  {full_name: "森田 保美", last_name: "もりた", first_name: "やすよし", style_id: 5},
  {full_name: "森田 光廣", last_name: "もりた", first_name: "みつひろ", style_id: 5},
  {full_name: "伊吹 吉博", last_name: "いぶき", first_name: "よしひろ", style_id: 6},
  {full_name: "菅 啓好", last_name: "すが", first_name: "", style_id: 6},
  {full_name: "曽和 鼓堂", last_name: "そわ", first_name: "こどう", style_id: 6},
  {full_name: "竹村 英雄", last_name: "たけむら", first_name: "ひでお", style_id: 6},
  {full_name: "竹村 英敏", last_name: "たけむら", first_name: "ひでとし", style_id: 6},
  {full_name: "丹下 紀香", last_name: "たんげ", first_name: "のりか", style_id: 6},
  {full_name: "林 吉兵衛", last_name: "はやし", first_name: "きちべ", style_id: 6},
  {full_name: "林 大和", last_name: "はやし", first_name: "やまと", style_id: 6},
  {full_name: "林 大輝", last_name: "はやし", first_name: "ひろき", style_id: 6},
  {full_name: "吉阪 一郎", last_name: "きちさか", first_name: "いちろう", style_id: 7},
  {full_name: "石井 保彦", last_name: "いしい", first_name: "やすひこ", style_id: 8},
  {full_name: "井林 清一", last_name: "いばやし", first_name: "せいいち", style_id: 8},
  {full_name: "井林 久登", last_name: "いばやし", first_name: "ひさと", style_id: 8},
  {full_name: "河村 大", last_name: "かわむら", first_name: "まさる", style_id: 8},
  {full_name: "武重 正律", last_name: "たけしげ", first_name: "", style_id: 8},
  {full_name: "谷口 正壽", last_name: "たにぐち", first_name: "まさとし", style_id: 8},
  {full_name: "渡部 諭", last_name: "わたなべ", first_name: "さとる", style_id: 8},
  {full_name: "井上 敬介", last_name: "いのうえ", first_name: "けいすけ", style_id: 9},
  {full_name: "前川 光長", last_name: "まえかわ", first_name: "みつなが", style_id: 10},
  {full_name: "前川 光範", last_name: "まえかわ", first_name: "みつのり", style_id: 10},
  {full_name: "前川 雪", last_name: "まえかわ", first_name: "すぐる", style_id: 10},
  {full_name: "網谷 正美", last_name: "あみたに", first_name: "まさよし", style_id: 11},
  {full_name: "安東 伸元", last_name: "あんどう", first_name: "", style_id: 11},
  {full_name: "井口 竜也", last_name: "いぐち", first_name: "たつや", style_id: 11},
  {full_name: "木村 正雄", last_name: "きむら", first_name: "まさお", style_id: 11},
  {full_name: "茂山 千作", last_name: "しげやま", first_name: "せんさく", style_id: 11},
  {full_name: "茂山 千五郎", last_name: "しげやま", first_name: "せんごろう", style_id: 11},
  {full_name: "茂山 茂", last_name: "しげやま", first_name: "しげる", style_id: 11},
  {full_name: "茂山 七五三", last_name: "しげやま", first_name: "しめ", style_id: 11},
  {full_name: "茂山 宗彦", last_name: "しげやま", first_name: "もとひこ", style_id: 11},
  {full_name: "茂山 逸平", last_name: "しげやま", first_name: "いっぺい", style_id: 11},
  {full_name: "茂山 千三郎", last_name: "しげやま", first_name: "せんざぶろう", style_id: 11},
  {full_name: "茂山 あきら", last_name: "しげやま", first_name: "あきら", style_id: 11},
  {full_name: "茂山 良暢", last_name: "しげやま", first_name: "よしのぶ", style_id: 11},
  {full_name: "島田 洋海", last_name: "しまだ", first_name: "ひろみ", style_id: 11},
  {full_name: "鈴木 実", last_name: "すずき", first_name: "みのる", style_id: 11},
  {full_name: "田賀屋 夙", last_name: "たがや", first_name: "なぎさ", style_id: 11},
  {full_name: "古川 道郎", last_name: "ふるかわ", first_name: "みちろう", style_id: 11},
  {full_name: "増田 浩紀", last_name: "ました", first_name: "こうき", style_id: 11},
  {full_name: "松本 薫", last_name: "まつもと", first_name: "かおる", style_id: 11},
  {full_name: "丸石 やすし", last_name: "まるいし", first_name: "やすし", style_id: 11},
  {full_name: "山口 耕道", last_name: "やまぐち", first_name: "こうどう", style_id: 11},
  {full_name: "山下 守之", last_name: "やました", first_name: "もりゆき", style_id: 11}
])
Place.create!([
  {title: "六角堂頂法寺", address: "日本, 〒604-8134 京都府京都市中京区六角通東洞院西入堂之前町", official_url: "http://www.ikenobo.jp/rokkakudo"},
  {title: "革堂行願寺", address: "日本, 〒604-0991 京都府京都市中京区行願寺門前町 寺町通竹屋町上る行願寺門前町17", official_url: nil},
  {title: "壬生寺", address: "日本, 〒604-8821 京都府京都市中京区中京区壬生梛ノ宮町３１", official_url: "http://www.mibudera.com/"},
  {title: "本能寺", address: "日本, 〒604-8243 京都府京都市中京区本能寺町", official_url: nil},
  {title: "大報恩寺", address: "日本, 〒602-8319 京都府京都市上京区溝前町 七本松通今出川上ル溝前町1034番地", official_url: "http://www.daihoonji.com/"},
  {title: "清浄華院", address: "日本, 〒602-0852 京都府京都市上京区北之辺町 京都府京都市上京区寺町通広小路上る北之辺町395", official_url: "http://www.jozan.jp/"},
  {title: "相国寺", address: "日本, 〒602-0898 京都府京都市上京区相国寺門前町 今出川通烏丸東入", official_url: "http://www.shokoku-ji.jp/"},
  {title: "引接寺", address: "日本, 〒602-8307 京都府京都市上京区閻魔前町 千本通蘆山寺上ル閻魔前町３４", official_url: "http://yenmado.blogspot.jp/"},
  {title: "報恩寺", address: "日本, 〒620-0002 京都府福知山市報恩寺", official_url: nil},
  {title: "東本願寺", address: "日本, 〒600-8505 京都府京都市下京区常葉町 烏丸通七条上る", official_url: "http://www.higashihonganji.or.jp/"},
  {title: "西本願寺", address: "日本, 〒060-0003 北海道札幌市中央区北3条西１９丁目１９", official_url: "http://www.hongwanji.or.jp/"},
  {title: "六波羅蜜寺", address: "日本, 〒605-0933 京都府京都市東山区轆轤町 五条通大和大路上ル東", official_url: "http://rokuhara.or.jp/"},
  {title: "清水寺", address: "日本, 〒605-0862 京都府京都市東山区清水１丁目２９４", official_url: "http://www.kiyomizudera.or.jp/"},
  {title: "知恩院", address: "日本, 〒605-8686 京都府京都市東山区林下町４００", official_url: "http://www.chion-in.or.jp/index.php"},
  {title: "泉涌寺", address: "日本, 〒605-0977 京都府京都市東山区泉涌寺山内町２７", official_url: "http://www.mitera.org/"},
  {title: "今熊野観音寺", address: "日本, 〒605-0977 京都府京都市東山区泉涌寺山内町３２", official_url: "http://www.kannon.jp/"},
  {title: "方広寺", address: "日本, 〒431-2224 静岡県浜松市北区引佐町奥山１５７７−１", official_url: "http://www.houkouji.or.jp/"},
  {title: "三十三間堂", address: "日本, 〒605-0941 京都府京都市東山区三十三間堂廻リ６５７", official_url: "http://www.sanjusangendo.jp/"},
  {title: "東福寺", address: "日本, 〒605-0981 京都府京都市東山区本町15−778", official_url: "http://www.tofukuji.jp/"},
  {title: "大雲院", address: "日本, 〒605-0074 京都府京都市東山区祇園町南側５９４−１", official_url: nil},
  {title: "建仁寺", address: "日本, 〒605-0811 京都府京都市東山区小松町 大和大路通四条下る小松町584", official_url: "http://www.kenninji.jp/"},
  {title: "南禅寺", address: "日本, 〒606-8435 京都府京都市左京区南禅寺福地町", official_url: "http://www.nanzen.net/"},
  {title: "慈照寺", address: "日本, 〒606-8402 京都府京都市左京区銀閣寺町２", official_url: "http://www.shokoku-ji.jp/g_about.html"},
  {title: "鞍馬寺", address: "日本, 〒601-1111 京都府京都市左京区鞍馬本町1074番地", official_url: "http://www.kuramadera.or.jp/"},
  {title: "三千院", address: "日本, 〒601-1242 京都府京都市左京区大原来迎院町５４０", official_url: "http://www.sanzenin.or.jp/"},
  {title: "寂光院", address: "日本, 〒601-1248 京都府京都市左京区大原草生町６７６", official_url: "http://www.jakkoin.jp/"},
  {title: "知恩寺", address: "日本, 〒606-8225 京都府京都市左京区田中門前町103", official_url: "http://hyakusan.jp/"},
  {title: "禅林寺", address: "日本, 〒606-8445 京都府京都市左京区永観堂町48", official_url: "http://www.eikando.or.jp/"},
  {title: "瑠璃光院", address: "日本, 〒601-1255 京都府京都市左京区上高野東山５５", official_url: "http://rurikoin.komyoji.com/"},
  {title: "天竜寺", address: "日本, 〒616-8385 京都府京都市右京区嵯峨天龍寺芒ノ馬場町 嵯峨天龍寺芒ノ馬場町68", official_url: "http://www.tenryuji.com/"},
  {title: "妙心寺", address: "日本, 〒616-8035 京都府京都市右京区花園妙心寺町64", official_url: "http://www.myoshinji.or.jp/"},
  {title: "化野念仏寺", address: "日本, 〒616-8436 京都府京都市右京区嵯峨鳥居本化野町１７", official_url: "http://www.nenbutsuji.jp/"},
  {title: "愛宕念仏寺", address: "日本, 〒616-8439 京都府京都市右京区嵯峨鳥居本深谷町２−５", official_url: "http://www.otagiji.com/"},
  {title: "竜安寺", address: "日本, 〒616-8001 京都府京都市右京区龍安寺御陵ノ下町１３", official_url: "http://www.ryoanji.jp/"},
  {title: "仁和寺", address: "日本, 〒616-8092 京都府京都市右京区御室大内３３", official_url: "http://www.ninnaji.or.jp/"},
  {title: "神護寺", address: "日本, 〒616-8292 京都府京都市右京区梅ケ畑高雄町５", official_url: "http://www.jingoji.or.jp/"},
  {title: "高山寺", address: "日本, 〒616-8295 京都府京都市右京区梅ケ畑栂尾町8", official_url: "http://www.kosanji.com/"},
  {title: "等持院", address: "日本, 〒603-8346 京都府京都市北区等持院北町６３", official_url: nil},
  {title: "鹿苑寺", address: "日本, 〒603-8361 京都府京都市北区金閣寺町１", official_url: "http://www.shokoku-ji.jp/k_access.html"},
  {title: "大徳寺", address: "日本, 〒603-8231 京都府京都市北区紫野大徳寺町５３", official_url: "http://www.rinnou.net/cont_03/07daitoku/"},
  {title: "西芳寺", address: "日本, 〒615-8286 京都府京都市西京区松尾神ケ谷町５６", official_url: "http://www.pref.kyoto.jp/isan/saihouji.html"},
  {title: "善峯寺", address: "日本, 〒610-1133 京都府京都市西京区大原野小塩町1372", official_url: "http://www.yoshiminedera.com/"},
  {title: "平等院", address: "日本, 〒611-0021 京都府宇治市宇治蓮華１１６", official_url: "http://www.byodoin.or.jp/"},
  {title: "三室戸寺", address: "日本, 〒611-0013 京都府宇治市莵道滋賀谷２１", official_url: "http://www.mimurotoji.com/"},
  {title: "興聖寺", address: "日本, 〒611-0021 京都府宇治市宇治山田２７−１", official_url: "http://kyoto-uji-kankou.or.jp/others/corse/shot/index.html"},
  {title: "神応寺", address: "日本, 〒614-8007 京都府八幡市八幡西高坊２４", official_url: "http://www.city.yawata.kyoto.jp/0000000490.html"},
  {title: "一休寺", address: "日本, 〒610-0341 京都府京田辺市薪里ノ内 京都府京田辺市薪里ノ内102", official_url: "http://www.ikkyuji.org/"},
  {title: "岩船寺", address: "日本, 〒619-1133 京都府木津川市加茂町岩船上ノ門４３", official_url: "http://0774.or.jp/temple/gansenji.html"},
  {title: "浄瑠璃寺", address: "日本, 〒619-1135 京都府木津川市加茂町西小札場札場40", official_url: "http://0774.or.jp/temple/jyoruriji.html"},
  {title: "海住山寺", address: "日本, 〒619-1106 京都府木津川市加茂町例幣海住山境外２０", official_url: "http://www.kaijyusenji.jp/"},
  {title: "笠置寺", address: "日本, 〒619-1303 京都府相楽郡笠置笠置山 笠置町笠置笠置山29", official_url: "http://www.kasagidera.or.jp/"},
  {title: "金胎寺", address: "日本, 〒619-1202 京都府相楽郡和束町原山鷲峰山 京都府相楽郡和束町原山鷲峰山", official_url: nil},
  {title: "宝積寺", address: "日本, 〒329-1233 栃木県塩谷郡高根沢町宝積寺", official_url: nil},
  {title: "穴太寺", address: "日本, 〒621-0029 京都府亀岡市曽我部町穴太東ノ辻４６", official_url: "http://saikoku33.gr.jp/21/"},
  {title: "成相寺", address: "日本, 〒629-2241 京都府宮津市成相寺３３９", official_url: "http://www.nariaiji.jp/"},
  {title: "智恩寺", address: "日本, 〒626-0001 京都府宮津市文珠４６６", official_url: "http://www.monjudo-chionji.jp/"},
  {title: "松尾寺", address: "日本, 〒639-1057 奈良県大和郡山市山田町６８３", official_url: "http://www.matsuodera.com/"},
  {title: "能福寺", address: "日本, 〒652-0837 兵庫県神戸市兵庫区北逆瀬川町１−３９", official_url: "http://nofukuji.jp/"},
  {title: "須磨寺", address: "日本, 〒654-0071 兵庫県神戸市須磨区須磨寺町", official_url: nil},
  {title: "忉利天上寺", address: "日本, 〒657-0105 兵庫県神戸市灘区摩耶山町２−１２", official_url: "http://www.mayasan-tenjoji.jp/"},
  {title: "中山寺", address: "日本, 〒665-0861 兵庫県宝塚市中山寺", official_url: nil},
  {title: "清荒神清澄寺", address: "日本, 〒665-0837 兵庫県宝塚市米谷清シ−１", official_url: "http://www.kiyoshikojin.or.jp/"},
  {title: "神呪寺", address: "日本, 〒662-0001 兵庫県西宮市甲山町２５−１", official_url: "http://www.ne.jp/asahi/kabutoyama/kanno-ji/"},
  {title: "鷲林寺", address: "日本, 〒662-0003 兵庫県西宮市鷲林寺町４−８", official_url: "http://www5b.biglobe.ne.jp/~jurinji/"},
  {title: "高源寺", address: "日本, 〒669-3821 兵庫県丹波市青垣町桧倉５１４", official_url: "http://kougenji-tanba.or.jp/"},
  {title: "圓満寺", address: "日本, 〒675-0157 兵庫県加古郡播磨町上野添２丁目１", official_url: "http://www.enmanji.net/"},
  {title: "鶴林寺", address: "日本, 〒675-0031 兵庫県加古川市加古川町北在家北在家４２４", official_url: "http://www.kakurinji.or.jp/"},
  {title: "教信寺", address: "日本, 〒675-0012 兵庫県加古川市野口町野口４６５", official_url: "http://www.bekkoame.ne.jp/~housenin/link32.html"},
  {title: "播州清水寺", address: "日本, 〒673-1402 兵庫県加東市平木１１９４", official_url: "http://kiyomizudera.net/"},
  {title: "光明寺", address: "日本, 〒491-0135 愛知県一宮市光明寺", official_url: nil},
  {title: "浄土寺", address: "日本, 〒722-0043 広島県尾道市東久保町20−28", official_url: "http://www.ermjp.com/j/temple/"},
  {title: "一乗寺", address: "日本, 〒606-8115 京都府京都市左京区一乗寺里ノ西町102", official_url: nil},
  {title: "随願寺", address: "日本, 〒670-0808 兵庫県姫路市白国５", official_url: nil},
  {title: "圓教寺", address: "日本, 〒671-2201 兵庫県姫路市書写２９６８", official_url: "http://www.shosha.or.jp/"},
  {title: "八葉寺", address: "日本, 〒969-3422 福島県会津若松市河東町広野冬木沢 福島県会津若松市河東町広野冬木沢", official_url: nil},
  {title: "花岳寺", address: "日本, 〒678-0239 兵庫県赤穂市加里屋１９９２", official_url: "https://kagakuji.jimdo.com/"},
  {title: "太融寺", address: "日本, 〒530-0051 大阪府大阪市北区太融寺町", official_url: nil},
  {title: "鶴満寺", address: "日本, 〒531-0063 大阪府大阪市北区長柄東１丁目３−１２", official_url: nil},
  {title: "三津寺", address: "日本, 〒542-0085 大阪府大阪市中央区心斎橋筋２丁目７−１２", official_url: "https://mitsutera.jp/"},
  {title: "北御堂", address: "日本, 〒541-0053 大阪府大阪市中央区本町４丁目4−1−3", official_url: "http://www.kitamido.or.jp/"},
  {title: "南御堂", address: "日本, 〒541-0056 大阪府大阪市中央区久太郎町４丁目１−１１", official_url: "http://minamimido.jp/"},
  {title: "法善寺", address: "日本, 〒542-0076 大阪府大阪市中央区難波１丁目１−２−１６", official_url: "http://houzenji.jp/"},
  {title: "四天王寺", address: "日本, 〒543-0051 大阪府大阪市天王寺区四天王寺", official_url: nil},
  {title: "勝鬘院", address: "日本, 〒543-0075 大阪府大阪市天王寺区夕陽丘町５−３６", official_url: "http://www.aizendo.com/"},
  {title: "円珠庵", address: "日本, 〒543-0018 大阪府大阪市天王寺区空清町４−２", official_url: "http://kamahachiman.sakura.ne.jp/"},
  {title: "道善寺", address: "日本, 〒543-0071 大阪府大阪市天王寺区生玉町２−６", official_url: nil},
  {title: "大念佛寺", address: "日本, 〒547-0045 大阪府大阪市平野区平野上町１丁目７−２６", official_url: "http://www.dainenbutsuji.com/"},
  {title: "勝尾寺", address: "日本, 〒562-0021 大阪府箕面市粟生間谷２９１４−１", official_url: "http://www.katsuo-ji-temple.or.jp/"},
  {title: "成田山明王院", address: "日本, 〒572-0005 大阪府寝屋川市成田西町１０−１", official_url: "http://www.osaka-naritasan.or.jp/"},
  {title: "慈眼寺", address: "日本, 〒891-0146 鹿児島県鹿児島市慈眼寺町", official_url: nil},
  {title: "顕証寺", address: "日本, 〒581-0072 大阪府八尾市久宝寺４丁目４−３", official_url: "http://www5a.biglobe.ne.jp/~kenshoji/"},
  {title: "大信寺", address: "日本, 〒370-0615 群馬県邑楽郡邑楽町篠塚 群馬県邑楽郡邑楽町大字篠塚3999−2", official_url: "http://daishinji.net/"},
  {title: "葛井寺", address: "日本, 〒583-0024 大阪府藤井寺市藤井寺１丁目１６−２１", official_url: "http://www.geocities.jp/saikoku33_5/"},
  {title: "道明寺", address: "日本, 〒583-0012 大阪府藤井寺市道明寺", official_url: nil},
  {title: "叡福寺", address: "日本, 〒583-0995 大阪府南河内郡太子町太子 太子町太子２１４６", official_url: "http://www.shin-saigoku.jp/temple/11_eifukuji_01.html"},
  {title: "弘川寺", address: "日本, 〒585-0022 大阪府南河内郡河南町弘川４３", official_url: "http://www.town.kanan.osaka.jp/kananchotte/kankogaido/terajinja/1394613320825.html"},
  {title: "観心寺", address: "日本, 〒586-0053 大阪府河内長野市寺元475", official_url: "http://www.kanshinji.com/"},
  {title: "金剛寺", address: "315 台湾 新竹県 峨眉郷", official_url: "http://www.wlig999.com/mobile/edcontent.php?lang=tw&tb=7&cid=35"},
  {title: "願泉寺", address: "日本, 〒597-0003 大阪府貝塚市中８４６", official_url: "http://www.eonet.ne.jp/~gansenji"},
  {title: "水間寺", address: "日本, 〒597-0104 大阪府貝塚市水間６３８", official_url: "http://www.mizumadera.or.jp/index.html"},
  {title: "七宝瀧寺", address: "日本, 〒598-0023 大阪府泉佐野市大木８", official_url: "http://www.inunakisan.jp/"},
  {title: "家原寺", address: "日本, 〒593-8304 大阪府堺市西区家原寺町１丁８−２０", official_url: "http://www.chiemonjyuebaraji.jp/"},
  {title: "施福寺", address: "日本, 〒594-1131 大阪府和泉市槇尾山町136", official_url: "http://saikoku33.gr.jp/place/4"},
  {title: "三井寺", address: "日本, 〒520-0036 滋賀県大津市園城寺町２４６", official_url: "http://www.shiga-miidera.or.jp/"},
  {title: "石山寺", address: "日本, 〒520-0861 滋賀県大津市石山寺", official_url: nil},
  {title: "岩間寺", address: "日本, 〒520-0869 滋賀県大津市石山内畑町82", official_url: "http://www.iwama-dera.or.jp/"},
  {title: "善水寺", address: "日本, 〒520-3252 滋賀県湖南市岩根３５１８", official_url: "http://www.zensuiji.jp/"},
  {title: "常楽寺", address: "日本, 〒247-0056 神奈川県鎌倉市大船５丁目８−２９", official_url: nil},
  {title: "長寿寺", address: "日本, 〒247-0062 神奈川県鎌倉市山ノ内１５２０", official_url: nil},
  {title: "長命寺", address: "日本, 〒131-0033 東京都墨田区向島５丁目４−４", official_url: nil},
  {title: "観音正寺", address: "日本, 〒521-1331 滋賀県近江八幡市安土町石寺２", official_url: "http://www.kannon.or.jp/"},
  {title: "桑實寺", address: "日本, 〒521-1321 滋賀県近江八幡市安土町桑実寺２９２", official_url: nil},
  {title: "教林坊", address: "日本, 〒521-1331 滋賀県近江八幡市安土町石寺 滋賀県近江八幡市安土町石寺1145", official_url: "http://www.d1.dion.ne.jp/~marche/kyourinbou/"},
  {title: "石塔寺", address: "日本, 〒529-1501 滋賀県東近江市石塔町８６０", official_url: "http://www.biwa.ne.jp/~tam/sansaku/report/26%20ishidoji/ishidoji.html"},
  {title: "百済寺", address: "日本, 〒527-0144 滋賀県東近江市百済寺町３２３", official_url: "http://www.hyakusaiji.jp/"},
  {title: "西明寺", address: "日本, 〒522-0254 滋賀県犬上郡甲良町池寺２６", official_url: "http://www.saimyouji.com/"},
  {title: "金剛輪寺", address: "日本, 〒529-1202 滋賀県愛知郡愛荘町松尾寺８７４", official_url: "http://kongourinji.jp/"},
  {title: "宝厳寺", address: "日本, 〒526-0124 滋賀県長浜市早崎町１６６４−１", official_url: "http://www.chikubushima.jp/"},
  {title: "興聖寺", address: "日本, 〒611-0021 京都府宇治市宇治山田２７−１", official_url: "http://kyoto-uji-kankou.or.jp/others/corse/shot/index.html"},
  {title: "紀三井寺", address: "日本, 〒641-0012 和歌山県和歌山市紀三井寺１２０１", official_url: "http://www.kimiidera.com/"},
  {title: "根来寺", address: "日本, 〒649-6202 和歌山県岩出市根来２２８６", official_url: "http://www.negoroji.org/"},
  {title: "粉河寺", address: "日本, 〒649-6531 和歌山県紀の川市粉河 粉河2787", official_url: "http://www.kokawadera.org/"},
  {title: "慈尊院", address: "日本, 〒648-0151 和歌山県伊都郡九度山町慈尊院", official_url: nil},
  {title: "高野山", address: "Koya-san, 高野山 高野町 伊都郡 和歌山県 648-0211 日本", official_url: nil},
  {title: "道成寺", address: "日本, 〒649-1331 和歌山県日高郡日高川町鐘巻１７３８", official_url: "http://www.dojoji.com/"},
  {title: "青岸渡寺", address: "日本, 〒649-5301 和歌山県東牟婁郡那智勝浦町大字那智山８", official_url: "http://www.nachikan.jp/kumano/seigantoji/"},
  {title: "無量寺", address: "日本, 〒920-0333 石川県金沢市無量寺", official_url: nil},
  {title: "橿原神宮", address: "日本, 〒634-8550 奈良県橿原市久米町９３４", official_url: "http://www.kashiharajingu.or.jp/"},
  {title: "春日大社", address: "日本, 〒630-8212 奈良県奈良市春日野町１６０", official_url: "http://www.kasugataisha.or.jp/"},
  {title: "石上神宮", address: "日本, 〒632-0014 奈良県天理市布留町３８４", official_url: "http://www.isonokami.jp/"},
  {title: "檜原神社", address: "日本, 〒633-0001 奈良県桜井市三輪 奈良県桜井市大字三輪１４２２", official_url: nil},
  {title: "大神神社", address: "日本, 〒633-8538 奈良県桜井市三輪1422", official_url: "http://oomiwa.or.jp/"},
  {title: "談山神社", address: "日本, 〒633-0032 奈良県桜井市多武峰319", official_url: "http://www.tanzan.or.jp/"},
  {title: "一言主神社", address: "日本, 〒303-0045 茨城県常総市大塚戸町８７５", official_url: "http://www.hitokoto.or.jp/"},
  {title: "高天彦神社", address: "日本, 〒639-2336 奈良県御所市北窪 奈良県御所市高天", official_url: "http://takama.sakura.ne.jp/takamahikojinjya"},
  {title: "葛木神社", address: "日本, 〒639-2336 奈良県御所市高天 高天４７２", official_url: "http://goseshikankou.jp/syousai/otera-zinzya/sonota/katuragi/katuragi.html"},
  {title: "丹生川上神社", address: "日本, 〒632-2431 奈良県吉野郡東吉野村小９６８", official_url: "http://www.niukawakami-jinja.jp/"},
  {title: "天河大弁財天社", address: "日本, 〒638-0321 奈良県吉野郡天川村坪内１０７", official_url: "http://www.tenkawa-jinja.or.jp/"},
  {title: "玉置神社", address: "日本, 〒647-1582 奈良県吉野郡十津川村玉置川１番地", official_url: "http://www.tamakijinja.or.jp/"},
  {title: "東大寺", address: "日本, 〒630-8211 奈良県奈良市雑司町４０６−１", official_url: "http://www.todaiji.or.jp/"},
  {title: "興福寺", address: "日本, 〒630-8213 奈良県奈良市登大路町４８", official_url: "http://www.kohfukuji.com/"},
  {title: "薬師寺", address: "日本, 〒630-8563 奈良県奈良市西ノ京町４５７", official_url: "http://www.nara-yakushiji.com/index.html"},
  {title: "唐招提寺", address: "日本, 〒630-8032 奈良県奈良市五条町１３−４６", official_url: "http://www.toshodaiji.jp/"},
  {title: "正暦寺", address: "日本, 〒630-8413 奈良県奈良市菩提山町１５７", official_url: "http://shoryakuji.jp/"},
  {title: "円成寺", address: "日本, 〒630-1244 奈良県奈良市忍辱山町1273", official_url: "http://www.enjyouji.jp/"},
  {title: "新薬師寺", address: "日本, 〒630-8301 奈良県奈良市高畑町 高畑町１３５２", official_url: "http://www.shinyakushiji.or.jp/"},
  {title: "西大寺", address: "日本, 〒631-0825 奈良県奈良市西大寺芝町１丁目１−５", official_url: "http://saidaiji.or.jp/"},
  {title: "般若寺", address: "日本, 〒630-8102 奈良県奈良市般若寺町", official_url: nil},
  {title: "法華寺", address: "日本, 〒630-8001 奈良県奈良市法華寺町", official_url: nil},
  {title: "霊山寺", address: "日本, 〒631-0052 奈良県奈良市中町3879", official_url: "http://www.ryosenji.jp/"},
  {title: "白毫寺", address: "日本, 〒630-8302 奈良県奈良市白毫寺町", official_url: nil},
  {title: "弘仁寺", address: "日本, 〒630-8412 奈良県奈良市虚空蔵町 奈良県奈良市虚空蔵町４６", official_url: "http://www.kouninji.org/"},
  {title: "法隆寺", address: "日本, 〒636-0115 奈良県生駒郡斑鳩町法隆寺山内１−１", official_url: "http://www.horyuji.or.jp/"},
  {title: "法輪寺", address: "日本, 〒616-0006 京都府京都市西京区嵐山虚空蔵山町１６", official_url: "http://www.kokuzohourinji.com/"},
  {title: "法起寺", address: "日本, 〒636-0102 奈良県生駒郡斑鳩町岡本１８７３番地", official_url: "http://www.horyuji.or.jp/hokiji.htm"},
  {title: "信貴山朝護孫子寺", address: "日本, 〒636-0923 奈良県生駒郡平群町信貴山２２８０−１", official_url: "http://www.sigisan.or.jp/"},
  {title: "宝山寺", address: "日本, 〒630-0266 奈良県生駒市門前町１−１", official_url: "http://www.hozanji.com/"},
  {title: "竹林寺", address: "No. 325, Zhulin Road, Linkou District, New Taipei City, 台湾 244", official_url: "http://www.zlskyt.com.tw/"},
  {title: "松尾寺", address: "日本, 〒639-1057 奈良県大和郡山市山田町６８３", official_url: "http://www.matsuodera.com/"},
  {title: "矢田寺", address: "日本, 〒639-1058 奈良県大和郡山市矢田町３５４９", official_url: "http://www.yatadera.or.jp/"},
  {title: "東明寺", address: "日本, 〒639-1058 奈良県大和郡山市矢田町２２３０ 639 1058", official_url: "http://toumyouji.com/"},
  {title: "長岳寺", address: "日本, 〒632-0052 兵庫県天理市柳本町508", official_url: "http://www.chogakuji.or.jp/"},
  {title: "百済寺", address: "日本, 〒527-0144 滋賀県東近江市百済寺町３２３", official_url: "http://www.hyakusaiji.jp/"},
  {title: "久米寺", address: "日本, 〒634-0063 奈良県橿原市久米町５０２", official_url: "http://www.city.kashihara.nara.jp/kankou/own_kankou/kankou/spot/kumedera.html"},
  {title: "称念寺", address: "日本, 〒602-8498 京都府京都市上京区寺之内通浄福寺西上る西熊町２７５", official_url: "http://nekodera.net/"},
  {title: "南法華寺", address: "日本, 〒635-0102 奈良県高市郡高取町壷阪3", official_url: "http://www.tsubosaka1300.or.jp/"},
  {title: "岡寺", address: "日本, 〒634-0111 奈良県高市郡明日香村岡８０６", official_url: "http://www.okadera3307.com/"},
  {title: "長谷寺", address: "日本, 〒248-0016 神奈川県鎌倉市長谷３丁目１１−２", official_url: "http://www.hasedera.jp/"},
  {title: "室生寺", address: "日本, 〒633-0421 奈良県宇陀市室生７８", official_url: "http://www.murouji.or.jp/"},
  {title: "大野寺", address: "日本, 〒633-0315 奈良県宇陀市室生大野１６８０", official_url: "http://www.city.uda.nara.jp/sin-kankou/guide/flower/f04.html"},
  {title: "大澤寺", address: "日本, 〒421-0523 静岡県牧之原市波津８０８−５", official_url: "http://www.daitakuji.jp/"},
  {title: "転法輪寺", address: "日本, 〒639-2336 奈良県御所市高天", official_url: nil},
  {title: "沙沙貴神社", address: "日本, 〒521-1351 滋賀県近江八幡市安土町常楽寺２", official_url: "http://sasakijinja.or.jp/"},
  {title: "日吉大社", address: "日本, 〒520-0113 滋賀県大津市坂本５丁目１−１", official_url: "http://hiyoshitaisha.jp/"},
  {title: "都久夫須麻神社", address: "日本, 〒526-0124 滋賀県長浜市早崎町1665", official_url: "http://www.biwako-visitors.jp/spot/detail/1312"},
  {title: "湯谷神社", address: "日本, 〒521-0012 滋賀県米原市米原７７１", official_url: nil},
  {title: "多賀大社", address: "日本, 〒522-0341 滋賀県犬上郡多賀町多賀６０４", official_url: "http://www.tagataisya.or.jp/"},
  {title: "兵主神社", address: "日本, 〒520-2424 滋賀県野洲市五条 滋賀県野洲市五条５６６", official_url: nil},
  {title: "近江神宮", address: "日本, 〒520-0015 滋賀県大津市神宮町１−１−１", official_url: "http://oumijingu.org/"},
  {title: "生田神社", address: "日本, 〒650-0011 兵庫県神戸市中央区下山手通１丁目２−１", official_url: "https://ikutajinja.or.jp/"},
  {title: "湊川神社", address: "日本, 〒650-0015 兵庫県神戸市中央区多聞通３丁目3−1−1", official_url: "http://www.minatogawajinja.or.jp/"},
  {title: "長田神社", address: "日本, 〒653-0812 兵庫県神戸市長田区長田区長田町３丁目１−１", official_url: "http://nagatajinja.jp/html/"},
  {title: "蛭子神社", address: "日本, 〒652-0806 兵庫県神戸市兵庫区西柳原町５−２０", official_url: "http://www.hyogo-ebisu.com/"},
  {title: "廣田神社", address: "日本, 〒662-0867 兵庫県西宮市大社町７ 兵庫県西宮市大社町７−７", official_url: "http://www.hirotahonsya.or.jp/"},
  {title: "西宮神社", address: "日本, 〒662-0974 兵庫県西宮市社家町１−１７", official_url: "http://nishinomiya-ebisu.com/"},
  {title: "売布神社", address: "日本, 〒690-0005 島根県松江市和多見町81", official_url: "http://www.shinbutsu.jp/37.html"},
  {title: "佐保神社", address: "日本, 〒673-1431 兵庫県加東市社７７７", official_url: "http://www.hyogo-jinjacho.com/data/6311091.html"},
  {title: "廣峯神社", address: "日本, 〒670-0891 兵庫県姫路市広嶺山５２", official_url: "http://www.hiromine-j.jp/"},
  {title: "おのころ島神社", address: "日本, 〒656-0423 兵庫県南あわじ市榎列下幡多 兵庫県南あわじ市榎列下幡多415", official_url: "http://www.freedom.ne.jp/onokoro/"},
  {title: "高砂神社", address: "日本, 〒676-0043 兵庫県高砂市高砂町東宮町１９０", official_url: "http://takasagojinja.takara-bune.net/"},
  {title: "鹿嶋神社", address: "日本, 〒676-0828 兵庫県高砂市阿弥陀町地徳２７９番地", official_url: "http://www.kashimajinja.or.jp/"},
  {title: "高御位神社", address: "日本, 〒676-0827 兵庫県高砂市阿弥陀町阿弥陀", official_url: nil},
  {title: "生石神社", address: "日本, 〒676-0823 兵庫県高砂市阿弥陀町生石１７１", official_url: "http://www.isinohouden.com/"},
  {title: "尾上神社", address: "日本, 〒675-0024 兵庫県加古川市尾上町長田５１８", official_url: "http://kako-navi.jp/spot/spot/purpose/history/927"},
  {title: "日前宮", address: "日本, 〒640-8322 和歌山県和歌山市秋月３６５", official_url: "http://hinokuma-jingu.com/"},
  {title: "淡嶋神社", address: "日本, 〒640-0103 和歌山県和歌山市加太 和歌山県和歌山市加太", official_url: "http://www.kada.jp/awashima/"},
  {title: "伊太祁曽神社", address: "日本, 〒640-0361 和歌山県和歌山市伊太祈曽558", official_url: "http://itakiso-jinja.net/"},
  {title: "竈山神社", address: "日本, 〒641-0004 和歌山県和歌山市和田４３８", official_url: "http://www.wakayama-jinjacho.or.jp/jdb/sys/user/GetWjtTbl.php?JinjyaNo=1052"},
  {title: "濱宮", address: "日本, 〒641-0014 和歌山県和歌山市毛見１３０３", official_url: "http://wakayama-jinjacho.or.jp/jdb/sys/user/GetWjtTbl.php?JinjyaNo=1046"},
  {title: "和歌浦天満宮", address: "日本, 〒641-0024 和歌山県和歌山市和歌浦西２丁目１−２４", official_url: "http://wakamatsuri.com/spot/%E5%92%8C%E6%AD%8C%E6%B5%A6%E5%A4%A9%E6%BA%80%E5%AE%AE"},
  {title: "藤白神社", address: "日本, 〒642-0034 和歌山県海南市藤白４６６", official_url: "http://fujishiro-jinja.net/"},
  {title: "丹生都比売神社", address: "日本, 〒649-7141 和歌山県伊都郡かつらぎ町上天野230", official_url: "http://www.niutsuhime.or.jp/"},
  {title: "隅田八幡神社", address: "日本, 〒648-0018 和歌山県橋本市隅田町垂井６２２", official_url: "http://wakayama-jinjacho.or.jp/jdb/sys/user/GetWjtTbl.php?JinjyaNo=4001"},
  {title: "闘鶏神社", address: "日本, 〒646-0029 和歌山県田辺市東陽１−１", official_url: "http://wakayama-jinjacho.or.jp/jdb/sys/user/GetWjtTbl.php?JinjyaNo=7001"},
  {title: "神倉神社", address: "日本, 〒647-0044 和歌山県新宮市神倉１丁目１３−８", official_url: "http://kumanohayatama.jp/?page_id=18"},
  {title: "伏見稲荷大社", address: "日本, 〒612-0882 京都府京都市伏見区深草藪之内町６８", official_url: "http://inari.jp/"},
  {title: "晴明神社", address: "日本, 〒602-8222 京都府京都市上京区晴明町 堀川通一条上ル晴明町806", official_url: "http://www.seimeijinja.jp/"},
  {title: "北野天満宮", address: "日本, 〒602-8386 京都府京都市上京区馬喰町", official_url: "http://kitanotenmangu.or.jp/"},
  {title: "錦天満宮", address: "日本, 〒604-8042 京都府京都市中京区中之町（新京極通） 新京極通り四条上る中之町537番地", official_url: "http://nishikitenmangu.or.jp/"},
  {title: "電電宮", address: "日本, 〒616-0004 京都府京都市西京区嵐山中尾下町４２−２５", official_url: "http://www.kokuzohourinji.com/dendengu.html"},
  {title: "車折神社", address: "日本, 〒616-8343 京都府京都市右京区嵯峨朝日町 右京区嵯峨朝日町２３", official_url: "http://www.kurumazakijinja.or.jp/"},
  {title: "平安神宮", address: "日本, 〒606-8341 京都府京都市左京区岡崎西天王町", official_url: "http://www.heianjingu.or.jp/"},
  {title: "八坂神社", address: "日本, 〒605-0073 京都府京都市東山区祇園町北側６２５", official_url: "http://www.yasaka-jinja.or.jp/"},
  {title: "地主神社", address: "日本, 〒605-0862 京都府京都市東山区清水1丁目317", official_url: "http://www.jishujinja.or.jp/"},
  {title: "下鴨神社", address: "日本, 〒606-0807 京都府京都市左京区下鴨泉川町59", official_url: "http://www.shimogamo-jinja.or.jp/"},
  {title: "上賀茂神社", address: "日本, 〒603-8047 京都府京都市北区上賀茂本山３３９", official_url: "http://www.kamigamojinja.jp/"},
  {title: "護王神社", address: "日本, 〒602-8011 京都府京都市上京区桜鶴円町 烏丸通下長者町下ル桜鶴円町385", official_url: "http://www.gooujinja.or.jp/"},
  {title: "豊国神社", address: "日本, 〒605-0931 京都府京都市東山区茶屋町 京都府京都市東山区大和大路通り正面茶屋町530", official_url: "http://kanko.city.kyoto.lg.jp/detail.php?InforKindCode=1&ManageCode=1000182"},
  {title: "平野神社", address: "日本, 〒603-8322 京都府京都市北区平野宮本町１", official_url: "http://www.hiranojinja.com/"},
  {title: "出世稲荷神社", address: "日本, 〒601-1242 京都府京都市左京区大原来迎院町 京都府京都市左京区大原来迎院町１４８", official_url: "http://syusseinari.or.jp/"},
  {title: "松尾大社", address: "日本, 〒616-0024 京都府京都市西京区嵐山宮町３", official_url: "http://www.matsunoo.or.jp/"},
  {title: "白峯神宮", address: "日本, 〒602-0054 京都府京都市上京区飛鳥井町 今出川堀川東入飛鳥井261", official_url: "http://shiraminejingu.or.jp/"},
  {title: "藤森神社", address: "日本, 〒612-0863 京都府京都市伏見区深草鳥居崎町６０９", official_url: "http://www.fujinomorijinjya.or.jp/"},
  {title: "長岡天満宮", address: "日本, 〒617-0824 京都府長岡京市天神２丁目１５−１５−１３", official_url: "http://www.nagaokatenmangu.or.jp/"},
  {title: "向日神社", address: "日本, 〒617-0005 京都府向日市向日町北山北山６５", official_url: "http://www.geocities.jp/mukojinjahp/"},
  {title: "宇治上神社", address: "日本, 〒611-0021 京都府宇治市宇治山田５９", official_url: "http://www.pref.kyoto.jp/isan/ujigami.html"},
  {title: "石清水八幡宮", address: "日本, 〒614-8005 京都府八幡市八幡高坊30", official_url: "http://www.iwashimizu.or.jp/"},
  {title: "土佐稲荷神社", address: "日本, 〒550-0014 大阪府大阪市西区北堀江４丁目９−７", official_url: "http://www.tosainari.jp/"},
  {title: "サムハラ神社", address: "日本, 〒550-0012 大阪府大阪市西区立売堀２丁目５−２６", official_url: nil},
  {title: "大阪天満宮", address: "日本, 〒530-0041 大阪府大阪市北区天神橋２丁目１−1番8", official_url: "http://www.tenjinsan.com/"},
  {title: "少彦名神社", address: "日本, 〒541-0045 大阪府大阪市中央区道修町２丁目１−８", official_url: "http://www.sinnosan.jp/onrei.html"},
  {title: "難波神社", address: "日本, 〒541-0059 大阪府大阪市中央区博労町４丁目２−1番3", official_url: "http://www.nanba-jinja.or.jp/"},
  {title: "坐摩神社", address: "日本, 〒541-0056 大阪府大阪市中央区久太郎町４丁目渡辺３号", official_url: "http://www.ikasuri.or.jp/"},
  {title: "御霊神社", address: "日本, 〒248-0021 神奈川県鎌倉市坂ノ下４ 248-0021 神奈川県鎌倉市坂ノ下4-9", official_url: "https://www.city.kamakura.kanagawa.jp/kamakura-kankou/meisho/02goryoujinja.html"},
  {title: "玉造稲荷神社", address: "日本, 〒540-0004 大阪府大阪市中央区中央区玉造２丁目３−８", official_url: "http://www.inari.or.jp/"},
  {title: "高津宮", address: "日本, 〒542-0072 大阪府大阪市中央区高津１丁目１−２９", official_url: "http://www.kouzu.or.jp/"},
  {title: "大江神社", address: "日本, 〒543-0075 大阪府大阪市天王寺区夕陽丘町５−４０", official_url: "http://ooejinja.net/index.html"},
  {title: "生國魂神社", address: "日本, 〒543-0071 大阪府大阪市天王寺区生玉町１３−９", official_url: "http://www.jinjacho-osaka.net/osakafunai-no-jinjya/dai8sibu/tennouji-ku/m01i_01_tennouji_ikukunitama.html"},
  {title: "三光神社", address: "日本, 〒543-0013 大阪府大阪市天王寺区玉造本町１４−９０", official_url: "http://sankoujinja.com/index.html"},
  {title: "日吉神社", address: "日本, 〒010-1622 秋田県秋田市新屋日吉町１０−６７", official_url: "http://hiyoshi-jinja.jp/"},
  {title: "神須牟地神社", address: "日本, 〒558-0002 大阪府大阪市住吉区長居西２丁目１−４", official_url: "http://www.jinjacho-osaka.net/osakafunai-no-jinjya/dai9sibu/sumiyosi-ku/m01u_04_sumiyosi_kamisumuti.html"},
  {title: "堀越神社", address: "日本, 〒543-0063 大阪府大阪市天王寺区茶臼山町１−８", official_url: "http://horikoshijinja.or.jp/"},
  {title: "今宮戎神社", address: "日本, 〒556-0003 大阪府大阪市浪速区恵美須西１丁目６−６番10号", official_url: "http://www.imamiya-ebisu.jp/"},
  {title: "難波八阪神社", address: "日本, 〒556-0016 大阪府大阪市浪速区元町２丁目９−１９", official_url: "http://nambayasaka.jp/"},
  {title: "石切神社", address: "日本, 〒579-8013 大阪府東大阪市東石切町１丁目１−１", official_url: "http://www.ishikiri.or.jp/"},
  {title: "枚岡神社", address: "日本, 〒579-8033 大阪府東大阪市出雲井町７−１６", official_url: "http://www.hiraoka-jinja.org/"},
  {title: "瓢箪山稲荷神社", address: "日本, 〒579-8051 大阪府東大阪市瓢箪山町８−１", official_url: "http://kamnavi.jp/inari/hyoutan.htm"},
  {title: "布施戎神社", address: "日本, 〒577-0841 大阪府東大阪市足代１丁目１５−２１", official_url: "https://www.facebook.com/fuse.ebisu/"},
  {title: "開口神社", address: "日本, 〒590-0953 大阪府堺市堺区甲斐町東２丁１−２９", official_url: "http://www.aguchi.jp/"},
  {title: "道明寺天満宮", address: "日本, 〒583-0012 大阪府藤井寺市道明寺１丁目１６ 道明寺1丁目16−40", official_url: "http://www.domyojitenmangu.com/"},
  {title: "建水分神社", address: "日本, 〒585-0041 大阪府南河内郡水分 千早赤阪村水分３５７", official_url: "http://www.takemikumari.com/"},
  {title: "伊居太神社", address: "日本, 〒563-0051 大阪府池田市綾羽２丁目４−５", official_url: "http://www.ikeda-jinjya.jp/"},
  {title: "萱島神社", address: "日本, 〒572-0827 大阪府寝屋川市萱島本町19−1 京阪萱島駅高架下", official_url: nil}
])
Program.create!([
  {title: "藍染川", category: "四番目", shimai: true, duration: 27, place_id: 210},
  {title: "葵上", category: "四番目", shimai: true, duration: 29, place_id: 90},
  {title: "阿漕", category: "四番目", shimai: true, duration: 44, place_id: 66},
  {title: "芦刈", category: "四番目", shimai: true, duration: 39, place_id: 197},
  {title: "安宅", category: "四番目", shimai: true, duration: 33, place_id: 122},
  {title: "愛宕空也", category: "五番目", shimai: true, duration: 25, place_id: 51},
  {title: "黒塚", category: "番目", shimai: true, duration: 30, place_id: 45},
  {title: "敦盛", category: "二番目", shimai: true, duration: 56, place_id: 217},
  {title: "海人", category: "五番目", shimai: true, duration: 44, place_id: 222},
  {title: "綾鼓", category: "四番目", shimai: true, duration: 59, place_id: 142},
  {title: "嵐山", category: "一番目", shimai: true, duration: 27, place_id: 217},
  {title: "蟻通", category: "四番目", shimai: true, duration: 4, place_id: 246},
  {title: "淡路", category: "番目", shimai: true, duration: 48, place_id: 31},
  {title: "碇潜", category: "五番目", shimai: true, duration: 31, place_id: 205},
  {title: "生田敦盛", category: "二番目", shimai: true, duration: 26, place_id: 203},
  {title: "一角仙人", category: "五番目", shimai: true, duration: 54, place_id: 240},
  {title: "井筒", category: "三番目", shimai: true, duration: 43, place_id: 33},
  {title: "岩舟", category: "一番目", shimai: true, duration: 29, place_id: 211},
  {title: "鵜飼", category: "五番目", shimai: true, duration: 20, place_id: 81},
  {title: "浮船", category: "四番目", shimai: true, duration: 59, place_id: 16},
  {title: "雨月", category: "四番目", shimai: true, duration: 22, place_id: 44},
  {title: "歌占", category: "四番目", shimai: true, duration: 18, place_id: 115},
  {title: "内外詣", category: "番目", shimai: true, duration: 46, place_id: 190},
  {title: "善知鳥", category: "四番目", shimai: true, duration: 3, place_id: 214},
  {title: "采女", category: "三番目", shimai: true, duration: 51, place_id: 31},
  {title: "梅", category: "番目", shimai: true, duration: 38, place_id: 249},
  {title: "梅枝", category: "四番目", shimai: true, duration: 1, place_id: 165},
  {title: "鱗形", category: "四番目", shimai: true, duration: 33, place_id: 105},
  {title: "雲林院", category: "三番目", shimai: true, duration: 4, place_id: 52},
  {title: "江口", category: "三番目", shimai: true, duration: 40, place_id: 38},
  {title: "江島", category: "一番目", shimai: true, duration: 3, place_id: 48},
  {title: "江野島", category: "番目", shimai: true, duration: 17, place_id: 110},
  {title: "箙", category: "二番目", shimai: true, duration: 2, place_id: 121},
  {title: "烏帽子折", category: "四番目", shimai: true, duration: 42, place_id: 138},
  {title: "絵馬", category: "一番目", shimai: true, duration: 40, place_id: 43},
  {title: "老松", category: "一番目", shimai: true, duration: 29, place_id: 11},
  {title: "大瓶猩猩", category: "五番目", shimai: true, duration: 27, place_id: 13},
  {title: "大江山", category: "五番目", shimai: true, duration: 19, place_id: 156},
  {title: "鸚鵡小町", category: "三番目", shimai: true, duration: 14, place_id: 122},
  {title: "大社", category: "番目", shimai: true, duration: 57, place_id: 173},
  {title: "小塩", category: "三番目", shimai: true, duration: 31, place_id: 247},
  {title: "姨捨", category: "三番目", shimai: true, duration: 10, place_id: 180},
  {title: "大原御幸", category: "三番目", shimai: true, duration: 53, place_id: 117},
  {title: "女郎花", category: "四番目", shimai: true, duration: 22, place_id: 103},
  {title: "杜若", category: "三番目", shimai: true, duration: 51, place_id: 124},
  {title: "籠祇王", category: "三番目", shimai: true, duration: 8, place_id: 241},
  {title: "翁", category: "一番目", shimai: true, duration: 56, place_id: 31},
  {title: "景清", category: "四番目", shimai: true, duration: 53, place_id: 25},
  {title: "花月", category: "四番目", shimai: true, duration: 46, place_id: 80},
  {title: "柏崎", category: "番目", shimai: true, duration: 53, place_id: 149},
  {title: "春日龍神", category: "五番目", shimai: true, duration: 20, place_id: 65},
  {title: "葛城", category: "四番目", shimai: true, duration: 32, place_id: 218},
  {title: "葛城天狗", category: "五番目", shimai: true, duration: 10, place_id: 175},
  {title: "合浦", category: "番目", shimai: true, duration: 46, place_id: 107},
  {title: "鉄輪", category: "四番目", shimai: true, duration: 42, place_id: 194},
  {title: "", category: "二番目", shimai: true, duration: 54, place_id: 106},
  {title: "賀茂", category: "一番目", shimai: true, duration: 31, place_id: 111},
  {title: "通小町", category: "四番目", shimai: true, duration: 56, place_id: 234},
  {title: "邯鄲", category: "四番目", shimai: true, duration: 6, place_id: 154},
  {title: "咸陽殿", category: "番目", shimai: true, duration: 24, place_id: 13},
  {title: "祇王", category: "三番目", shimai: true, duration: 17, place_id: 159},
  {title: "俊寛", category: "番目", shimai: true, duration: 40, place_id: 21},
  {title: "枕慈童", category: "四番目", shimai: true, duration: 11, place_id: 65},
  {title: "木曽", category: "四番目", shimai: true, duration: 53, place_id: 226},
  {title: "砧", category: "四番目", shimai: true, duration: 7, place_id: 36},
  {title: "清経", category: "二番目", shimai: true, duration: 51, place_id: 222},
  {title: "草薙", category: "五番目", shimai: true, duration: 31, place_id: 204},
  {title: "国栖", category: "五番目", shimai: true, duration: 16, place_id: 1},
  {title: "熊坂", category: "五番目", shimai: true, duration: 4, place_id: 195},
  {title: "鞍馬天狗", category: "五番目", shimai: true, duration: 54, place_id: 36},
  {title: "車僧", category: "五番目", shimai: true, duration: 10, place_id: 148},
  {title: "呉服", category: "番目", shimai: true, duration: 55, place_id: 220},
  {title: "黒塚", category: "四番目", shimai: true, duration: 9, place_id: 180},
  {title: "", category: "一番目", shimai: true, duration: 8, place_id: 186},
  {title: "鶴亀", category: "番目", shimai: true, duration: 16, place_id: 60},
  {title: "源氏供養", category: "三番目", shimai: true, duration: 36, place_id: 101},
  {title: "現在七面", category: "四番目", shimai: true, duration: 59, place_id: 220},
  {title: "絃上", category: "五番目", shimai: true, duration: 43, place_id: 75},
  {title: "恋松原", category: "四番目", shimai: true, duration: 60, place_id: 247},
  {title: "恋重荷", category: "四番目", shimai: true, duration: 54, place_id: 192},
  {title: "項羽", category: "五番目", shimai: true, duration: 16, place_id: 74},
  {title: "皇帝", category: "番目", shimai: true, duration: 16, place_id: 76},
  {title: "高野物狂", category: "四番目", shimai: true, duration: 28, place_id: 213},
  {title: "小鍛冶", category: "五番目", shimai: true, duration: 10, place_id: 45},
  {title: "小督", category: "四番目", shimai: true, duration: 7, place_id: 149},
  {title: "小袖曽我", category: "四番目", shimai: true, duration: 12, place_id: 9},
  {title: "胡蝶", category: "三番目", shimai: true, duration: 23, place_id: 71},
  {title: "西行桜", category: "四番目", shimai: true, duration: 54, place_id: 51},
  {title: "佐保山", category: "番目", shimai: true, duration: 5, place_id: 31},
  {title: "逆矛", category: "番目", shimai: true, duration: 45, place_id: 56},
  {title: "鷺", category: "四番目", shimai: true, duration: 56, place_id: 80},
  {title: "桜川", category: "四番目", shimai: true, duration: 38, place_id: 42},
  {title: "桜井", category: "四番目", shimai: true, duration: 49, place_id: 42},
  {title: "桜井駅", category: "四番目", shimai: true, duration: 43, place_id: 90},
  {title: "実方", category: "番目", shimai: true, duration: 25, place_id: 114},
  {title: "実盛", category: "二番目", shimai: true, duration: 28, place_id: 47},
  {title: "志賀", category: "番目", shimai: true, duration: 7, place_id: 193},
  {title: "七騎落", category: "四番目", shimai: true, duration: 15, place_id: 170},
  {title: "自然居士", category: "四番目", shimai: true, duration: 48, place_id: 119},
  {title: "石橋", category: "五番目", shimai: true, duration: 48, place_id: 169},
  {title: "舎利", category: "五番目", shimai: true, duration: 28, place_id: 30},
  {title: "俊寛", category: "四番目", shimai: true, duration: 16, place_id: 48},
  {title: "春栄", category: "番目", shimai: true, duration: 16, place_id: 80},
  {title: "鍾馗", category: "五番目", shimai: true, duration: 19, place_id: 159},
  {title: "昭君", category: "五番目", shimai: true, duration: 7, place_id: 84},
  {title: "猩々", category: "五番目", shimai: true, duration: 43, place_id: 24},
  {title: "正尊", category: "四番目", shimai: true, duration: 20, place_id: 245},
  {title: "白髭", category: "番目", shimai: true, duration: 14, place_id: 130},
  {title: "代主", category: "番目", shimai: true, duration: 55, place_id: 5},
  {title: "須磨源氏", category: "番目", shimai: true, duration: 5, place_id: 153},
  {title: "隅田川", category: "四番目", shimai: true, duration: 37, place_id: 88},
  {title: "住吉詣", category: "番目", shimai: true, duration: 59, place_id: 209},
  {title: "西王母", category: "一番目", shimai: true, duration: 13, place_id: 165},
  {title: "誓願寺", category: "番目", shimai: true, duration: 51, place_id: 48},
  {title: "善界", category: "五番目", shimai: true, duration: 47, place_id: 240},
  {title: "関寺小町", category: "三番目", shimai: true, duration: 23, place_id: 17},
  {title: "殺生石", category: "四番目", shimai: true, duration: 39, place_id: 9},
  {title: "蝉丸 (能)", category: "四番目", shimai: true, duration: 45, place_id: 173},
  {title: "千手", category: "三番目", shimai: true, duration: 47, place_id: 79},
  {title: "草子洗小町", category: "三番目", shimai: true, duration: 4, place_id: 9},
  {title: "卒都婆小町", category: "四番目", shimai: true, duration: 10, place_id: 110},
  {title: "大会", category: "五番目", shimai: true, duration: 47, place_id: 103},
  {title: "泰山府君", category: "五番目", shimai: true, duration: 27, place_id: 81},
  {title: "大仏供養", category: "四番目", shimai: true, duration: 34, place_id: 176},
  {title: "第六天", category: "五番目", shimai: true, duration: 44, place_id: 218},
  {title: "当麻", category: "五番目", shimai: true, duration: 26, place_id: 239},
  {title: "高砂", category: "一番目", shimai: true, duration: 2, place_id: 35},
  {title: "忠信", category: "四番目", shimai: true, duration: 19, place_id: 12},
  {title: "忠度", category: "二番目", shimai: true, duration: 44, place_id: 199},
  {title: "龍田", category: "四番目", shimai: true, duration: 42, place_id: 60},
  {title: "谷行", category: "四番目", shimai: true, duration: 41, place_id: 168},
  {title: "玉鬘", category: "四番目", shimai: true, duration: 27, place_id: 13},
  {title: "田村", category: "二番目", shimai: true, duration: 38, place_id: 91},
  {title: "竹生島", category: "一番目", shimai: true, duration: 53, place_id: 107},
  {title: "土蜘蛛", category: "五番目", shimai: true, duration: 9, place_id: 22},
  {title: "土車", category: "番目", shimai: true, duration: 45, place_id: 104},
  {title: "経正", category: "二番目", shimai: true, duration: 6, place_id: 190},
  {title: "妻戸", category: "五番目", shimai: true, duration: 22, place_id: 174},
  {title: "鶴亀", category: "一番目", shimai: true, duration: 13, place_id: 109},
  {title: "定家", category: "三番目", shimai: true, duration: 6, place_id: 184},
  {title: "点鼓", category: "四番目", shimai: true, duration: 58, place_id: 68},
  {title: "道成寺", category: "四番目", shimai: true, duration: 38, place_id: 160},
  {title: "唐船", category: "四番目", shimai: true, duration: 49, place_id: 153},
  {title: "東方朔", category: "一番目", shimai: true, duration: 46, place_id: 152},
  {title: "東北", category: "三番目", shimai: true, duration: 33, place_id: 232},
  {title: "道明寺", category: "一番目", shimai: true, duration: 25, place_id: 32},
  {title: "融", category: "五番目", shimai: true, duration: 26, place_id: 230},
  {title: "木賊", category: "四番目", shimai: true, duration: 6, place_id: 169},
  {title: "巴", category: "二番目", shimai: true, duration: 47, place_id: 20},
  {title: "朝長", category: "二番目", shimai: true, duration: 27, place_id: 127},
  {title: "知章", category: "二番目", shimai: true, duration: 2, place_id: 67},
  {title: "満仲", category: "番目", shimai: true, duration: 30, place_id: 46},
  {title: "難波", category: "一番目", shimai: true, duration: 50, place_id: 213},
  {title: "錦木", category: "番目", shimai: true, duration: 43, place_id: 107},
  {title: "鵺", category: "五番目", shimai: true, duration: 39, place_id: 114},
  {title: "野宮", category: "三番目", shimai: true, duration: 26, place_id: 145},
  {title: "野守", category: "五番目", shimai: true, duration: 46, place_id: 58},
  {title: "羽衣", category: "三番目", shimai: true, duration: 15, place_id: 128},
  {title: "半蔀", category: "三番目", shimai: true, duration: 4, place_id: 53},
  {title: "橋弁慶", category: "四番目", shimai: true, duration: 21, place_id: 122},
  {title: "芭蕉", category: "番目", shimai: true, duration: 37, place_id: 212},
  {title: "鉢木", category: "四番目", shimai: true, duration: 8, place_id: 102},
  {title: "初雪", category: "三番目", shimai: true, duration: 26, place_id: 92},
  {title: "花軍", category: "三番目", shimai: true, duration: 24, place_id: 236},
  {title: "花筐", category: "四番目", shimai: true, duration: 56, place_id: 27},
  {title: "班女", category: "四番目", shimai: true, duration: 12, place_id: 47},
  {title: "飛雲", category: "五番目", shimai: true, duration: 60, place_id: 1},
  {title: "檜垣", category: "三番目", shimai: true, duration: 15, place_id: 206},
  {title: "雲雀山", category: "四番目", shimai: true, duration: 16, place_id: 185},
  {title: "氷室", category: "番目", shimai: true, duration: 41, place_id: 187},
  {title: "百万", category: "四番目", shimai: true, duration: 41, place_id: 133},
  {title: "豊干", category: "四番目", shimai: true, duration: 60, place_id: 205},
  {title: "富士太鼓", category: "四番目", shimai: true, duration: 25, place_id: 83},
  {title: "藤戸", category: "四番目", shimai: true, duration: 2, place_id: 213},
  {title: "二人静", category: "四番目", shimai: true, duration: 23, place_id: 98},
  {title: "船弁慶", category: "五番目", shimai: true, duration: 7, place_id: 202},
  {title: "放下僧", category: "四番目", shimai: true, duration: 19, place_id: 145},
  {title: "放生川", category: "一番目", shimai: true, duration: 38, place_id: 28},
  {title: "巻絹", category: "四番目", shimai: true, duration: 38, place_id: 232},
  {title: "枕慈童", category: "番目", shimai: true, duration: 38, place_id: 28},
  {title: "枕慈童", category: "番目", shimai: true, duration: 5, place_id: 7},
  {title: "松風", category: "三番目", shimai: true, duration: 48, place_id: 53},
  {title: "松虫", category: "四番目", shimai: true, duration: 56, place_id: 56},
  {title: "松山鏡", category: "四番目", shimai: true, duration: 47, place_id: 7},
  {title: "松山天狗", category: "五番目", shimai: true, duration: 35, place_id: 49},
  {title: "満仲", category: "四番目", shimai: true, duration: 16, place_id: 190},
  {title: "三井寺", category: "四番目", shimai: true, duration: 22, place_id: 122},
  {title: "通盛", category: "二番目", shimai: true, duration: 36, place_id: 19},
  {title: "水無瀬", category: "四番目", shimai: true, duration: 26, place_id: 171},
  {title: "御裳濯", category: "番目", shimai: true, duration: 20, place_id: 203},
  {title: "三輪", category: "四番目", shimai: true, duration: 1, place_id: 97},
  {title: "室君", category: "四番目", shimai: true, duration: 46, place_id: 37},
  {title: "和布刈", category: "一番目", shimai: true, duration: 34, place_id: 203},
  {title: "望月", category: "四番目", shimai: true, duration: 51, place_id: 103},
  {title: "求塚", category: "四番目", shimai: true, duration: 44, place_id: 147},
  {title: "紅葉狩", category: "五番目", shimai: true, duration: 47, place_id: 1},
  {title: "盛久", category: "四番目", shimai: true, duration: 21, place_id: 81},
  {title: "屋島", category: "二番目", shimai: true, duration: 10, place_id: 243},
  {title: "山姥", category: "五番目", shimai: true, duration: 20, place_id: 162},
  {title: "雪", category: "三番目", shimai: true, duration: 53, place_id: 137},
  {title: "遊行桜", category: "三番目", shimai: true, duration: 57, place_id: 82},
  {title: "遊行柳", category: "三番目", shimai: true, duration: 15, place_id: 92},
  {title: "弓八幡", category: "番目", shimai: true, duration: 44, place_id: 65},
  {title: "熊野", category: "三番目", shimai: true, duration: 17, place_id: 120},
  {title: "楊貴妃", category: "三番目", shimai: true, duration: 46, place_id: 138},
  {title: "夜討曽我", category: "四番目", shimai: true, duration: 22, place_id: 226},
  {title: "養老", category: "一番目", shimai: true, duration: 59, place_id: 198},
  {title: "吉野静", category: "番目", shimai: true, duration: 55, place_id: 112},
  {title: "吉野天人", category: "三番目", shimai: true, duration: 41, place_id: 163},
  {title: "頼政", category: "二番目", shimai: true, duration: 40, place_id: 50},
  {title: "弱法師", category: "四番目", shimai: true, duration: 36, place_id: 17},
  {title: "妻戸", category: "番目", shimai: true, duration: 1, place_id: 176},
  {title: "雷電", category: "五番目", shimai: true, duration: 48, place_id: 84},
  {title: "羅生門", category: "五番目", shimai: true, duration: 52, place_id: 8},
  {title: "龍虎", category: "五番目", shimai: true, duration: 13, place_id: 214},
  {title: "輪蔵", category: "四番目", shimai: true, duration: 7, place_id: 213},
  {title: "籠太鼓", category: "四番目", shimai: true, duration: 45, place_id: 209}
])
Style.create!([
  {title: "シテ方観世流"},
  {title: "シテ方金春流"},
  {title: "シテ方金剛流"},
  {title: "ワキ方高安流"},
  {title: "笛方森田流"},
  {title: "小鼓方幸流"},
  {title: "小鼓方大倉流"},
  {title: "大鼓方石井流"},
  {title: "太鼓方観世流"},
  {title: "太鼓方金春流"},
  {title: "狂言方大蔵流"}
])
Ticket.create!([
  {event_id: 1, grade: "後席", price: 5600},
  {event_id: 1, grade: "2階席", price: 5700},
  {event_id: 1, grade: "ワキ見席", price: 5800},
  {event_id: 1, grade: "正面席", price: 6200},
  {event_id: 2, grade: "前売券", price: 5000},
  {event_id: 2, grade: "割引券", price: 5200},
  {event_id: 2, grade: "学生券", price: 5200},
  {event_id: 3, grade: "C席", price: 5300},
  {event_id: 3, grade: "B席", price: 5500},
  {event_id: 3, grade: "A席", price: 5700},
  {event_id: 4, grade: "前売券", price: 5500},
  {event_id: 4, grade: "割引券", price: 5600},
  {event_id: 4, grade: "学生券", price: 5900},
  {event_id: 4, grade: "当日券", price: 6400},
  {event_id: 5, grade: "前売券", price: 5800},
  {event_id: 5, grade: "割引券", price: 6100},
  {event_id: 5, grade: "学生券", price: 6000},
  {event_id: 6, grade: "後席", price: 5400},
  {event_id: 6, grade: "2階席", price: 5600},
  {event_id: 6, grade: "ワキ見席", price: 6000},
  {event_id: 7, grade: "前売券", price: 4500},
  {event_id: 7, grade: "割引券", price: 4800},
  {event_id: 7, grade: "学生券", price: 5100},
  {event_id: 8, grade: "前売券", price: 4500},
  {event_id: 8, grade: "割引券", price: 4700},
  {event_id: 8, grade: "学生券", price: 5100},
  {event_id: 8, grade: "当日券", price: 5100},
  {event_id: 8, grade: "正面券", price: 5300},
  {event_id: 9, grade: "前売券", price: 5800},
  {event_id: 9, grade: "割引券", price: 6000},
  {event_id: 9, grade: "学生券", price: 6400},
  {event_id: 9, grade: "当日券", price: 6400},
  {event_id: 9, grade: "正面券", price: 7000},
  {event_id: 10, grade: "後席", price: 5700},
  {event_id: 10, grade: "2階席", price: 6000},
  {event_id: 10, grade: "ワキ見席", price: 6300},
  {event_id: 11, grade: "前売券", price: 5700},
  {event_id: 11, grade: "割引券", price: 6000},
  {event_id: 11, grade: "学生券", price: 5900},
  {event_id: 11, grade: "当日券", price: 6000},
  {event_id: 12, grade: "C席", price: 5300},
  {event_id: 12, grade: "B席", price: 5500},
  {event_id: 12, grade: "A席", price: 5700},
  {event_id: 13, grade: "前売券", price: 5600},
  {event_id: 13, grade: "割引券", price: 5800},
  {event_id: 13, grade: "学生券", price: 6200},
  {event_id: 13, grade: "当日券", price: 6500},
  {event_id: 14, grade: "C席", price: 6000},
  {event_id: 14, grade: "B席", price: 6200},
  {event_id: 14, grade: "A席", price: 6600},
  {event_id: 14, grade: "S席", price: 6900},
  {event_id: 14, grade: "SS席", price: 6400},
  {event_id: 15, grade: "前売券", price: 5600},
  {event_id: 15, grade: "割引券", price: 5800},
  {event_id: 15, grade: "学生券", price: 6200},
  {event_id: 15, grade: "当日券", price: 6500},
  {event_id: 15, grade: "正面券", price: 6000},
  {event_id: 16, grade: "後席", price: 5200},
  {event_id: 16, grade: "2階席", price: 5500},
  {event_id: 16, grade: "ワキ見席", price: 5600},
  {event_id: 16, grade: "正面席", price: 6100},
  {event_id: 16, grade: "特等席", price: 6000},
  {event_id: 17, grade: "前売券", price: 5800},
  {event_id: 17, grade: "割引券", price: 6100},
  {event_id: 17, grade: "学生券", price: 6200},
  {event_id: 18, grade: "後席", price: 5200},
  {event_id: 18, grade: "2階席", price: 5400},
  {event_id: 18, grade: "ワキ見席", price: 5800},
  {event_id: 18, grade: "正面席", price: 6100},
  {event_id: 18, grade: "特等席", price: 5600},
  {event_id: 19, grade: "C席", price: 5000},
  {event_id: 19, grade: "B席", price: 5200},
  {event_id: 19, grade: "A席", price: 5400},
  {event_id: 20, grade: "C席", price: 5700},
  {event_id: 20, grade: "B席", price: 5900},
  {event_id: 20, grade: "A席", price: 5900},
  {event_id: 20, grade: "S席", price: 6000}
])
User.create!([
  {name: "例　学士", email: "example@gmail.com", password_digest: "$2a$10$yhakT9M5Ji9hUGIK/q0mA.gHsx6gioFRAkAX2MtSjFKGzCgRAI.aC"},
  {name: "例　見習", email: "pupil@gmail.com", password_digest: "$2a$10$PYGexhwQshcm4qGhw..DHeKu8ofWHQQUziREcqJlamzeS4z29UWFO"},
  {name: "例　師匠", email: "master@gmail.com", password_digest: "$2a$10$D0luCs5p1dwBkxmkj6zi7OBAv5WIAVfMMjPiJ8bhlEXQ4x9.BUAQS"}
])
